/**
 * Видимые тексты своих блоков — второй кусок каталога (10.13.47, В-67):
 * редактор Fields, Smart Rules, Binder, свои теги, списки порядка.
 *
 * Устройство то же, что у окон (`texts_dialogs.ts`, У-82):
 *   * владелец — сам блок, тем же id, что у `kind: "custom"` в схеме;
 *   * ключ — `block.<владелец>.<имя>`;
 *   * собираемые строки — с `{0}`, не склейкой через `+`: порядок слов в языках разный.
 *
 * Место в файле каталога — у строки блока в схеме (`blockEntries` в `texts_custom.ts`).
 */

/** Строки, которые рисует один блок. Порядок — порядок чтения на экране. */
export const BLOCK_TEXTS = {
  /* ---- знак наверху General: строка README, она же описание манифеста без точки (цикл 134) */
  "brand-mark": {
    TAGLINE: "Turn a raw thought into a structured line without leaving it",
  },
  /* ---- редактор Fields: сам блок, его окна, проверки имён -------------- */
  "field-editor": {
    /* Левая колонка: список Fields. */
    /*
     * Смысл подписей сторон — здесь: колонка списка 188 точек, подсказка встала
     * бы столбиком (У-105). Знака «?» у `Left Block`/`Right Block` нет —
     * объявленное исключение из «tip у всех элементов» (2026-09-08).
     */
    /* Подсказка списка — двумя блоками с легендой значков (его 💬 к тесту 1 цикла 131). */
    LIST_TIP_BLOCKS: "<b>Blocks</b> — where on the line a Field is written",
    LEGEND_LEFT: "before your text",
    LEGEND_RIGHT: "after your text",
    LEGEND_CUSTOM: "<b>Add Block</b> makes one: its Fields are written where the cursor is, by its own tagWheel command",
    LEGEND_CUSTOM_NAME: "Custom block",
    LEGEND_RENAME: "Rename a custom block; its tagWheel command follows the new name",
    LEGEND_DELETE: "Delete a custom block together with its Fields",
    LIST_TIP_FIELDS: "<b>Fields</b> — what is written: one row is one Field",
    LEGEND_GRIP: "Drag to reorder, or into another Block",
    LEGEND_ARROWS: "Move one place; at the edge of a Block, into the next Block. Works from the keyboard",
    LEGEND_TAG: "<b>Tag</b> writes a tag, such as <code>#todo</code>",
    LEGEND_LINK: "<b>Link</b> writes a link to a note, such as <code>[[John]]</code>",
    LEGEND_EMOJI: "<b>Emoji</b> writes an emoji, such as <code>💡</code>",
    LEGEND_ACTION: "<b>Action</b> edits the line, such as wrapping it in a callout; it writes no Value",
    EMPTY_SIDE: "nothing on this side",
    SIDE_LEFT: "Left Block",
    SIDE_RIGHT: "Right Block",
    /* Родная подсказка Obsidian у подписи стороны: одна на узел, только `aria-label` (У-21). */
    SIDE_LEFT_ABOUT: "Everything in Left Block is written before your text on the line",
    SIDE_RIGHT_ABOUT: "Everything in Right Block is written after your text on the line",
    TYPE_TAG: "Tag",
    TYPE_LINK: "Link",
    TYPE_ELEMENT: "Emoji",
    /* Короче `Command`: чип не съедает имя Field (его пункт «Новое» 2026-10-03). */
    TYPE_COMMAND: "Action",
    /* Command Field: категории и пресеты вместо Values (постановка command-field.md, 4.1). */
    CATS_HEAD: "Categories",
    CATS_TIP: "A category is one kind of edit, such as <b>Insert callout</b>. Its presets are ready-made versions of it, such as a <b>Note</b> or a <b>Tip</b> callout. Each category gets its own <code>next</code> and <code>previous</code> commands:\n- <b>Outside its result</b> — <code>next</code> puts in the first preset, <code>previous</code> the last: <code>- call Anna</code> → <code>> [!note]</code> with <code>> - call Anna</code> under it\n- <b>Inside it</b> — the commands step through the presets: <code>[!note]</code> → <code>[!tip]</code>. One step past the end takes the callout off\nNothing here is written into the line as a Value",
    CATS_COL_NAME: "Name",
    CATS_COL_NAME_TIP: "What tagWheel and its scroller call this category or preset\n- <b>Empty</b> — the name is built from its settings, such as <code>Note · closed</code> for a closed note callout\n- <b>Your text</b> — <code>Meeting</code> is shown instead",
    CATS_COL_SETTINGS: "Settings",
    CATS_COL_SETTINGS_TIP: "What the preset does. Each category names its settings in the row under it; point at a choice to see what it does",
    CATS_EMPTY: "No categories yet — pick one below and press Add category",
    CATS_ADD: "Add category",
    /* Прочерк серым — пустой выбор, а не вариант (его пункт «Новое» 2026-10-03). */
    CATS_PICK_PLACEHOLDER: "—",
    CATS_PICK_ARIA: "Category to add to {0}",
    CAT_DESC_CALLOUTS: "Wraps the line and its tree, or the selected lines, in a callout; inside one, steps through the presets and then takes the callout off",
    CAT_DESC_CLEANUP: "Takes the Values of your Fields off the line or the selected lines, except the Fields you keep",
    CAT_DESC_SECTION: "On a list item, turns it and its tree into a section under a heading; on a heading, turns the section back into a list item with its tree. Your Fields stay in the heading",
    CAT_DESC_BLOCK: "On an empty line, inserts your text, such as a code block of another plugin, as it is, under a heading or in a callout; inside it, steps through the presets and then takes the block off, keeping the lines you added",
    /* Подписи колонок пресета — строка под категорией (его 💬 к тесту 2 цикла 126). */
    CAP_TYPE: "Type",
    CAP_TYPE_TIP: "The kind of callout; its icon and color come from your theme",
    CAP_FOLD: "Fold",
    CAP_FOLD_TIP: "Whether the callout starts open or folded",
    CAP_KEEP: "Keep",
    CAP_KEEP_TIP: "The Fields whose Values stay on the line; the Values of all other Fields are taken off",
    CAP_LEVEL: "Heading",
    CAP_LEVEL_TIP: "The level of the heading the list item becomes",
    CAP_PLACE: "Where",
    CAP_PLACE_TIP: "Where the new section goes",
    CAP_CODE: "Code blocks",
    CAP_CODE_TIP: "What happens to the code blocks of a section when it turns back into a tree",
    CAP_TABLES: "Tables",
    CAP_TABLES_TIP: "What happens to the tables of a section when it turns back into a tree",
    CAP_WRAP: "Wrap",
    CAP_WRAP_TIP: "What goes around your text: nothing, a heading above it or a callout around it",
    CAP_HEADING_TEXT: "Heading",
    CAP_HEADING_TEXT_TIP: "The text of the heading above your text",
    CAP_BLOCK_LEVEL: "Level",
    CAP_BLOCK_LEVEL_TIP: "The level of the heading; Auto puts it one level below the heading above",
    CAP_TITLE: "Title",
    CAP_TITLE_TIP: "The title of the callout; leave it empty for the name of its type",
    CAP_TEXT: "Text",
    CAP_TEXT_TIP: "What the preset inserts, such as a code block of another plugin",
    CAT_DRAG: "Drag {0} to reorder",
    CAT_HIDE: "Hide {0}",
    CAT_SHOW: "Show {0}",
    CAT_NAME_ARIA: "Name of the category {0}",
    CAT_CLONE: "Clone the category {0}",
    CAT_REMOVE: "Remove the category {0}",
    COPY_OF: "{0} (copy)",
    PRESET_NAME_ARIA: "Name of the preset {0}",
    PRESET_TYPE_ARIA: "Callout type of {0}",
    PRESET_FOLD_ARIA: "Fold of {0}",
    /* Варианты выбора: подпись и подсказка при наведении (его пункт «Новое» 2026-10-03). */
    FOLD_OPEN: "Open",
    FOLD_OPEN_TIP: "The callout shows its text",
    FOLD_CLOSED: "Closed",
    FOLD_CLOSED_TIP: "The callout starts folded: only its title shows until you click it",
    PRESET_KEEP_ARIA: "Keep the Values of {0}",
    PRESET_CONTENT_ARIA: "Text that {0} inserts",
    PRESET_CONTENT_PLACEHOLDER: "Text or a code block to insert",
    PRESET_MODE_ARIA: "Wrap of {0}",
    PRESET_HEADING: "Heading",
    PRESET_HEADING_TEXT_ARIA: "Heading text of {0}",
    PRESET_LEVEL_ARIA: "Heading level of {0}",
    PRESET_TITLE_ARIA: "Callout title of {0}",
    PRESET_TITLE_PLACEHOLDER: "Callout title",
    PRESET_PLACE_ARIA: "Where the section of {0} goes",
    PRESET_CODE_ARIA: "Code blocks of {0}",
    PRESET_TABLES_ARIA: "Tables of {0}",
    MODE_PLAIN: "No (Plain)",
    MODE_PLAIN_TIP: "Inserts your text as it is",
    MODE_HEADING: "Heading",
    MODE_HEADING_TIP: "Inserts a heading and your text under it",
    MODE_CALLOUT: "Callout",
    MODE_CALLOUT_TIP: "Inserts a callout with your text inside it",
    LEVEL_AUTO: "Auto",
    LEVEL_AUTO_TIP: "One level below the heading above the line; H1 when there is none, never deeper than H6",
    LEVEL_FIXED_TIP: "This level wherever the line is",
    SECTION_PLACE_AFTER_LIST: "After list",
    SECTION_PLACE_AFTER_LIST_TIP: "The section goes right after the list the item is in",
    SECTION_PLACE_IN_PLACE: "In place",
    SECTION_PLACE_IN_PLACE_TIP: "The section takes the place of the item; the lines after its tree become the body of the section",
    SECTION_PLACE_SECTION_END: "Section end",
    SECTION_PLACE_SECTION_END_TIP: "The section goes at the end of the section the item is in, before the next heading of the same level",
    SECTION_CODE_NEST: "Nested",
    SECTION_CODE_NEST_TIP: "Code blocks go into the tree, indented under their item",
    SECTION_CODE_AFTER: "After tree",
    SECTION_CODE_AFTER_TIP: "Code blocks go after the tree as they are",
    SECTION_TABLES_AFTER: "After tree",
    SECTION_TABLES_AFTER_TIP: "Tables go after the tree: Obsidian does not draw a table inside a list item",
    SECTION_TABLES_KEEP: "In place",
    SECTION_TABLES_KEEP_TIP: "Tables stay where they are, without an indent",
    PRESET_SAME: "same as {0} — that one is used",
    PRESET_CLONE: "Clone the preset {0}",
    PRESET_REMOVE: "Remove the preset {0}",
    ADD_FIELD: "Add Field",
    ADD_FIELD_LABEL: "Add a Field",
    /* Custom block (10.13.260): кнопка, подпись раздела и две его кнопки. */
    ADD_BLOCK: "Add Block",
    ADD_BLOCK_LABEL: "Add a custom block",
    NEW_BLOCK_NAME: "Custom block {0}",
    SIDE_CUSTOM_ABOUT: "Everything in {0} is written where the cursor is, by its own tagWheel command",
    RENAME_BLOCK: "Rename the block {0}",
    DELETE_BLOCK: "Delete the block {0}",
    NO_FIELD_PICKED: "add a Field on the left to set it up here",
    LIST_ARIA: "the Fields list",
    COLUMN_ARIA: "this column",
    /* Подпись называет то, что случится по нажатию: знак кнопки уже показывает режим. */
    HEIGHT_EXPAND: "Expand the Fields table to its full height",
    HEIGHT_COLLAPSE: "Collapse the Fields table to a fixed height",
    /* Подписи строк, собранные вокруг имени Field. */
    SHOW_FIELD: "Show the Field {0}",
    RENAME_FIELD: "Rename the Field {0}",
    DELETE_FIELD: "Delete the Field {0}",
    DRAG_FIELD: "Drag {0} to reorder it, or across the line to change side",
    DRAG_CHILD_FIELD: "Drag {0} — it moves with {1}",
    MOVE_FIELD_UP: "Move {0} up, and across the line at the top",
    MOVE_FIELD_DOWN: "Move {0} down, and across the line at the bottom",
    /* Правая колонка: шапка и разделы. */
    DETAIL_TIP: "Everything about the Field you picked on the left: its name in tagWheel, its Values, how it acts on a line and which note property it goes into. Nothing here changes the other Fields. Pick another Field on the left and this whole column switches to it",
    SHORT_NAME_NAME: "Name in tagWheel",
    SHORT_NAME_DESC: "Shorter name for parent Field in tagWheel panel",
    SHORT_SUB_NAME: "Child name in tagWheel",
    SHORT_SUB_DESC: "Shorter name for child Field in tagWheel panel",
    SHORT_SUB_TIP: "The child Field sits right after its parent in tagWheel and is called <b>sub</b> there. Type a name to use instead\n- <b>Empty</b> — tagWheel shows <code>sub</code>\n- <b>Stage</b> — tagWheel shows <code>Stage</code>",
    SHORT_NAME_TIP: "tagWheel puts every Field side by side, so a long name crowds its neighbors. Only tagWheel uses this name, your notes and commands keep the full one\n- <b>Importance</b> → <b>Imp</b> — the tagWheel row stays readable",
    /* Раздел Behavior. */
    BEHAVIOR_HEAD: "Behavior",
    BEHAVIOR_HEAD_TIP: "Three things about how this Field acts, and none about what it writes:\n- <b>Active</b> — turns its commands on and off without deleting the Field\n- <b>Prefix behavior</b> — decides whether a Value may change the marker at the start of the line, a checkbox for instance\n- <b>Child Field</b> — ties this Field to another one, so it comes into play only once that one is on the line",
    ACTIVE_NAME: "Active",
    ACTIVE_DESC: "Whether this Field is offered, and where",
    ACTIVE_TIP: "- <b>Yes</b> — tagWheel shows the Field and its commands work: <code>Type next</code> turns <code>- call Anna</code> into <code>- [ ] #todo :: call Anna</code>\n- <b>No</b> — the Field is off everywhere: tagWheel hides it and <code>Type next</code> leaves the line as it is\n- <b>Commands only</b> — <code>Type next</code> still works, but tagWheel hides the Field",
    ACTIVE_YES: "Yes",
    ACTIVE_NO: "No",
    ACTIVE_COMMANDS_ONLY: "Commands only",
    ACTIVE_FOR: "Active, for {0}",
    BEHAVIOR_NAME: "Prefix behavior",
    BEHAVIOR_DESC: "How this Field affects the line Prefix",
    BEHAVIOR_STRICT: "Strict",
    BEHAVIOR_INSERT_ONLY: "Insert only",
    BEHAVIOR_TIP: "- <b>Strict</b> — the Value also sets the start of the line, such as its checkbox: <code>call Anna</code> → <code>- [ ] #todo :: call Anna</code>\n- <b>Insert only</b> — the Value is added and a plain line stays plain: <code>call Anna</code> → <code>#todo :: call Anna</code>\nFine-tune both under <code>Placement modes</code>. A Field that should go where the cursor is belongs in a custom block: <code>Add Block</code> under the Fields list",
    BEHAVIOR_FOR: "Behavior for {0}",
    CHILD_NAME: "Child Field",
    CHILD_DESC: "When the child Field is offered: after a parent Value, always, on an Alt press, or never",
    CHILD_TIP: "A child Field holds the Values marked child in the table below, such as <code>#work/report</code> under <code>#work</code>\n- <b>After parent</b> — works once the parent is on the line: <code>- #work :: call Anna</code> → <code>- #work #work/report :: call Anna</code>. Pressing <code>Alt</code> on the parent opens it earlier\n- <b>Always</b> — works on any line: <code>- call Anna</code> → <code>- #work/report :: call Anna</code>\n- <b>On Alt</b> — hidden in tagWheel until you press <code>Alt</code> on the parent. Then you can pick a child Value even without the parent. Press <code>Alt</code> again to hide it, and the Value stays. Commands work as with <b>After parent</b>\n- <b>Hide</b> — never offered, not in tagWheel and not in commands\n<code>Alt</code> pressed together with another key is a hotkey and does not open it",
    CHILD_ALWAYS: "Always",
    CHILD_AFTER_PARENT: "After parent",
    CHILD_ALT: "On Alt",
    CHILD_HIDE: "Hide",
    CHILD_OF: "Child Field of {0}",
    CHILD_PARENT_NAME: "Parent Value",
    CHILD_PARENT_DESC: "What happens to the parent when a child Value is set without it",
    CHILD_PARENT_TIP: "Shown only with <b>Always</b>. What a child command writes on a line without the parent:\n- <b>Child only</b> — <code>- call Anna</code> → <code>- #work/report :: call Anna</code>\n- <b>Add parent Value</b> — <code>- call Anna</code> → <code>- #work #work/report :: call Anna</code>",
    CHILD_PARENT_KEEP: "Child only",
    CHILD_PARENT_ADD: "Add parent Value",
    CHILD_PARENT_OF: "Parent Value for {0}",
    CHILD_NAV_NAME: "Parent is Navigator",
    CHILD_NAV_DESC: "Parent Values only narrow the child list and are never written to the line",
    CHILD_NAV_TIP: "Use it when the parent Values are only groups, not Values of their own\n- <b>On</b> — in tagWheel a parent only narrows the child list, and only the child is written: <code>- call Anna</code> → <code>- #work/report :: call Anna</code>. The parent command skips parents that have children: <code>- call Anna</code> → <code>- #home :: call Anna</code>\n- <b>Off</b> — the parent is an ordinary Value: the parent command writes <code>#work</code>\nA child on the line counts as its parent for Fields and Smart Rules that wait for it. Not available with <b>Hide</b>",
    CHILD_NAV_ON: "On",
    CHILD_NAV_OFF: "Off",
    CHILD_NAV_OF: "Parent is Navigator for {0}",
    YAML_NAV_NAME: "YAML of navigator values",
    YAML_NAV_DESC: "Write the navigator of a child Value into this Field's property too",
    YAML_NAV_TIP: "A navigator is never written to the line, so on its own it never reaches the note. This works with <code>Inline to note</code>\n- <b>On</b> — for <code>#work/report</code> the note gets <code>#work</code> in this Field's property and <code>#work/report</code> in the child's property\n- <b>Off</b> — only <code>#work/report</code> is written\nA child under two navigators writes both, as a list",
    YAML_NAV_OF: "YAML of navigator values for {0}",
    PREREQ_NAME: "Prerequisite Field",
    PREREQ_DESC: "Show this Field only after another Field has a Value",
    PREREQ_TIP: "- <b>No</b> — the Field is always offered\n- <b>Yes</b> — it waits for another Field to have a Value. If Importance waits for Type, <code>- call Anna</code> stays as it is, and <code>- #idea :: call Anna</code> → <code>- #idea #high :: call Anna</code>\nA new Value in the Field it waits for clears this one: <code>- [ ] #todo #high :: call Anna</code> → <code>- #idea :: call Anna</code>",
    PREREQ_YES: "Yes",
    PREREQ_NO: "No",
    PREREQ_PICK_NAME: "Choose prerequisite Field",
    PREREQ_PICK_DESC: "Which Field this one waits for",
    PREREQ_PICK_TIP: "This Field can wait for any other Field, of any type. Two Tag Fields tied this way also stay side by side in the line: <code>- #idea #high :: call Anna</code>",
    PREREQ_NOT_CHOSEN: "Not chosen",
    PREREQ_VALUE_NAME: "Prerequisite Value",
    PREREQ_VALUE_DESC: "Which Value of that Field this one waits for",
    PREREQ_VALUE_TIP: "- <b>Any Value</b> — this Field appears as soon as the Field it waits for has any Value: both <code>#idea</code> and <code>#todo</code> let <code>#high</code> in\n- <b>One Value</b> — such as <code>#todo</code>: <code>- #idea :: call Anna</code> stays as it is, and <code>- [ ] #todo :: call Anna</code> → <code>- [ ] #todo #high :: call Anna</code>",
    PREREQ_ANY_VALUE: "Any Value",
    /* Раздел Values. */
    VALUES_TIP: "<code>next</code> and <code>previous</code> walk this list in order, and one step past the end takes the Value off: <code>#idea</code> → <code>#mem</code>, and <code>#done</code> → no tag. A child Value follows its parent: it sits in the same Block and uses the parent’s <code>Prefix behavior</code>",
    ELEMENT_VALUE_TIP: "An element Field holds one Value right after its emoji, such as <code>📅2026-10-10</code>, <code>🕒1435</code> or <code>🔢007</code>. The rows below set the emoji, the format of the Value and how <code>next</code> and <code>previous</code> change it",
    VALUES_EMPTY: "no Values yet — add the first one below",
    LEVEL_TIP: "change Value to be parent or child by pressing arrows. Child Values are only active when Parent Value is present",
    VALUE_LINK_TIP: "The note this Value links to. <code>[[Anna]]</code> and <code>Anna</code> are the same Value, and the line gets <code>[[Anna]]</code>\n- <b>Eye open</b> — <code>next</code>, <code>previous</code> and tagWheel offer the Value\n- <b>Eye closed</b> — they skip it, but a line that already has it still reads it",
    VALUE_TAG_TIP: "The text of the Value. <code>#todo</code> and <code>todo</code> are the same Value, and the line gets <code>#todo</code>\n- <b>Eye open</b> — <code>next</code>, <code>previous</code> and tagWheel offer the Value: <code>#idea</code> → <code>#mem</code>\n- <b>Eye closed on #mem</b> — they skip it: <code>#idea</code> → <code>#question</code>. A line that already has <code>#mem</code> still reads it",
    VALUE_PREFIX_TIP: "The checkbox this Value puts at the start of the line\n- <b>[ ]</b> — <code>- call Anna</code> → <code>- [ ] #todo :: call Anna</code>\n- <b>no</b> — the usual list marker stays: <code>- call Anna</code> → <code>- #high :: call Anna</code>",
    VALUE_SHOWN_TIP: "How the Value looks in the editor. The text of the note does not change\n- <b>default</b> — shows the Value: <code>#todo</code>\n- <b>empty</b> — shows only its colored bubble, with no text\n- <b>custom</b> — shows your text instead, such as <code>TODO</code>",
    /* Подсказки 2026-09-08: `Text` — это цвет надписи, контраст — в `Preview`. */
    VALUE_FILL_TIP: "The color of the bubble drawn behind this Value in the line. Untouched it comes from your theme, and the round arrow at the end of the row puts it back there",
    VALUE_TEXT_TIP: "The color of the writing inside that bubble — not the text of the Value, which is the <code>Value</code> column. If the two colors read badly together, <code>Preview</code> says so",
    VALUE_SIDE_TIP: "The color of the bubble outline. Untouched it comes from your theme. Pure white means no outline, and in <code>Fill</code> it means no fill",
    VALUE_PREVIEW_TIP: "This Value drawn the way the editor draws it, with both colors and the <code>Show</code> choice. It is not a setting: it shows what the columns to its left build. A warning sign means the two colors are too close to read, with the contrast it measured",
    SHOWN_DEFAULT: "default",
    SHOWN_EMPTY: "empty",
    SHOWN_CUSTOM: "custom",
    VALUE_DRAG: "Drag {0} to reorder it",
    VALUE_MAKE_PARENT: "Make {0} a top-level Value",
    VALUE_MAKE_CHILD: "Make {0} a child Value",
    VALUE_PREFIX_NO: "no",
    VALUE_PREFIX_FOR: "Prefix for {0}",
    /* Выбиралка Prefix (2026-09-28): вид чекбокса рисует тема. */
    PREFIX_PICK_HINT: "How each checkbox looks with your theme. Click one to use it, or type your own",
    PREFIX_PICK_NONE: "No checkbox",
    /* `VALUE_PREFIX_HINT` снята (A46, У-71): дубль `ERR_PREFIX_TOKEN`, на экране не было. */
    VALUE_SHOWN_FOR: "Show, for {0}",
    VALUE_CUSTOM_PLACEHOLDER: "printed instead",
    VALUE_CUSTOM_FOR: "Custom text for {0}",
    VALUE_FILL_COLOR: "Fill color",
    /*
     * Имена контролов строки Value без имени значения — для «что изменилось»
     * автокопии (значение там строкой выше). `VALUE_SHOWN_FOR`/`VALUE_CUSTOM_FOR` —
     * `aria-label` пикера с именем значения.
     */
    VALUE_TEXT_COLOR: "Text color",
    VALUE_SIDE_COLOR: "Side color",
    VALUE_SHOWN_NAME: "Show",
    VALUE_CUSTOM_NAME: "Custom text",
    VALUE_RESET_COLORS: "Reset the colors of {0} back to the colors of the theme",
    VALUE_REMOVE: "Remove {0}",
    /* Глаз у Value (его ответ 5 к разбору Command Field, В-278): скрыть из перебора и скроллера. */
    VALUE_HIDE: "Hide {0} from next, previous and tagWheel",
    VALUE_SHOW: "Show {0} in next, previous and tagWheel",
    NEW_VALUE_LINK_HINT: "[[wikilink]] / wikilink",
    NEW_VALUE_TAG_HINT: "#tag / tag",
    NEW_VALUE_FOR: "New Value for {0}",
    ADD_VALUE: "Add Value",
    ADD_VALUE_TO: "Add a Value to {0}",
    /* Раздел эмодзи-элемента. */
    ELEMENT_EMOJI_NAME: "Emoji prefix",
    ELEMENT_EMOJI_DESC: "The character that stands in front of the Value in the line",
    ELEMENT_EMOJI_TIP: "This emoji is how the plugin finds the Field in a line: <code>📅2026-10-10</code> is read as this Field only because <code>📅</code> stands in front. Give each Field its own emoji, or the plugin takes two Fields for one",
    ELEMENT_EMOJI_HINT: "one character or emoji",
    /* Выбиралка эмодзи (`В-182`): вкладка одна, подпись не нужна; у Element-списка —
       три вкладки Binder с теми же подписями. */
    PICK_EMOJI: "Emoji",
    PICK_SYMBOLS: "Symbol",
    PICK_FACES: "Kaomoji",
    PICK_SEARCH: "Search by name",
    PICK_EMPTY: "Nothing by that name — paste your own character into the field",
    ELEMENT_FORMAT_NAME: "Value format",
    ELEMENT_FORMAT_DESC: "The shape of the Value: a date, a time or a number",
    ELEMENT_FORMAT_HINT: "YYYY-MM-DD / HHmm / 1",
    ELEMENT_FORMAT_TIP: "Write the shape you want to see in the line\n- <code>YYYY-MM-DD</code> — the date: <code>📅2026-10-04</code>\n- <code>YY-MM-DD</code>, <code>DD.MM</code> — a short date: <code>📅26-10-04</code>, <code>📅04.10</code>\n- <code>HHmm</code> — the time: <code>🕒1435</code>. <code>ss</code> adds seconds\n- <code>1</code>, <code>001</code> — a counter that keeps that many digits: <code>1</code>, <code>2</code> or <code>001</code>, <code>002</code>\nAnything else is plain text and never steps",
    ELEMENT_STEP_NAME: "Steps by",
    ELEMENT_STEP_DESC: "What should happen with the Value when you use <code>next</code> or <code>previous</code> command",
    ELEMENT_STEP_TIP: "What <code>next</code> and <code>previous</code> do to the Value\n- <b>Fixed step</b> — add or take away the same amount: <code>📅2026-12-10</code> → <code>📅2026-12-11</code>, <code>🔢009</code> → <code>🔢010</code>\n- <b>Command</b> — <code>next</code> writes a fresh Value each time, such as the time of the press or a random id. <code>previous</code> removes it\n- <b>Custom step</b> — walks steps you write yourself and can remove the Value at the end\n- <b>List of Values</b> — walks your own list, such as <code>🤡</code> → <code>💭</code>, the way a tag walks its Values",
    STEP_FIXED: "Fixed step",
    STEP_COMMAND: "Command",
    STEP_CUSTOM: "Custom step",
    STEP_LIST: "List of Values",
    ELEMENT_STEP_FOR: "Steps by, for {0}",
    ELEMENT_AMOUNT_NAME: "Amount",
    ELEMENT_AMOUNT_DESC: "How much one press adds to the Value",
    ELEMENT_AMOUNT_TIP: "<code>next</code> adds this much, <code>previous</code> takes it back. The unit comes from <code>Value format</code>:\n- <code>YYYY-MM-DD</code> — days: with <b>1</b>, <code>📅2026-12-10</code> → <code>📅2026-12-11</code>\n- <code>HHmm</code> — minutes: <code>🕒1431</code> → <code>🕒1432</code>\n- <b>Counter</b> — ones: <code>🔢009</code> → <code>🔢010</code>\nA date before today jumps to today, and <code>previous</code> on today removes it",
    ELEMENT_AMOUNT_FOR: "Amount for {0}",
    ELEMENT_COMMAND_NAME: "Command",
    ELEMENT_COMMAND_DESC: "What the press writes into the Value instead of stepping it",
    ELEMENT_COMMAND_TIP: "What <code>next</code> writes each time. <code>previous</code> removes the Value\n- <b>Current date and time</b> — the moment of the press in your <code>Value format</code>: <code>🕒2026-10-04 17:27</code>\n- <b>Random numbers</b> — digits, as many as the format has: <code>🆔120163</code> for <code>000000</code>\n- <b>Random characters</b> — letters and digits, good for an id: <code>🆔39S5N6</code>",
    COMMAND_NOW: "Current date and time",
    COMMAND_RANDOM_NUMBERS: "Random numbers",
    COMMAND_RANDOM_CHARS: "Random characters",
    ELEMENT_COMMAND_FOR: "Command for {0}",
    ELEMENT_STEPS_NAME: "Steps",
    ELEMENT_STEPS_DESC: "One step per line, in the order the presses walk them",
    ELEMENT_STEPS_TIP: "One step per line. A number in brackets says how many presses use that step, and <code>END</code> removes the Value\n- <code>1 (2)</code>, <code>5</code>, <code>END</code> — <code>next</code> counts <code>🔢1</code>, <code>🔢2</code>, <code>🔢3</code>, <code>🔢8</code>, then removes the Value",
    ELEMENT_STEPS_FOR: "Steps for {0}",
    ELEMENT_LIST_NAME: "Values",
    ELEMENT_LIST_DESC: "One Value per line, in the order <code>next</code> walks them",
    ELEMENT_LIST_TIP: "One Value per line, each with its own emoji in front, such as <code>🙂‍↕️yes</code>, or an emoji alone, such as <code>💡</code>. <code>next</code> walks them in order, <code>🤡</code> → <code>💭</code>, and after the last one it removes the Value, the way a tag ends its cycle",
    ELEMENT_LIST_FOR: "Values for {0}",
    /*
     * Раздел `Commands` (`З-33`): команды Field и их хоткеи. Подписи колонок
     * свои (колонок две, у справочника три); общий дом — способ спросить
     * хоткей (`hotkeys.ts`).
     */
    COMMANDS_HEAD: "Commands",
    COMMANDS_HEAD_TIP: "Every command this Field has now, and its hotkey. A Field gets <code>next</code> and <code>previous</code>, such as <code>Type next</code>, and a child Field adds its own pair. The list follows the Field when you rename it or switch it off. Click a hotkey cell to set the key in Obsidian’s <code>Hotkeys</code> screen. The plugin sets no keys by itself",
    COMMANDS_COL_NAME: "Command",
    COMMANDS_COL_HOTKEY: "Hotkey",
    COMMANDS_EMPTY: "This Field has no commands right now",
    /* Подписи кнопки хоткея — у каждого блока свои: владелец текста — блок, где он нарисован (10.13.47). */
    HOTKEY_NOT_SET: "not set",
    HOTKEY_CHANGE: "Change the hotkey for {0}",
    HOTKEY_ASSIGN: "Assign a hotkey to {0}",
    HOTKEY_OPEN: "Open Obsidian’s Hotkeys settings at this command",
    /* Раздел YAML. */
    YAML_HEAD: "YAML property",
    YAML_HEAD_TIP: "<code>Inline to note</code> on the Transform tab turns a line into a note. It can copy any Field into a property of that note, the same properties you see at the top of a note in Obsidian. Here you pick the property for this Field. Leave it empty and the Field is not copied",
    YAML_NAME: "Property",
    YAML_DESC: "If you use <code>Inline to note</code>, to which YAML property this Field should go",
    YAML_TIP: "The note property this Field goes into. Start typing and the box offers the names your vault already uses. A new name works too: it appears the first time a note is written with it\n- <b>Empty</b> — the Field is not copied into the note\n- <b>type</b> — <code>#todo</code> on the line gives the note <code>type: todo</code> with <b>Clean</b>\nTwo Fields may share one property. Then <code>Property type</code> below decides between a list and one Value",
    YAML_HINT: "select a property",
    YAML_FOR: "YAML property for {0}",
    YAML_CLEAR: "Clear the property of {0}",
    YAML_KIND_NAME: "Property type",
    YAML_KIND_DESC: "Whether the property holds one Value or a list",
    YAML_KIND_TIP: "- <b>Auto</b> — a list when more than one Field writes to this property, one Value otherwise\n- <b>Single Value</b> — one Value: <code>type: todo</code>\n- <b>List</b> — always a list, even with one Value: <code>type: [todo]</code>\nA property that Obsidian already knows as a list always gets a list",
    YAML_NOT_WRITTEN: "not written",
    YAML_KIND_AUTO: "Auto",
    YAML_KIND_ONE: "Single Value",
    YAML_KIND_LIST: "List",
    YAML_FORM_NAME: "How to show Value in YAML",
    YAML_FORM_DESC: "How the Value is written into the property",
    YAML_FORM_TIP: "- <b>Raw</b> — copies the Value as it is in the line: <code>#todo</code>, <code>[[Anna]]</code>, <code>📅2026-10-10</code>\n- <b>Clean</b> — copies it bare: <code>todo</code>, <code>Anna</code>, <code>2026-10-10</code>. Best if you search or sort by the property\nThe rule is for the whole Field and all its Values",
    YAML_FORM_RAW: "Raw",
    YAML_FORM_CLEAN: "Clean",
    YAML_TAGS_WARNING: "A tags property does not take links: Obsidian will flag the value in the note",
    YAML_PREVIEW_NAME: "Preview",
    YAML_PREVIEW_DESC: "How this Value will look like in YAML",
    YAML_PREVIEW_TIP: "What <b>this</b> Field writes into the note, such as <code>type: todo</code>. It follows the three choices above as you change them. When two Fields share one property, the note gets both in one list, but each Field shows only its own part here",
    /* Окна редактора. `Name`, `Type`, `Cancel` в каталоге с 2026-09-08 (A46). */
    NEW_FIELD_TITLE: "Add a Field",
    NEW_FIELD_NAME: "Name",
    NEW_FIELD_TYPE: "Type",
    CANCEL: "Cancel",
    NEW_FIELD_NAME_LABEL: "What this Field is called here and in its commands",
    /* `Field name`, а не пример: пример читался как уже набранное. */
    NEW_FIELD_NAME_HINT: "Field name",
    NEW_FIELD_NAME_ARIA: "Name of the new Field",
    /* «?» у полей окна `Add a Field` (2026-09-23). */
    NEW_FIELD_NAME_TIP: "The name shows in the Fields list, in tagWheel and in the command names, such as <code>Type next</code>. You can rename the Field later from its heading",
    NEW_FIELD_TYPE_TAG: "Tag",
    NEW_FIELD_TYPE_LINK: "Link",
    NEW_FIELD_TYPE_ELEMENT: "Element",
    NEW_FIELD_MARKER: "Emoji",
    NEW_FIELD_MARKER_LABEL: "What stands in front of the Value in the line, such as <code>📅</code> or <code>⏰</code>",
    /* Заглушка нейтральна: `📅` читался как уже выбранный знак. */
    NEW_FIELD_MARKER_HINT: "Pick or type",
    NEW_FIELD_MARKER_ARIA: "Emoji of the new Field",
    NEW_FIELD_MARKER_TIP: "An Element writes this emoji with its Value right after it, such as <code>📅2026-10-04</code>. The emoji is how tagWheel tells the Value from your text, so the Field needs one from the start",
    NEW_FIELD_ADD: "Add Field",
    /* Окно `Add a Field` с главным сразу и предпросмотром (2026-09-27). */
    NF_TYPE_TAG_DESC: "Your own #tags, each in its own colors",
    NF_TYPE_LINK_DESC: "A link to one of your notes",
    NF_TYPE_ELEMENT_DESC: "An emoji with a date, a time, a count or a random id",
    NEW_FIELD_TYPE_COMMAND: "Command",
    NF_TYPE_COMMAND_DESC: "Edits of the line, such as a callout or a cleanup, one hotkey each",
    NF_CATEGORIES_HEAD: "Categories",
    NF_PREVIEW_NO_CATEGORIES: "No categories yet",
    NF_PREVIEW_NOTHING: "nothing is written into the line",
    NF_NEED_NAME: "Name the Field",
    NF_NEED_EMOJI: "Pick the emoji the Element writes",
    NF_BLOCK: "Block",
    NF_BLOCK_DESC: "Where in the line the Field writes",
    NF_BLOCK_TIP: "Where the Field writes its Value in the line\n- <b>Left</b> — before your text: <code>- #high :: call Anna</code>\n- <b>Right</b> — after your text: <code>- call Anna :: 📅2026-10-10</code>\nA custom block writes where the cursor is. You can drag the Field to another Block later",
    NF_BLOCK_LEFT: "Left",
    NF_BLOCK_RIGHT: "Right",
    NF_VALUES_HEAD: "Values",
    NF_VALUE_HEAD: "Value",
    NF_VALUES_DESC_TAG: "The tags this Field cycles through. Drag one by its handle to change the order",
    NF_VALUES_DESC_LINK: "The notes this Field cycles through. Drag one by its handle to change the order",
    NF_VALUES_TIP: "The order here is the order <code>next</code> and <code>previous</code> walk and the order tagWheel shows. With <code>#todo</code>, <code>#idea</code>, <code>#done</code>, <code>next</code> goes <code>#todo</code> → <code>#idea</code> → <code>#done</code> → no tag. The preview below follows as you drag, and you can change the order later in the Values table of the Field",
    NF_VALUE_DRAG: "Drag {0} to another place",
    NF_VALUES_EMPTY_TAG: "No Values yet — type one below and press Enter",
    NF_VALUES_EMPTY_LINK: "No notes yet — click the box below to pick one, or type a name",
    NF_VALUES_EMPTY_LIST: "No Values yet — type one with its emoji below, such as 🙂‍↕️yes, and press Enter",
    NF_VALUES_DESC_LIST: "The Values this Field cycles through, each with its own emoji. Drag one by its handle to change the order",
    NEW_VALUE_LIST_HINT: "🙂‍↕️yes / 💡",
    NF_VALUE_ARIA: "New Value",
    NF_VALUE_COLOR: "Fill color of {0}",
    NF_VALUE_TEXT_COLOR: "Text color of {0}",
    NF_VALUE_REMOVE: "Remove {0}",
    NF_NOTE_NONE: "no note yet",
    NF_WRITES: "Writes",
    NF_WRITES_DESC: "What the Element writes into the line",
    NF_WRITES_TIP: "What the Element puts into the line on each <code>next</code>\n- <b>Date and time</b> — a date, a time or both: <code>📅2026-10-04</code> → <code>📅2026-10-05</code>\n- <b>Counter</b> — a number that goes up one step: <code>🔢1</code> → <code>🔢2</code>\n- <b>Random</b> — new random characters every time, good for an id: <code>🆔4821</code> → <code>🆔0937</code>\n- <b>List</b> — your own Values in turn, each with its emoji: <code>🙂‍↕️yes</code> → <code>🙂‍↔️no</code>",
    NF_WRITES_DATETIME: "Date and time",
    NF_WRITES_COUNTER: "Counter",
    NF_WRITES_RANDOM: "Random",
    NF_WRITES_LIST: "List",
    NF_SHOWS: "Shows",
    NF_SHOWS_DESC: "The date, the time or both",
    NF_SHOWS_TIP: "Each choice fills in <code>Value format</code> below. You can edit it by hand later\n- <b>Date</b> — <code>2026-10-04</code>, moves a day per press, starting from today\n- <b>Time</b> — <code>14:30</code>, writes the time you press\n- <b>Date and time</b> — <code>2026-10-04 14:30</code>, writes the moment you press",
    NF_SHOWS_DATE: "Date",
    NF_SHOWS_TIME: "Time",
    NF_SHOWS_BOTH: "Date and time",
    NF_PRESS: "On next",
    NF_PRESS_DESC: "What the <code>next</code> command does to the Value",
    NF_PRESS_TIP: "- <b>Steps</b> — the first press writes today, each next press moves it by the step below: <code>📅2026-10-04</code> → <code>📅2026-10-05</code>. <code>previous</code> moves it back\n- <b>The moment</b> — writes the time of the press over whatever was there: <code>⏰2026-10-01 09:00</code> → <code>⏰2026-10-04 14:30</code>. <code>previous</code> removes it",
    NF_PRESS_STEP: "Steps",
    NF_PRESS_NOW: "The moment",
    NF_RANDOM: "Made of",
    NF_RANDOM_DESC: "Numbers or letters",
    NF_RANDOM_TIP: "<code>Value format</code> below sets how many characters you get: <code>0000</code> gives four\n- <b>Random numbers</b> — digits only: <code>4821</code>\n- <b>Random characters</b> — letters, digits and a few signs such as <code>-</code> and <code>_</code>: <code>aZ7k</code>",
    NF_FORMAT_DESC: "How the Value is spelled, such as <code>YYYY-MM-DD</code>",
    NF_FORMAT_COUNTER_DESC: "The first number; its digits set the width, such as <code>001</code>",
    NF_FORMAT_RANDOM_DESC: "As many characters as digits here, such as <code>0000</code>",
    /* Одна подпись на любой формат: единица — самая мелкая в <code>Value format</code>. */
    NF_STEP_DESC_UNIT: "How much one press adds to the smallest unit of <code>Value format</code>, such as a minute or a day",
    NF_STEP_DESC_COUNT: "How much one press adds",
    NF_PREVIEW: "Preview",
    NF_PREVIEW_LINE: "Line",
    NF_PREVIEW_NO_VALUES: "No Values yet",
    NF_PREVIEW_VALUE: "Value",
    NF_SAMPLE_TEXT: "your text",
    /* Link как MOC: окно и правая колонка. */
    MOC_NAME: "Use as MOC",
    MOC_DESC: "Let <code>Link the notes you mention</code> file new notes into the notes of these Values",
    MOC_TIP: "Works when <code>Link the notes you mention</code> is on. <code>Inline to note</code> turns a line into a new note and adds a link to it into the notes of the link Values on the line, if those notes exist\n- <b>Yes</b> — <code>- call Anna [[Project X]]</code> → note <b>Project X</b> gets a line like <code>- [[call Anna]]</code>\n- <b>No</b> — note <b>Project X</b> stays as it is. Good for links that are not lists, such as people",
    MOC_YES: "Yes",
    MOC_NO: "No",
    MOC_OF: "Use as MOC for {0}",
    NEW_FIELD_FAILED: "The Field was not added",
    /* Переименование Value-ссылки называет цену (2026-09-27). */
    LINK_RENAME_TITLE: "Rename the note too?",
    LINK_RENAME_NOTE_BODY: "The Value <code>{0}</code> has its own note, <code>{1}</code>. Rename the note to <code>{2}</code> as well, and Obsidian rewrites every link to it in your notes: {3} in {4}",
    LINK_RENAME_NOTE_ONLY: "<b>Only the Value</b> leaves those links on the old name: they keep opening <code>{1}</code>, and the next command writes the new name next to them",
    LINK_RENAME_ASKS_FIRST: "<code>Automatically update internal links</code> is off in Obsidian's <b>Files and links</b>, so Obsidian asks you before it rewrites them",
    LINK_RENAME_CLASH_TITLE: "The note keeps its name",
    LINK_RENAME_CLASH_BODY: "The Value <code>{0}</code> has its own note, <code>{1}</code>, but <code>{2}</code> is taken by another note, so the note stays as it is. Renaming the Value leaves {3} in {4} on the old name",
    LINK_RENAME_NONE_TITLE: "Links keep the old name",
    LINK_RENAME_NONE_BODY: "There is no note <code>{1}</code>, so there is nothing for Obsidian to rename: {3} in {4} keep the old name. Only the Value changes",
    LINK_RENAME_BOTH: "Rename note and links",
    LINK_RENAME_VALUE: "Only the Value",
    LINK_RENAME_VALUE_CTA: "Rename the Value",
    LINK_RENAME_LINKS_ONE: "{0} link",
    LINK_RENAME_LINKS_MANY: "{0} links",
    LINK_RENAME_NOTES_ONE: "{0} note",
    LINK_RENAME_NOTES_MANY: "{0} notes",
    LINK_RENAME_FAILED: "The note was not renamed: {0}",
    LINK_RENAME_NAME_ARIA: "New name for {0}",
    DELETE_TITLE: "Delete Field",
    DELETE_BODY: "Deleting {0} removes its Values, their colors and its note property",
    DELETE_CONFIRM: "Delete",
    DELETE_BLOCK_TITLE: "Delete block",
    /* Число в скобках: «its 1 Fields» не годилось по-английски (BUGHUNT S11). */
    DELETE_BLOCK_BODY: "Delete {0} and its Fields ({1}): {2}? Their Values, colors and note properties go with them",
    RENAME_BLOCK_TITLE: "Rename block",
    RENAME_BLOCK_HINT: "The name of its tagWheel command follows it; a hotkey stays where it was",
    RENAME_BLOCK_ARIA: "New name for the block {0}",
    RENAME_TITLE: "Rename Field",
    RENAME_LABEL: "New name",
    RENAME_HINT: "Letters, digits, spaces, hyphens and underscores",
    RENAME_ARIA: "New name for the Field {0}",
    RENAME_WARNING: "Two things will not follow the new name:",
    RENAME_WARNING_NOTES: "lines you have already written keep the old tag — the plugin does not edit your notes",
    RENAME_WARNING_HOTKEY: "a hotkey given to this Field’s commands comes loose: Obsidian keeps hotkeys by command id, and the id is built from the name",
    RENAME_CONFIRM: "Rename",
    /* Проверки имён и значений: их человек читает на месте ошибки. */
    ERR_NAME_CHARS: "A Field name can only use letters, digits, spaces, hyphens and underscores",
    ERR_NAME_SUB: "Names ending in _sub are reserved for child Fields",
    ERR_NAME_TAKEN: "A Field with this name already exists",
    /* Custom block и повтор Value (10.13.260, `В-209`). */
    ERR_BLOCK_NAME_TAKEN: "A block with this name already exists",
    ERR_VALUE_TAKEN: "Another Field already has a Value written this way",
    /* Написание Value (BUGHUNT 2026-09-30, Q3). */
    ERR_VALUE_SPACE: "A tag Value is one word: join the words with - or _",
    ERR_VALUE_TWICE: "This Field already has this Value",
    ERR_LIST_VALUE_SPACE: "A list Value is one word: write it without spaces, like ✅done",
    ERR_CHILD_TAKEN: "The child Field for this name already exists",
    ERR_NO_FIELD: "No Field named {0}",
    ERR_YAML_FORM: "A Value is written either raw or clean, nothing else",
    ERR_NOT_SAVED: "This Field is not saved yet",
    ERR_SELF_PREREQ: "A Field cannot wait for itself",
    ERR_LINK_NO_FIELD: "Cannot tell which Field this link Value belongs to",
    ERR_LINK_NO_TARGET: "Cannot tell which Field this link Value would go to",
    ERR_LINK_UNNAMED_FIELD: "The Field for this link has no name",
    ERR_LINK_NEEDS_NAME: "A link needs a name",
    ERR_PREFIX_TOKEN: "A Prefix checkbox looks like [ ] or [x]",
  },

  /* ---- Smart Rules ----------------------------------------------------- */
  "smart-rules-list": {
    KIND_TAG: "Tag",
    KIND_ELEMENT: "Element",
    KIND_LINK: "Link",
    KIND_FIELD: "Field",
    RULE_NAME_HINT: "Name this rule (optional)",
    RULE_FALLBACK_NAME: "Rule {0}",
    RULES_EMPTY: "no rules yet — the default template is used for every line",
    ADD_RULE: "Add rule",
    /* Кнопка отказа в окне выбора условия (A46). */
    CANCEL: "Cancel",
    MATCH_ANY: "any",
    MATCH_OR: "or",
    MATCH_AND: "and",
    WHEN_THE_LINE_HAS: "when the line has",
    USE_TEMPLATE: "Use template",
    MOVE_TO_FOLDER: "Move to folder",
    TEMPLATE_NONE: "None",
    FOLDER_DEFAULT: "Default",
    FOLDER_NEAR_NOTE: "Next to note",
    FOLDER_OTHER: "Other folder…",
    FOLDER_HINT: "type or pick a folder",
    ANY_VALUE_SUFFIX: "{0} — any Value",
    ANY_VALUE_TAKEN: "{0} — any Value is already in this rule",
    USE_ANY_VALUE_OF: "Use any Value of {0}",
    NO_FIELDS_YET: "no Fields yet — set one up on the Tags & PKM tab",
    NO_KIND_FIELDS_YET: "no {0} Fields yet — set one up on the Tags & PKM tab",
    VALUES_EMPTY: "no Values yet",
    USE_VALUE: "Use {0}",
    CONDITION_TIP: "Pick one of the Values your Fields already offer. Within one kind, any one Value is enough. Every kind you filled in must be on the line. A rule with <code>#todo</code> or <code>#idea</code>, and <code>[[Project X]]</code>:\n- <code>- call Anna #todo [[Project X]]</code> — fits\n- <code>- call Anna #todo</code> — does not fit, there is no link",
    ADD_CONDITION: "Add {0}",
    RULE_NAME_ARIA: "Name of {0}",
    RULE_TEMPLATE_ARIA: "Template for {0}",
    RULE_FOLDER_ARIA: "{0} path for {1}",
    RULE_DRAG: "{0} to reorder it",
    RULE_STOP: "Stop using {0}",
    RULE_REMOVE: "Remove {0}",
    CONDITION_REMOVE: "Remove {0}",
    /* ---- `Advanced settings` у правила (З-5) ------------------------------
       Слова повторяют `Note content` нарочно: у правила свои ключи, переводятся врозь. */
    /* ---- свёрнутая карточка правила (З-6) ---------------------------- */
    RULE_COLLAPSE: "Collapse {0}",
    RULE_EXPAND: "Expand {0}",
    /* Без условий движок правило выключает (`validateSmartRules`); «any line» было неправдой (BUGHUNT C16). */
    SUMMARY_ANY_LINE: "nothing yet, so the rule is not used",
    /* Жалобы на правило: вердикт движка, слова панели (C16). */
    CONFLICT_WITH: "Conflicts with {0}: a line can match both, so neither is used",
    CONDITION_TITLE_TAG: "Add a tag",
    CONDITION_TITLE_ELEMENT: "Add an element",
    CONDITION_TITLE_LINK: "Add a link",
    CONDITION_TITLE_FIELD: "Add a Field",
    CONFLICT_EMPTY: "No conditions yet: add a Tag, Element, Link or Field, or the rule is not used",
    /* Двоеточие внутри строки нарочно: его место в языке решает переводчик, не склейка. */
    SUMMARY_WHEN: "Use when:",
    SUMMARY_TEMPLATE: "Template:",
    SUMMARY_FOLDER: "Folder:",
    RULE_ADVANCED: "Advanced settings",
    RULE_ADVANCED_ARIA: "Advanced settings for {0}",
    RULE_ADVANCED_DEFAULT: "Default",
    RULE_ADVANCED_CUSTOM: "Custom",
    PL_ROW_ARIA: "{0} for {1}",
    PL_POSITION: "Where to put the text",
    PL_POSITION_BEGINNING: "Beginning",
    PL_POSITION_END: "End",
    PL_POSITION_HEADER: "Under heading",
    PL_TARGET_HEADER: "Name of the heading",
    PL_TARGET_HEADER_HINT: "# Heading name",
    PL_FALLBACK: "If heading not found",
    PL_HEADER_MODE: "Line above the text",
    PL_HEADER_MODE_CUSTOM: "Fixed text",
    PL_HEADER_MODE_DATETIME: "Date and time",
    PL_HEADER_MODE_NONE: "None",
    PL_HEADER_LEVEL: "Line above is a heading",
    PL_HEADER_LEVEL_PLAIN: "Plain text",
    PL_HEADER_TEXT: "Text of the line above",
    PL_DATETIME: "Date format",
  },

  /* ---- Binder ---------------------------------------------------------- */
  "binder-table": {
    COL_INSERTS: "Inserts",
    COL_COMMAND_NAME: "Command name",
    COL_DESCRIPTION: "Description",
    COL_HOTKEY: "Hotkey",
    /* Подсказки колонок раскрываются в слот под шапкой во всю ширину: ячейка шапки ~60 точек. */
    COL_INSERTS_TIP: "The text the command puts in at the cursor, such as <code>→</code>: <code>call Anna|</code> → <code>call Anna→</code>. You cannot change it later. The command is built from this text, so your hotkey would start typing something else. A <code>Command</code> row shows its category here and its preset below, and you can change the preset any time",
    COL_COMMAND_NAME_TIP: "The name you see in the command palette and on Obsidian’s <code>Hotkeys</code> screen. The plugin adds its own name in front, so do not type it here: <code>Arrow right</code> → <code>inlineOverhaul: Binder: Arrow right</code>",
    COL_DESCRIPTION_TIP: "A note to yourself about what the row is for, such as <code>for meeting notes</code>. It is the only column you can change later, and nothing outside this table reads it",
    COL_HOTKEY_TIP: "The keys set for this command now, or <code>not set</code>. Press the cell and Obsidian’s <code>Hotkeys</code> screen opens at this command. The plugin never sets keys by itself",
    HOTKEY_CHANGE: "Change the hotkey for {0}",
    HOTKEY_ASSIGN: "Assign a hotkey to {0}",
    NEW_INSERTS_HINT: "Type anything or choose below",
    NEW_NAME_HINT: "Arrow",
    NEW_CANCEL: "Cancel",
    ADD_COMMAND: "Add command",
    HOTKEY_NOT_SET: "not set",
    BUILT_IN: "Built in",
    COMMAND_PREFIX: "Binder: {0}",
    NEW_TITLE: "Add a Binder command",
    /* Строка типа `Command` (постановка command-field.md, 4.6). */
    NEW_TYPE_LABEL: "Type",
    NEW_TYPE_DESC: "Insert your text, or run a Command Field category with one preset of its own",
    TYPE_TEXT: "Text",
    TYPE_COMMAND: "Command",
    NEW_CATEGORY_LABEL: "Category",
    NEW_CATEGORY_DESC: "What the command does to the line; set its preset below",
    NEW_CATEGORY_ARIA: "Category of the new command",
    NEW_NOTE_COMMAND: "One press applies the preset, the next press on its result takes it off; Cleanup only applies",
    ROW_PRESET_ARIA: "Preset of {0}",
    ROW_DESC_PLACEHOLDER: "Add a note",
    ROW_PRESET_SHOW: "Show the settings of {0}",
    ROW_PRESET_HIDE: "Hide the settings of {0}",
    NEW_NOTE: "The command is made from the row, so the text it inserts cannot be changed afterwards",
    NEW_INSERTS_LABEL: "Inserts",
    NEW_INSERTS_DESC: "The text this command drops in at the cursor",
    NEW_NAME_LABEL: "Command name",
    NEW_NAME_DESC: "What to call it in Obsidian’s list of hotkeys",
    /* Имя по умолчанию, когда знака нет в выбиралке (п. 9.4); у знака из выбиралки имя своё (`Arrow right` у `→`). */
    NEW_NAME_AUTO: "Insert {0}",
    /* Выбиралка знака под полем `Inserts` (`В-182`). */
    PICK_EMOJI: "Emoji",
    PICK_SYMBOLS: "Symbol",
    PICK_FACES: "Kaomoji",
    PICK_SEARCH: "Search by name",
    PICK_EMPTY: "Nothing by that name — type your own text into the field",
    NEW_DESC_LABEL: "Description",
    NEW_DESC_DESC: "A note to yourself about what the row is for",
    NEW_FIELD_ARIA: "{0} of the new command",
    NEW_ADD: "Add",
    ROW_ARIA: "this row",
    ROW_DRAG: "{0} to reorder it",
    ROW_DESC_ARIA: "Description for {0}",
    /* `ROW_HOTKEY_ARIA` снята (A46, У-71): подпись приходит целой — `HOTKEY_CHANGE`/`HOTKEY_ASSIGN`. */
    ROW_REMOVE: "Remove {0}",
    ERR_TEXT_TAKEN: "A row with this text to insert already exists",
    ERR_NAME_TAKEN: "A row with this command name already exists",
  },

  /* ---- свои теги ------------------------------------------------------- */
  "user-tag-list": {
    HEAD_TAG: "Tag",
    HEAD_SHOW: "Show",
    HEAD_FILL: "Fill",
    HEAD_TEXT: "Text",
    HEAD_SIDE: "Side",
    HEAD_PREVIEW: "Preview",
    TEXT_COLOR: "Text color",
    TAG_TIP: "The tag as you write it in a line. With or without <code>#</code> it is the same tag: <code>#urgent</code> and <code>urgent</code> both color <code>- call Anna #urgent</code>",
    SHOWN_TIP: "How the tag looks in the line\n- <b>default</b> — the tag text on its colors, so <code>#urgent</code> stays readable\n- <b>empty</b> — only the color, the text of the tag is hidden",
    FILL_TIP: "The color of the bubble behind the tag",
    TEXT_TIP: "The color of the writing on the bubble",
    SIDE_TIP: "The color of the bubble outline. Pure white means no outline, and in <code>Fill</code> it means no fill",
    /* Чип предпросмотра своего тега — свой, как в Values; контраст показывает он (2026-09-08). */
    PREVIEW_TIP: "The tag drawn the way the editor will draw it, with both colors and the <code>Show</code> choice applied. A warning sign appears when the two colors are too close to read, with the contrast it measured",
    ADD_TAG: "Add tag",
    NEW_TAG_HINT: "#tag",
    NEW_TAG_ARIA: "New tag to color",
    EMPTY: "no tags of your own yet — add one below",
    SHOWN_DEFAULT: "default",
    SHOWN_EMPTY: "empty",
    ROW_ARIA: "Tag {0}",
    SHOWN_FOR: "Show, for {0}",
    FILL_COLOR: "Fill color",
    SIDE_COLOR: "Side color",
    RESET_COLORS: "Reset the colors of {0} back to the colors of the theme",
    REMOVE: "Remove {0}",
  },

  /* ---- списки порядка: Fields и Prefix ---------------------------------- */
  "field-order-list": {
    NO_PREFIX: "no Prefix (plain text)",
    ADD_PREFIX: "Add Prefix",
    DRAG_HINT: "Drag a row, or use the arrows, to change the order",
    FIELDS_TIP: "The Field nearest the top wins a conflict. Drag a row, or use the arrows",
    PREFIX_TIP: "The Prefix nearest the top wins, whichever Field produced it. Drag a row, or use the arrows",
    FIELDS_EMPTY: "no Fields yet — set them up under Fields above",
    PREFIX_EMPTY: "no Prefixes listed yet",
    ROW_DRAG: "{0} to reorder it",
    MOVE_UP: "Move {0} up",
    MOVE_DOWN: "Move {0} down",
    REMOVE: "Remove {0}",
    PREFIX_ROW: "Prefix {0}",
  },

  /* ---- таблицы того, что делают клавиши --------------------------------- */
  "left-right-order": {
    MOVE_LEFT: "Move left",
    MOVE_RIGHT: "Move right",
    /* Тело подсказки — ПОД парой колонок: колонка от 268 точек, прозе тесно. */
    MOVE_LEFT_TIP: "What the key does depends on the line. Read the list from the top: the first line that fits wins. This only describes the command. Each of the three jobs has its own on/off setting further down",
    MOVE_RIGHT_TIP: "Works like <code>Move left</code>, in the other direction, and is read the same way\n- <code>Cycle in both directions</code> on — all three lines work\n- <code>Cycle in both directions</code> off — the last line never applies, so <code>Move right</code> only changes the indent",
    WHEN_SELECTED: "part of a line is selected",
    THEN_MOVE_TEXT: "move that text",
    WHEN_INDENTED: "the line is indented",
    THEN_UNINDENT: "remove one indent level",
    THEN_INDENT: "add one indent level",
    WHEN_NO_INDENT: "no indent",
    THEN_CYCLE_BACK: "cycle the Prefix backwards",
    THEN_CYCLE_ON: "cycle the Prefix forwards",
  },

  /* ---- что остаётся на строке ------------------------------------------- */
  "source-fields": {
    NO_FIELDS: "no Fields yet — set them up under Tags & PKM",
    NONE_KEPT: "nothing is kept: every Value leaves the line",
    KEEP_ONE: "Keep the Values of {0} on the line",
    KEEP_ALL: "Keep all",
    KEEP_ALL_DESC: "Keep the Values of every Field on the line",
    KEEP_NONE: "Keep none",
    KEEP_NONE_DESC: "Let every Value leave the line",
  },

  /* ---- ступени расширенного `Ctrl+A`: режим `Custom` (З-3) ------------- */
  "select-all-custom": {
    /* Имена ступеней — со строчной (Р9). */
    STEP_WORD: "word",
    STEP_WORD_ABOUT: "the word nearest the cursor",
    STEP_LINE: "line",
    STEP_LINE_ABOUT: "the line you are on",
    STEP_TREE: "tree",
    STEP_TREE_ABOUT: "the line and everything indented under it",
    STEP_HEADING: "heading",
    STEP_HEADING_ABOUT: "everything under the nearest heading",
    STEP_NOTE: "note",
    STEP_NOTE_ABOUT: "the whole note",
    /* Пустой список объясняет себя, а не молчит (ПЗ2). */
    NOTHING_TICKED: "nothing ticked: Ctrl/Cmd + A stays Obsidian’s own",
    STOP_AT: "Stop at the {0} while cycling",
  },

  /* ---- справочник команд ------------------------------------------------ */
  "command-list": {
    COL_COMMAND: "Command",
    COL_DOES: "Description",
    COL_HOTKEY: "Hotkey",
    /* Шапка — в слот под ней; подпись части занимает строку, знак в ней самой (2026-09-08). */
    COL_COMMAND_TIP: "The command name without the area shown above it. In the command palette and on the <code>Hotkeys</code> screen the area comes first: <code>Move up</code> → <code>Navigation: Move up</code>. Names are never translated, so they always match Obsidian’s own list",
    COL_DOES_TIP: "What the command does, in one line. A language file can change only this column, the names beside it stay as they are",
    COL_HOTKEY_TIP: "The keys set for this command now, or <code>not set</code>. Press the cell and Obsidian’s <code>Hotkeys</code> screen opens at this command. The plugin never sets keys by itself",
    PART_STANDARD_TIP: "Commands that are always there, whatever you have set up: they come with the plugin, and their names do not change",
    PART_USER_TIP: "Commands made from your Fields, in the order of your Fields, not the alphabet. Each Field gets a pair: <code>Due</code> → <code>Due next</code> and <code>Due previous</code>. A child Field gets its own pair under the same heading. Add, rename or remove a Field and this list follows",
    HOTKEY_CHANGE: "Change the hotkey for {0}",
    HOTKEY_ASSIGN: "Assign a hotkey to {0}",
    HOTKEY_NOT_SET: "not set",
    HOTKEY_OPEN: "Open Obsidian’s Hotkeys settings at this command",
    /* Кнопка в заголовке любого уровня (2026-09-20, п. 12.3). Подпись говорит, чем
       отобрано: поиск Obsidian набор команд не выражает, строку видно в поле поиска. */
    PART_USER_DESC: "<code>next</code> moves a Field on to its next Value or preset, <code>previous</code> moves it back",
    TO_HOTKEYS: "to hotkeys",
    TO_HOTKEYS_LABEL: "Open Obsidian’s Hotkeys screen for {0}, filtered by {1}",
  },
} as const;

/** Кто владеет строкой: id своего блока в схеме. */
export type BlockOwner = keyof typeof BLOCK_TEXTS;

/** Ключ каталога для текста блока. Одна функция на оба конца (У-82). */
export function blockKey(owner: string, name: string): string {
  return "block." + owner + "." + name.toLowerCase().replace(/_/g, "-");
}

/** Английская ветка каталога для одного блока — в порядке чтения. */
export function blockTextEntries(owner: string): ReadonlyArray<{ key: string; text: string }> {
  const table = (BLOCK_TEXTS as Readonly<Record<string, Readonly<Record<string, string>>>>)[owner];
  if (!table) return [];
  return Object.entries(table).map(([name, text]) => ({ key: blockKey(owner, name), text }));
}

/** То же, когда имя приходит строкой (для `say`). */
export const BLOCK_BY_NAME: Readonly<Record<string, Readonly<Record<string, string>>>> =
  BLOCK_TEXTS as unknown as Readonly<Record<string, Readonly<Record<string, string>>>>;

/** Что блоку нужно от панели, чтобы спросить свой текст. */
interface HasT {
  t?: (key: string, fallback: string) => string;
}

/**
 * Как блок спрашивает свой текст: `const say = sayIn("field-editor", ctx)`,
 * дальше `say("ADD_FIELD")` и `say("SHOW_FIELD", name)`.
 */
export function sayIn(owner: BlockOwner, ctx: HasT): (name: string, ...args: readonly (string | number)[]) => string {
  const table = BLOCK_BY_NAME[owner] || {};
  return (name: string, ...args: readonly (string | number)[]): string => {
    const english = table[name] || "";
    const said = ctx && typeof ctx.t === "function" ? ctx.t(blockKey(owner, name), english) : english;
    return args.length ? said.replace(/\{(\d+)\}/g, (whole, n) => {
      const value = args[Number(n)];
      return value === undefined ? whole : String(value);
    }) : said;
  };
}
