/**
 * ВНИМАНИЕ: файл сгенерирован из docs/prototype/settings_prototype.html.
 * Руками не правится. Правится прототип, затем `npm run gen:schema`.
 *
 * Тексты согласованы заказчиком и совпадают с Приложением B PRD.
 */

import type { SettingsGroup } from "../types.ts";
import { on } from "../types.ts";
import { callout } from "../custom/callouts.ts";

export const ADVANCED_GROUPS: readonly SettingsGroup[] = [
{ id: "advanced-intro",  tab: "advanced",   order: 50, heading: "Before you start",
  items: [
    { kind:"custom", id:"advanced-callout", render: callout("advanced") }
  ],
  visible: on("general.help.showCallouts") },
{
  id: "settings-backup", tab: "advanced", order: 190, heading: "Backup",
  intro: "A backup is a regular note in your vault that holds all your settings. Use it to go back to an earlier setup or to move your setup to another vault",
  tip: "A backup is a note with all your settings, such as <code>Settings 2026-10-04 14-30-05.md</code>\n- <b>Save a backup</b> — adds a new note each time and never overwrites old ones. You delete old backups yourself\n- <b>Restore a backup</b> — replaces <b>everything</b> on every tab, then asks you to restart\nTo move your setup to another computer, sync your vault and restore the backup there",
  items: [
    { kind:"text", id:"backup-folder", clearable:true, path:"advanced.backups.folder", default:"inlineOverhaul/Backups", wide:true,
      name:"Backup folder", desc:"Where in your vault the backups are kept",
      tip:"Pick any folder. It is created when you save your first backup. Backups are regular notes, so they sync with the rest of your vault\n- <b>Backups</b> — <code>Backups/Settings 2026-10-04 14-30-05.md</code>\n- <b>Empty</b> — <code>inlineOverhaul/Backups/Settings 2026-10-04 14-30-05.md</code>" },
    { kind:"toggle", id:"backup-autosave", path:"advanced.backups.autosave", default:false,
      name:"Autosave", desc:"Each time Obsidian starts, keep a copy of your settings if they differ from the last one",
      tip:"Catches settings that arrive from sync, another device or a copied file, so you can always go back\n- <b>On</b> — when Obsidian starts and your settings changed, a copy goes to the <code>autosave</code> subfolder: <code>autosave/Settings 2026-10-04 14-30-05_autosave.md</code>. It holds every tab plus this plugin’s hotkeys and lists <code>What changed</code>\n- <b>Off</b> — no copies\nTo undo one change, use the command <code>Undo last settings change</code>" },
    { kind:"text", id:"backup-autosave-keep", clearable:true, path:"advanced.backups.autosaveKeep", default:"", placeholder:"10",
      name:"Autosaves to keep", desc:"How many autosaves stay; when there are more, the oldest ones are removed",
      visible: on("advanced.backups.autosave"),
      tip:"When there are more autosaves than this, the oldest ones are removed. Backups you save yourself are always kept\n- <b>3</b> — a fourth autosave removes the oldest, so 3 stay\n- <b>Empty</b> — 10 stay" },
    { kind:"toggle", id:"backup-before-restore", path:"advanced.backups.beforeRestore", default:true,
      name:"Save a backup before restoring", desc:"Write what you have now into the folder above before an earlier backup replaces it",
      tip:"- <b>On</b> — each restore first saves what you have now, as <code>Settings 2026-10-04 14-30-05 Autogenerated.md</code>, so you can go back\n- <b>Off</b> — restoring writes straight over your settings, with no way back\nTurn it off only if you restore often and the extra copies pile up" },
    { kind:"buttons", id:"settings-backup-actions",
      name:"Your settings", desc:"Save what you have set up now, or bring back an earlier backup",
      tip:"- <b>Save a backup</b> — adds a new note each time: <code>Settings 2026-10-04 14-30-05.md</code>. Old ones stay until you delete them\n- <b>Restore a backup</b> — replaces <b>everything</b> on every tab, then asks you to restart\nThe toggle above decides whether your current settings are saved first, as a copy ending in <code>Autogenerated</code>",
      buttons:[ {label:"Save a backup", action:"save-backup"},
                {label:"Restore a backup", action:"restore-backup", warning:true} ] },
    { kind:"buttons", id:"settings-reset-actions",
      name:"Start over", desc:"Delete everything you have set up here and go back to the plugin\u2019s own defaults",
      tip:"- <b>Delete all my settings</b> — deletes every tab, Field, Value, rule, Binder row and the hotkeys of this plugin’s commands. Other plugins’ hotkeys stay\nA copy like <code>Settings 2026-10-04 14-30-05 Autogenerated.md</code> is always saved first, whatever the toggle says, so <code>Restore a backup</code> brings everything back",
      buttons:[ {label:"Delete all my settings", action:"reset-settings", warning:true} ] }
  ]
},
{
  id: "diagnostics", tab: "advanced", order: 200, heading: "Diagnostics",
  intro: "Tools for finding out why something goes wrong: setting ids and a log of what the plugin did. Careful: the log is saved in your vault and contains the text of the lines you edit",
  tip: "- <b>Ids</b> — harmless. An id names a setting in a bug report and never changes\n- <b>Log</b> — keep it off unless you are chasing a problem. It records what you type\nTurn the log on, repeat the problem once, turn it off and read the note",
  items: [
    { kind:"toggle", id:"show-setting-ids", path:"advanced.showSettingIds", default:false,
      name:"Show option IDs in tips", desc:"Put the id of each setting and group at the end of its tip",
      tip:"Puts the id and the current state at the end of each tip, such as <code>show-setting-ids = on</code>. Settings without a tip get a tip with just this line\n- <b>On</b> — use the id to point at a setting in a bug report. It stays the same even when a name changes\n- <b>Off</b> — no ids\n<code>Show tips</code> on the General tab must be on too" },
    { kind:"toggle", id:"dev-mode", path:"advanced.devMode.enabled", default:false,
      name:"Developer logging", desc:"Record what the plugin did, to help track down a problem",
      searchTerms:["Enable Dev Mode"],
      tip:"- <b>On</b> — the plugin writes a log note of what it did, and the text of the lines you edit\n- <b>Off</b> — no log. Keep it so day to day\nTo report a problem: turn it on, repeat the problem once, turn it off, check what is in the log and attach it" },
    { kind:"toggle", id:"dev-ai-log", path:"advanced.devMode.aiLog", default:false,
      name:"Machine-readable log", desc:"Also keep a second, denser log meant for tools rather than people",
      tip:"- <b>On</b> — a second, denser log file is kept next to the plain one, meant for tools\n- <b>Off</b> — only the plain log, the one you can read yourself\nOnly worth turning on if someone has asked you for it",
      searchTerms:["Generate log for AI?"], visible: on("advanced.devMode.enabled") },
    { kind:"text", id:"dev-log-path", clearable:true, path:"advanced.devMode.logPath", default:"InlineOverhaul_DevLog", wide:true,
      name:"Log folder", desc:"Where in your vault the logs are put",
      tip:"Logs are regular notes, so they show up in search and in your graph. If that bothers you, put them in a folder you exclude",
      searchTerms:["Log Path"], visible: on("advanced.devMode.enabled") }
  ]
}
];
