/**
 * ВНИМАНИЕ: файл сгенерирован из docs/prototype/settings_prototype.html.
 * Руками не правится. Правится прототип, затем `npm run gen:schema`.
 *
 * Тексты согласованы заказчиком и совпадают с Приложением B PRD.
 */

import type { SettingsGroup } from "../types.ts";
import { on } from "../types.ts";
import { callout } from "../custom/callouts.ts";

export const ADVANCED_GROUPS: readonly SettingsGroup[] = [
{ id: "advanced-intro",  tab: "advanced",   order: 50, heading: "Before you start",
  items: [
    { kind:"custom", id:"advanced-callout", render: callout("advanced") }
  ],
  visible: on("general.help.showCallouts") },
{
  id: "settings-backup", tab: "advanced", order: 190, heading: "Backup",
  intro: "A backup is a regular note in your vault that holds all your settings. Use it to go back to an earlier setup or to move your setup to another vault",
  tip: "Saving adds a new note each time and never overwrites old ones, so the folder fills up and you delete old backups yourself. Restoring replaces <b>everything</b> on every tab, then asks you to restart. To move your setup to another computer, sync your vault and restore the backup there",
  items: [
    { kind:"text", id:"backup-folder", clearable:true, path:"advanced.backups.folder", default:"inlineOverhaul/Backups", wide:true,
      name:"Backup folder", desc:"Where in your vault the backups are kept",
      tip:"Pick any folder. It is created when you save your first backup. Backups are regular notes, so they sync with the rest of your vault" },
    { kind:"toggle", id:"backup-autosave", path:"advanced.backups.autosave", default:false,
      name:"Autosave", desc:"Each time Obsidian starts, keep a copy of your settings if they differ from the last one",
      tip:"This catches settings that arrive from sync, another device or a copied file, so you can always go back. Each copy holds every tab plus this plugin’s hotkeys, and lists <code>What changed</code>. Copies go to the <code>autosave</code> subfolder. To undo one change, use the command <code>Undo last settings change</code>" },
    { kind:"text", id:"backup-autosave-keep", clearable:true, path:"advanced.backups.autosaveKeep", default:"", placeholder:"10",
      name:"Autosaves to keep", desc:"How many autosaves stay; when there are more, the oldest ones are removed",
      visible: on("advanced.backups.autosave"),
      tip:"Leave it empty for 10. Only autosaves are removed. Backups you save yourself are always kept" },
    { kind:"toggle", id:"backup-before-restore", path:"advanced.backups.beforeRestore", default:true,
      name:"Save a backup before restoring", desc:"Write what you have now into the folder above before an earlier backup replaces it",
      tip:"When on, each restore first saves a copy ending in <code>Autogenerated</code>, so you can go back. When off, restoring writes straight over your settings. Turn it off only if you restore often and the extra copies pile up" },
    { kind:"buttons", id:"settings-backup-actions",
      name:"Your settings", desc:"Save what you have set up now, or bring back an earlier backup",
      tip:"Saving adds a new note each time. Old ones stay until you delete them. Restoring replaces <b>everything</b> on every tab, then asks you to restart. The toggle above decides whether your current settings are saved first, as a copy ending in <code>Autogenerated</code>",
      buttons:[ {label:"Save a backup", action:"save-backup"},
                {label:"Restore a backup", action:"restore-backup", warning:true} ] },
    { kind:"buttons", id:"settings-reset-actions",
      name:"Start over", desc:"Delete everything you have set up here and go back to the plugin\u2019s own defaults",
      tip:"This deletes every tab, Field, Value, rule, Binder row and the hotkeys of this plugin’s commands. Other plugins’ hotkeys stay. A copy ending in <code>Autogenerated</code> is always saved first, whatever the toggle says, so the restore button next to it brings everything back",
      buttons:[ {label:"Delete all my settings", action:"reset-settings", warning:true} ] }
  ]
},
{
  id: "diagnostics", tab: "advanced", order: 200, heading: "Diagnostics",
  intro: "Tools for finding out why something goes wrong: setting ids and a log of what the plugin did. Careful: the log is saved in your vault and contains the text of the lines you edit",
  tip: "Showing ids is harmless. Use an id to name a setting in a bug report, because ids never change. Keep the log off unless you are chasing a problem: it grows with every keypress and records what you type. Turn it on, repeat the problem once, turn it off and read the note",
  items: [
    { kind:"toggle", id:"show-setting-ids", path:"advanced.showSettingIds", default:false,
      name:"Show option IDs in tips", desc:"Put the id of each setting and group at the end of its tip",
      tip:"<code>Show tips</code> on the General tab must be on too. Settings without a tip get one that shows only the id. Use the id to point at a setting in a bug report or a question. It stays the same even when a name changes" },
    { kind:"toggle", id:"dev-mode", path:"advanced.devMode.enabled", default:false,
      name:"Developer logging", desc:"Record what the plugin did, to help track down a problem",
      searchTerms:["Enable Dev Mode"],
      tip:"Leave this off day to day. Turn it on, reproduce the problem once, then turn it off and attach the log to a bug report after checking what is in it" },
    { kind:"toggle", id:"dev-ai-log", path:"advanced.devMode.aiLog", default:false,
      name:"Machine-readable log", desc:"Also keep a second, denser log meant for tools rather than people",
      tip:"Only worth turning on if someone has asked you for it. The plain log is the one you can read yourself",
      searchTerms:["Generate log for AI?"], visible: on("advanced.devMode.enabled") },
    { kind:"text", id:"dev-log-path", clearable:true, path:"advanced.devMode.logPath", default:"InlineOverhaul_DevLog", wide:true,
      name:"Log folder", desc:"Where in your vault the logs are put",
      tip:"Logs are regular notes, so they show up in search and in your graph. If that bothers you, put them in a folder you exclude",
      searchTerms:["Log Path"], visible: on("advanced.devMode.enabled") }
  ]
}
];
