/**
 * ВНИМАНИЕ: файл сгенерирован из docs/prototype/settings_prototype.html.
 * Руками не правится. Правится прототип, затем `npm run gen:schema`.
 *
 * Тексты согласованы заказчиком и совпадают с Приложением B PRD.
 */

import type { SettingsGroup } from "../types.ts";
import { on } from "../types.ts";
import { callout } from "../custom/callouts.ts";

export const ADVANCED_GROUPS: readonly SettingsGroup[] = [
{ id: "advanced-intro",  tab: "advanced",   order: 50, heading: "Before you start",
  items: [
    { kind:"custom", id:"advanced-callout", render: callout("advanced") }
  ],
  visible: on("general.help.showCallouts") },
{
  id: "setting-ids", tab: "advanced", order: 150, heading: "Setting ids",
  intro: "Every setting and every group here has a short id. Turn this on and you can name one instead of describing where it sits on screen",
  tip: "Ids are what the plugin\u2019s own notes, reports and issues call settings by. They never change when a name or a description is reworded, so they are the safe way to point at a setting \u2014 in a bug report, in a question, or when someone walks you through a fix",
  items: [
    { kind:"toggle", id:"show-setting-ids", path:"advanced.showSettingIds", default:false,
      name:"Show setting ids in tips", desc:"Put the id of each setting and group at the end of its tip",
      tip:"The id goes into the tip, so <code>Show tips</code> on the General tab has to be on as well. Settings without a tip of their own get one with just the id in it" }
  ]
},
{
  id: "settings-backup", tab: "advanced", order: 190, heading: "Settings backup",
  intro: "A backup is an ordinary note in your vault. It holds everything you have set up here, so you can come back to it later or carry your setup to another vault",
  tip: "Saving writes a new note every time and never overwrites an earlier one, so the folder fills up and it is on you to delete what you no longer want. Restoring replaces <b>everything</b> on every tab and asks you to restart afterwards; whether the plugin saves what you have now before it writes is the toggle below. Because a backup is an ordinary note, syncing your vault carries it to your other machine, and restoring it there is how a setup travels",
  items: [
    { kind:"text", id:"backup-folder", path:"advanced.backups.folder", default:"Inline Overhaul/Backups", wide:true,
      name:"Backup folder", desc:"Where in your vault the backups are kept",
      tip:"Any folder you like. It is made when you save the first backup, not before. Backups are ordinary notes, so they travel with the vault and sync along with the rest of it" },
    { kind:"toggle", id:"backup-before-restore", path:"advanced.backups.beforeRestore", default:true,
      name:"Save a backup before restoring", desc:"Write what you have now into the folder above before an earlier backup replaces it",
      tip:"On, every restore leaves you a way back, and that copy is named with <code>Autogenerated</code> at the end so you can tell it from the ones you saved yourself. Off, restoring writes straight over what you have and the confirmation says so — pick that if you restore often and the folder fills up with copies you never asked for" },
    { kind:"buttons", id:"settings-backup-actions",
      name:"Your settings", desc:"Save what you have set up now, or bring back an earlier backup",
      tip:"Saving writes a new note every time and never overwrites an earlier one \u2014 delete the ones you no longer want yourself. Restoring replaces <b>everything</b> on every tab and asks you to restart afterwards. Whether what you have now is saved first is the toggle above, and a copy taken that way is named with <code>Autogenerated</code> at the end",
      buttons:[ {label:"Save a backup", action:"save-backup"},
                {label:"Restore a backup", action:"restore-backup", warning:true} ] },
    { kind:"buttons", id:"settings-reset-actions",
      name:"Start over", desc:"Delete everything you have set up here and go back to the plugin\u2019s own defaults",
      tip:"Everything means everything: every tab, every Field, every Value, every rule, every Binder row, and the hotkeys you gave to plugin commands. Hotkeys of other plugins are left alone. A backup of what you have now is written first, into the folder above, named with <code>Autogenerated</code> at the end, so the way back is the button next to this one \u2014 which is also what this is for: a way to check that a backup really brings everything back. This button writes that copy always, whatever the toggle above says: here it is the only way back there is",
      buttons:[ {label:"Delete all my settings", action:"reset-settings", warning:true} ] }
  ]
},
{
  id: "diagnostics", tab: "advanced", order: 200, heading: "Diagnostics",
  intro: "If something misbehaves, a log helps work out why. Be aware the log is saved into your vault and will contain the text of the lines you were working on",
  tip: "Leave this off unless you are chasing a problem. The log is an ordinary note in your vault, it grows with every keypress the plugin handles, and it records the lines you were on — so it carries whatever you happened to be writing. Turn it on, reproduce the problem once, turn it off, and read the note",
  items: [
    { kind:"toggle", id:"dev-mode", path:"advanced.devMode.enabled", default:false,
      name:"Developer logging", desc:"Record what the plugin did, to help track down a problem",
      searchTerms:["Enable Dev Mode"],
      tip:"Leave this off day to day. Turn it on, reproduce the problem once, then turn it off and attach the log to a bug report after checking what is in it" },
    { kind:"toggle", id:"dev-ai-log", path:"advanced.devMode.aiLog", default:true,
      name:"Machine-readable log", desc:"Also keep a second, denser log meant for tools rather than people",
      tip:"Only worth turning on if someone has asked you for it. The plain log is the one you can read yourself",
      searchTerms:["Generate log for AI?"], visible: on("advanced.devMode.enabled") },
    { kind:"text", id:"dev-log-path", path:"advanced.devMode.logPath", default:"InlineOverhaul_DevLog", wide:true,
      name:"Log file", desc:"Where in your vault the logs are put",
      tip:"They are ordinary notes, so they show up in search and in your graph. Keep them in a folder you exclude if that bothers you",
      searchTerms:["Log Path"], visible: on("advanced.devMode.enabled") }
  ]
}
];
