/**
 * ВНИМАНИЕ: файл сгенерирован из docs/prototype/settings_prototype.html.
 * Руками не правится. Правится прототип, затем `npm run gen:schema`.
 *
 * Тексты согласованы заказчиком и совпадают с Приложением B PRD.
 */

import type { SettingsGroup } from "../types.ts";
import { on, eq, both } from "../types.ts";
import { callout } from "../custom/callouts.ts";
import { dispatchTables } from "../custom/dispatch_tables.ts";
import { cycleOrder } from "../custom/order_lists.ts";
import { subheader } from "../custom/subheader.ts";

export const NAVIGATION_GROUPS: readonly SettingsGroup[] = [
{ id: "nav-intro",       tab: "navigation", order: 50, heading: "Before you start",
  items: [
    { kind:"custom", id:"nav-callout", render: callout("navigation") }
  ],
  visible: on("general.help.showCallouts") },
{
  id: "move-lines", tab: "navigation", order: 100, heading: "Move lines (up/down)",
  intro: "Reorder a note without cutting and pasting: pick up a line and walk it up or down",
  tip: "When a line has other lines indented beneath it, the whole bundle is called its <b>tree</b>. That word turns up in a few places here. The setting below is where you decide whether the bundle travels with the line or stays behind",
  commands: ["Move up", "Move down"],
  items: [
    { kind:"toggle", id:"move-lines-enabled", path:"navigation.moveLine.enabled", default:true,
      name:"Move lines", desc:"Let the keys pick up a line and move it",
      tip:"Off, the two commands stay in the palette and do nothing: nothing is deleted and no hotkey is lost. Turn it back on and everything is where you left it. What the keys do with a selection, and whether they carry the whole line or only the text, is set by the rows below",
      searchTerms:["Enable Move Line"] },
    { kind:"dropdown", id:"move-lines-no-selection", path:"navigation.moveLine.noSelectionMode", default:"line-only",
      name:"Moving behavior", desc:"Whether the tree under the line travels with it",
      searchTerms:["No-selection mode"], visible: on("navigation.moveLine.enabled"),
      options:[ {value:"line-only",label:"Line only"}, {value:"with-children",label:"Whole tree"} ],
      tip:"Say a line has three lines indented under it. <b>Line only</b> lifts that one line out and leaves the three where they are, so the order changes around them. <b>Whole tree</b> keeps the four together and moves them as one block" },
    { kind:"toggle", id:"move-lines-jump-trees", path:"navigation.moveLine.jumpNeighborTrees", default:false,
      name:"Jump over neighbor trees", desc:"Move the tree past the whole tree next to it instead of into its lines",
      visible: both(on("navigation.moveLine.enabled"), eq("navigation.moveLine.noSelectionMode","with-children")),
      tip:"Off, the tree moves one line per press, so it can pass into the lines indented under its neighbor and take them along. On, one press puts it above or below the whole neighbor at its own level, and the neighbor keeps its own lines" },
    { kind:"dropdown", id:"move-lines-heading", path:"navigation.moveLine.headerMode", default:"move-as-line",
      name:"Moving headings", desc:"If you are moving a heading, this decides whether the whole section moves or just the heading line",
      searchTerms:["Header mode"], visible: on("navigation.moveLine.enabled"),
      options:[ {value:"move-as-line",label:"Heading only"}, {value:"move-with-section",label:"Whole section"} ],
      tip:"With <b>heading with its section</b>, one press swaps two whole sections of a note, content and all. With <b>heading only</b> the heading text moves on its own and the paragraphs under it stay put, which is what you want when you are only reordering the headings" },
    { kind:"toggle", id:"move-lines-cross", path:"navigation.moveLine.crossSectionAllowed", default:true,
      name:"Cross heading boundaries", desc:"Let a line travel past a heading into the part of the note below it",
      searchTerms:["Cross-section allowed"], visible: on("navigation.moveLine.enabled"),
      tip:"Leave it on and a line keeps going wherever you push it. Turn it off and it stops at the heading, which is what you want in a note where each heading has to keep its own contents" },
    { kind:"toggle", id:"move-lines-select", path:"navigation.moveLine.highlightMovedLines", default:false,
      name:"Highlight after moving", desc:"Keep the lines highlighted once they land, so you can see what moved",
      tip:"Useful when you move a tree of several lines and want to be sure the whole thing came along",
      searchTerms:["Highlight moved lines", "Select after moving"], visible: on("navigation.moveLine.enabled") },
    { kind:"color", id:"move-lines-select-color", path:"navigation.moveLine.highlightColor", default:"",
      allowReset:true,
      name:"Moved lines color", desc:"Leave it unset to use the selection color of your theme",
      searchTerms:["Highlight color after moving"],
      tip:"Unset, the moved lines take the color your theme gives to selected text, see-through as it is. Pick your own if it is too pale to spot against your background; the reset button brings back the theme color",
      visible: both(on("navigation.moveLine.enabled"), on("navigation.moveLine.highlightMovedLines")) },
    { kind:"toggle", id:"move-lines-view", path:"navigation.moveLine.keepInView", default:true,
      name:"Follow the moved line", desc:"Scroll the note to the line you moved instead of leaving the view where it was",
      searchTerms:["Scroll on move","Keep in view","Screen jumps"], visible: on("navigation.moveLine.enabled"),
      tip:"Off, the note does not scroll at all: what you see stays exactly where it was, and a line pushed past the edge goes on moving out of sight. On, the view follows the line and puts it where the setting below says" },
    { kind:"dropdown", id:"move-lines-view-position", path:"navigation.moveLine.viewPosition", default:"center",
      name:"Where the line lands", desc:"The place on screen the moved line is scrolled to",
      searchTerms:["Scroll position","Center on move"],
      visible: both(on("navigation.moveLine.enabled"), on("navigation.moveLine.keepInView")),
      options:[ {value:"center",label:"Center"},
                {value:"top",label:"Top"},
                {value:"bottom",label:"Bottom"} ],
      tip:"The same place every time, so the note does not jump: one press does not center the line while the next throws it to the top. Near the start or the end of a note there is nothing left to scroll, and the line sits as close to the chosen place as the note allows" }
  ]
},
{
  id: "left-right", tab: "navigation", order: 200, heading: "Move lines (left/right)",
  intro: "Two keys, one for left and one for right, and between them they do three jobs: nudge a piece of text along a line, change the marker at the start of a line, or change how far the line is indented. Which one you get depends on what is selected \u2014 the two lists below spell it out",
  tip: "Two keys, three jobs, and the line decides which one you get. Highlight some text and they slide it along the line. On a plain line with nothing highlighted they change the marker at the start of it, walking down the Prefix list in this group. On an indented line <code>Move right</code> indents; at the left edge it changes the marker while <code>Cycle in both directions</code> is on, and a task keeps its checkbox. The two lists at the top of this group show the order the checks run in, and you switch each job below off on its own, so you can narrow the keys down to the one thing you want them to do",
  items: [
    { kind:"custom", id:"left-right-order", render: dispatchTables },
    { kind:"custom", id:"move-text-sub", render: subheader("Move text",
        "These two keys can do three different jobs, and this half is the one that needs a selection: highlight a phrase and they slide it along the line, leaving the line itself alone. With nothing highlighted none of it applies and the keys fall through to the rows further down") },
    { kind:"toggle", id:"move-text-enabled", path:"navigation.moveSelection.inlineEnabled", default:true,
      name:"Move selected text", desc:"Slide a highlighted phrase along its line",
      searchTerms:["Enable inline text move"],
      tip:"Highlight two words in the middle of a sentence and press <code>Move right</code>: they trade places with the word after them, and stay highlighted, so you can keep pressing until they are where you want" },
    { kind:"dropdown", id:"move-text-step", path:"navigation.moveSelection.inlineMoveMode", default:"auto",
      name:"Movement step", desc:"How far the highlighted text goes on each press",
      searchTerms:["Inline move mode"], visible: on("navigation.moveSelection.inlineEnabled"),
      options:[ {value:"auto",label:"Auto"}, {value:"char",label:"Character"},
                {value:"word",label:"Word"}, {value:"disabled",label:"Off"} ],
      tip:"<b>Auto</b> reads what you highlighted: part of a word moves letter by letter, a whole word hops over whole words. Pick one of the others if you would rather it always behave the same way" },
    { kind:"toggle", id:"move-text-word-escape", path:"navigation.moveSelection.inlineWordEscape", default:false,
      name:"Step out of the word", desc:"Let a highlighted part of a word carry on past the word it came from",
      searchTerms:["Leave the word","Word escape"],
      visible: both(on("navigation.moveSelection.inlineEnabled"), eq("navigation.moveSelection.inlineMoveMode","auto")),
      tip:"Only <code>Auto</code> has anything to decide here, which is why this row shows up for that step alone. Highlight two letters inside a word and <code>Auto</code> moves them letter by letter \u2014 but at the edge of the word it stops, because the next press would carry the letters into the word next door. On, it carries them: <b>te|xt more</b> becomes <b>te xtmore</b>, and that is the point \u2014 the highlighted piece goes wherever you press. Off is the way it has always worked" },
    { kind:"toggle", id:"move-text-cross", path:"navigation.moveSelection.inlineBoundaryJump", default:true,
      name:"Continue past Separators", desc:"Let the highlighted text leave your text and move into the tags at either end",
      visible: on("navigation.moveSelection.inlineEnabled"),
      tip:"Off, a highlighted phrase stays between the Separators: it will not slide back into the tags at the start of the line, nor forward into the dates at the end. Turn it on when you do want to shuffle a tag and a phrase past each other",
      seeAlso:{ id:"in-line-cross", label:"The cursor has the same setting of its own" } },
    { kind:"custom", id:"move-line-sub", render: subheader("Moving lines (left and right)",
        "The other half, and it works with nothing highlighted: the same two keys change the marker at the start of the line, or how far the line is indented. Which of the two you get is decided by the line you are on, and the two tables at the top of this group show the order those checks run in") },
    { kind:"toggle", id:"prefix-cycle-enabled", path:"navigation.moveSelection.prefixCyclerEnabled", default:true,
      name:"Cycle line Prefixes", desc:"Turn a line into a heading, a bullet, a numbered item or plain text, one press at a time",
      searchTerms:["Enable PrefixCycler"],
      tip:"<code>Move right</code> walks down the list below, <code>Move left</code> walks back up, and an empty row in it means plain text with no Prefix at all. Both cycle whenever the line has no indent; on an indented line they change the indent instead. Whether the right key cycles at all is the row below" },
    { kind:"custom", id:"cycle-order", render: cycleOrder,
      visible: on("navigation.moveSelection.prefixCyclerEnabled") },
    { kind:"toggle", id:"right-cycles", path:"navigation.moveSelection.rightCycles", default:true,
      name:"Cycle in both directions", desc:"On: <code>Move right</code> changes the marker too, but only on a line with no indent",
      visible: on("navigation.moveSelection.prefixCyclerEnabled"),
      tip:"On, both keys change the marker while the line sits at the left edge: <code>Move right</code> walks down the list below and <code>Move left</code> walks back up. <b>An indented line is not part of this</b> \u2014 there <code>Move right</code> indents as it always did, and cycling stays a <code>Move left</code> job. <b>The price is at the left edge</b>: a line with no indent is no longer pushed by <code>Move right</code> while the list still has somewhere to go, and what happens when it runs out is <code>After the last one</code> \u2014 with <b>Start over</b> the key never pushes at all, and indenting is left to <code>Tab</code>. Switch this off and the two keys split the work: <code>Move left</code> changes the marker, <code>Move right</code> only ever indents" },
    { kind:"dropdown", id:"prefix-cycle-end", path:"navigation.moveSelection.onCycleEnd", default:"indent",
      name:"After the last one", desc:"What happens when you reach the bottom of the list below",
      tip:"<b>Start over</b> loops back to the top, so you can keep pressing until you find what you want. <b>Indent</b> stops cycling and starts pushing the line to the right instead",
      searchTerms:["On cycle end"], visible: on("navigation.moveSelection.prefixCyclerEnabled"),
      options:[ {value:"indent",label:"Indent"}, {value:"wrap",label:"Start over"} ] },
    { kind:"toggle", id:"indent-fallback", path:"navigation.moveSelection.indentFallbackEnabled", default:true,
      name:"Change the indent", desc:"<code>Move right</code> indents a list item one step, <code>Move left</code> takes one step off",
      searchTerms:["Indent fallback"],
      /* \u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043d\u0435 \u0441\u0441\u044b\u043b\u0430\u0435\u0442\u0441\u044f \u043d\u0430 \u00ab\u0434\u0432\u0430 \u0434\u0435\u043b\u0430 \u0432\u044b\u0448\u0435\u00bb: \u043f\u0440\u0438 \u0432\u044b\u043a\u043b\u044e\u0447\u0435\u043d\u043d\u043e\u043c `Cycle line
         Prefixes` \u0441\u0442\u0440\u043e\u043a \u0432\u044b\u0448\u0435 \u043d\u0435 \u0432\u0438\u0434\u043d\u043e \u2014 \u0435\u0433\u043e \u0437\u0430\u043c\u0435\u0447\u0430\u043d\u0438\u0435 \u043a \u0442\u0435\u0441\u0442\u0443 1 \u0446\u0438\u043a\u043b\u0430 98
         (2026-09-28): \u00ab\u0442\u0435\u043a\u0443\u0449\u0435\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 indent-fallback \u0441\u0435\u0439\u0447\u0430\u0441 \u043d\u0435 \u043b\u043e\u0433\u0438\u0447\u043d\u043e\u0435\u00bb. */
      tip:"This is what the two keys do to a line when nothing is highlighted, and with <code>Cycle line Prefixes</code> off it is all they do. With it on, <code>Move left</code> takes the indent off first and only then changes the Prefix, and <code>Move right</code> changes the Prefix of a line at the left edge before it indents. Plain text is never indented: four spaces in front of it would turn it into a code block. Off, the keys never touch the indent \u2014 pick that if you indent with <code>Tab</code>" },
    { kind:"toggle", id:"indent-tree", path:"navigation.moveSelection.indentWithChildren", default:false,
      name:"Indent the whole tree", desc:"The lines indented under the line take the same step with it",
      visible: on("navigation.moveSelection.indentFallbackEnabled"),
      tip:"Say a list item has two lines indented under it. Off, <code>Move right</code> indents that one item and the two now sit at its level. On, all three move one step together and stay under it. Changing the Prefix never touches them either way" }
  ]
},
{
  id: "in-line", tab: "navigation", order: 400, heading: "Jump inside a line (left/right)",
  intro: "A line can hold tags before your text and dates after it. These keys walk the cursor between those parts without leaving the line",
  tip: "A tagged line has three parts: what comes before your text, your text, and what comes after. The arrow keys treat all of it as one long string and walk through the tags character by character. These two keys hop instead — word, sentence, or straight to one end of your text — and by default they stop at the Separators, so the cursor stays in the sentence you are writing and never lands inside a tag by accident",
  commands: ["Jump left", "Jump right"],
  items: [
    { kind:"toggle", id:"in-line-enabled", path:"navigation.navigateInline.enabled", default:true,
      name:"Move cursor inside a line", desc:"Let the keys walk the cursor along the line",
      tip:"This is the cursor walking your own sentence, not the note: it steps by word, by sentence or straight to the start or end, and it knows where your text ends and a Separator begins. Off, the commands stay and do nothing",
      searchTerms:["Enable Navigate Inline"] },
    { kind:"dropdown", id:"in-line-step", path:"navigation.navigateInline.stepMode", default:"word",
      name:"Step size", desc:"How big a hop the cursor makes each time",
      tip:"<b>Word</b> is the everyday choice. <b>Sentence</b> suits long paragraphs. <b>Start or end</b> skips the middle entirely and lands at one end of your text",
      searchTerms:["Step mode"], visible: on("navigation.navigateInline.enabled"),
      options:[ {value:"word",label:"Word"}, {value:"sentence",label:"Sentence"},
                {value:"begin-end",label:"Start or end"} ] },
    { kind:"toggle", id:"in-line-cross", path:"navigation.navigateInline.boundaryJump", default:false,
      name:"Continue past Separators", desc:"Let the cursor leave your text and walk into the tags at either end",
      searchTerms:["Allow crossing Separators", "Continue past Separators"], visible: on("navigation.navigateInline.enabled"),
      tip:"Off is the safer setting while you are writing: the cursor stays in your sentence and cannot wander into the tags. Turn it on when you want to reach a tag with the same keys instead of the mouse" },
    { kind:"dropdown", id:"in-line-boundary", path:"navigation.navigateInline.onBoundary", default:"wrap",
      name:"What to do at the end", desc:"When there is nowhere further to go in the line",
      searchTerms:["On boundary", "At the far end"], visible: on("navigation.navigateInline.enabled"),
      tip:"Say the cursor is on the last word before the closing Separator and you press again. <b>Stop</b> does nothing. <b>Wrap around</b> sends it back to the first word of the same stretch. <b>Next line</b> leaves the line entirely",
      options:[ {value:"stay",label:"Stop"}, {value:"wrap",label:"Wrap around"},
                {value:"next-line",label:"Next line"} ] }
  ]
},
{
  id: "heading-jumps", tab: "navigation", order: 500, heading: "Jump inside a note (up/down)",
  intro: "Skip through a long note by its headings instead of scrolling",
  tip: "In a note with headings these two keys move you a section at a time, which beats scrolling and beats the outline sidebar once your hands are on the keyboard. The settings below decide what counts as a stop — every heading, or every line — where on the line you land, and whether the note scrolls so that what you jumped to is actually on screen",
  commands: ["Jump up", "Jump down"],
  items: [
    { kind:"toggle", id:"heading-jumps-enabled", path:"navigation.jumpToHeader.enabled", default:true,
      name:"Jump between headings", desc:"Turn on the <code>Jump up</code> and <code>Jump down</code> commands",
      tip:"Both commands move between headings only; walking line by line is a mode inside them, not a separate feature. Off, they stay in the palette and do nothing, and any hotkey you gave them is kept",
      searchTerms:["Enable Jump To Header"] },
    { kind:"dropdown", id:"heading-jumps-mode", path:"navigation.jumpToHeader.jumpMode", default:"edge",
      name:"Jump target", desc:"Hop between headings, or crawl from one written line to the next",
      searchTerms:["Jump mode"], visible: on("navigation.jumpToHeader.enabled"),
      options:[ {value:"edge",label:"Headings"}, {value:"line",label:"Lines"} ],
      tip:"<b>Headings</b> is for finding your way around a long note. <b>Lines</b> turns the same keys into a slow walk through the text, which some people prefer to the arrow keys. It steps from one written line to the next and does not stop on the empty ones, nor on rules and table rows: those are spacing, not places to be" },
    { kind:"dropdown", id:"heading-jumps-edge", path:"navigation.jumpToHeader.edgeMode", default:"start-end",
      name:"Where in the section", desc:"Land at the start of the part you jump to, or at its end",
      tip:"<b>Start and end</b> means one press takes you to the start, the next to the end, so you can reach both without changing the setting",
      searchTerms:["Edge behavior"],
      visible: both(on("navigation.jumpToHeader.enabled"), eq("navigation.jumpToHeader.jumpMode","edge")),
      options:[ {value:"start-end",label:"Start and end"},
                {value:"start",label:"Start only"}, {value:"end",label:"End only"} ] },
    { kind:"dropdown", id:"heading-jumps-cursor", path:"navigation.jumpToHeader.jumpCursorPosition", default:"section-end",
      name:"Cursor position after jumping", desc:"Where on that line the cursor ends up",
      searchTerms:["Jump cursor position", "Cursor on arrival"], visible: on("navigation.jumpToHeader.enabled"),
      options:[ {value:"start",label:"Line start"}, {value:"end",label:"Line end"},
                {value:"section-start",label:"Text start"},
                {value:"section-end",label:"Text end"} ],
      tip:"<b>Text end</b> puts the cursor after the last word you wrote but before the tags and dates at the end of the line, so you can carry on typing without having to step back over them. <b>Text start</b> is the same place at the other end, just after the tags. This row also decides where <code>Jump right</code> drops you when you step in from the tags",
      seeAlso:{ id:"separator-2", label:"Where your text ends is set by the second Separator" } },
    { kind:"toggle", id:"heading-jumps-center", path:"navigation.jumpToHeader.centerCursor", default:true,
      name:"Follow the jump target", desc:"After a jump, scroll the note so the line you landed on is on screen",
      searchTerms:["Center the target","Center the screen on target","Scroll on jump"],
      tip:"Without it you often arrive at the very bottom of the window, with the section you jumped to still off screen below \u2014 so you have to scroll anyway. With it on, you can read straight away, and the row below says where on the screen you land",
      visible: on("navigation.jumpToHeader.enabled") },
    { kind:"dropdown", id:"heading-jumps-view-position", path:"navigation.jumpToHeader.viewPosition", default:"center",
      name:"Where the target lands", desc:"The place on screen the line you jump to is scrolled to",
      searchTerms:["Scroll position","Center on jump"],
      visible: both(on("navigation.jumpToHeader.enabled"), on("navigation.jumpToHeader.centerCursor")),
      options:[ {value:"center",label:"Center"},
                {value:"top",label:"Top"},
                {value:"bottom",label:"Bottom"} ],
      tip:"The same place every time, and the same three choices as the matching row of <code>Move lines</code>. Near the start or the end of a note there is nothing left to scroll, and the line sits as close to the chosen place as the note allows" }
  ]
}
];
