/**
 * ВНИМАНИЕ: файл сгенерирован из docs/prototype/settings_prototype.html.
 * Руками не правится. Правится прототип, затем `npm run gen:schema`.
 *
 * Тексты согласованы заказчиком и совпадают с Приложением B PRD.
 */

import type { SettingsGroup } from "../types.ts";
import { on, eq, both } from "../types.ts";
import { callout } from "../custom/callouts.ts";
import { dispatchTables } from "../custom/dispatch_tables.ts";
import { cycleOrder } from "../custom/order_lists.ts";
import { subheader } from "../custom/subheader.ts";

export const NAVIGATION_GROUPS: readonly SettingsGroup[] = [
{ id: "nav-intro",       tab: "navigation", order: 50, heading: "Before you start",
  items: [
    { kind:"custom", id:"nav-callout", render: callout("navigation") }
  ],
  visible: on("general.help.showCallouts") },
{
  id: "move-lines", tab: "navigation", order: 100, heading: "Move lines (up/down)",
  intro: "Reorder a note without cut and paste: move a line up or down with a key",
  tip: "A line with other lines indented under it forms a <b>tree</b>. The settings below decide whether those indented lines move with it or stay behind",
  commands: ["Move up", "Move down"],
  items: [
    { kind:"toggle", id:"move-lines-enabled", path:"navigation.moveLine.enabled", default:true,
      name:"Move lines", desc:"Let the keys pick up a line and move it",
      tip:"Off, the commands do nothing, but your hotkeys and settings are kept. Turn it back on and everything works as before",
      searchTerms:["Enable Move Line"] },
    { kind:"dropdown", id:"move-lines-no-selection", path:"navigation.moveLine.noSelectionMode", default:"line-only",
      name:"Moving behavior", desc:"Whether the tree under the line travels with it",
      searchTerms:["No-selection mode"], visible: on("navigation.moveLine.enabled"),
      options:[ {value:"line-only",label:"Line only"}, {value:"with-children",label:"Whole tree"} ],
      tip:"<b>Line only</b> moves just that line, and the lines indented under it stay where they are. <b>Whole tree</b> moves the line together with everything indented under it" },
    { kind:"toggle", id:"move-lines-jump-trees", path:"navigation.moveLine.jumpNeighborTrees", default:false,
      name:"Jump over neighbor trees", desc:"Move the tree past the whole tree next to it instead of into its lines",
      visible: both(on("navigation.moveLine.enabled"), eq("navigation.moveLine.noSelectionMode","with-children")),
      tip:"Off, the tree moves one line per press and can slip in among the neighbor's indented lines, taking them along. On, one press moves it past the whole neighbor, and the neighbor keeps its own lines" },
    { kind:"dropdown", id:"move-lines-heading", path:"navigation.moveLine.headerMode", default:"move-as-line",
      name:"Moving headings", desc:"If you are moving a heading, this decides whether the whole section moves or just the heading line",
      searchTerms:["Header mode"], visible: on("navigation.moveLine.enabled"),
      options:[ {value:"move-as-line",label:"Heading only"}, {value:"move-with-section",label:"Whole section"} ],
      tip:"<b>Heading with its section</b>: one press swaps two whole sections, content and all. <b>Heading only</b>: just the heading line moves and the text under it stays. Pick it when you only want to reorder headings" },
    { kind:"toggle", id:"move-lines-cross", path:"navigation.moveLine.crossSectionAllowed", default:true,
      name:"Cross heading boundaries", desc:"Let a line travel past a heading into the part of the note below it",
      searchTerms:["Cross-section allowed"], visible: on("navigation.moveLine.enabled"),
      tip:"On, a line keeps moving wherever you push it. Off, it stops at the heading — useful when each heading must keep its own contents" },
    { kind:"toggle", id:"move-lines-select", path:"navigation.moveLine.highlightMovedLines", default:false,
      name:"Highlight after moving", desc:"Keep the lines highlighted once they land, so you can see what moved",
      tip:"Useful when you move a tree of several lines and want to be sure the whole thing came along",
      searchTerms:["Highlight moved lines", "Select after moving"], visible: on("navigation.moveLine.enabled") },
    { kind:"color", id:"move-lines-select-color", path:"navigation.moveLine.highlightColor", default:"",
      allowReset:true,
      name:"Moved lines color", desc:"Leave it unset to use the selection color of your theme",
      searchTerms:["Highlight color after moving"],
      tip:"Unset, moved lines use your theme's selection color. Pick your own if that is too pale to see; the reset button brings the theme color back",
      visible: both(on("navigation.moveLine.enabled"), on("navigation.moveLine.highlightMovedLines")) },
    { kind:"toggle", id:"move-lines-view", path:"navigation.moveLine.keepInView", default:true,
      name:"Follow the moved line", desc:"Scroll the note to the line you moved instead of leaving the view where it was",
      searchTerms:["Scroll on move","Keep in view","Screen jumps"], visible: on("navigation.moveLine.enabled"),
      tip:"Off, the note never scrolls, and a line moved past the edge goes out of sight. On, the view follows the line and places it where the row below says" },
    { kind:"dropdown", id:"move-lines-view-position", path:"navigation.moveLine.viewPosition", default:"center",
      name:"Where the line lands", desc:"The place on screen the moved line is scrolled to",
      searchTerms:["Scroll position","Center on move"],
      visible: both(on("navigation.moveLine.enabled"), on("navigation.moveLine.keepInView")),
      options:[ {value:"center",label:"Center"},
                {value:"top",label:"Top"},
                {value:"bottom",label:"Bottom"} ],
      tip:"The line lands in the same place every time, so the note does not jump around. Near the start or end of a note it gets as close to that place as it can" }
  ]
},
{
  id: "left-right", tab: "navigation", order: 200, heading: "Move lines (left/right)",
  intro: "Two keys, three jobs: slide selected text along a line, change the marker at the start of a line, or change its indent. What you get depends on what is selected",
  tip: "Selected text: the keys slide it along the line. Nothing selected: they change the marker at the start of the line or its indent. The line decides which, as the lists at the top of this group show. A task keeps its checkbox. Switch off any job below to keep only the ones you want",
  items: [
    { kind:"custom", id:"left-right-order", render: dispatchTables },
    { kind:"custom", id:"move-text-sub", render: subheader("Move text",
        "This half works on selected text: highlight a phrase and the keys slide it along the line. With nothing selected, the settings further down apply instead") },
    { kind:"toggle", id:"move-text-enabled", path:"navigation.moveSelection.inlineEnabled", default:true,
      name:"Move selected text", desc:"Slide a highlighted phrase along its line",
      searchTerms:["Enable inline text move"],
      tip:"Highlight two words and press <code>Move right</code>: they swap places with the next word and stay highlighted, so you can keep pressing until they are where you want" },
    { kind:"dropdown", id:"move-text-step", path:"navigation.moveSelection.inlineMoveMode", default:"auto",
      name:"Movement step", desc:"How far the highlighted text goes on each press",
      searchTerms:["Inline move mode"], visible: on("navigation.moveSelection.inlineEnabled"),
      options:[ {value:"auto",label:"Auto"}, {value:"char",label:"Character"},
                {value:"word",label:"Word"}, {value:"disabled",label:"Off"} ],
      tip:"<b>Auto</b>: part of a word moves letter by letter, a whole word moves word by word. Pick another option if you want the same step every time" },
    { kind:"toggle", id:"move-text-word-escape", path:"navigation.moveSelection.inlineWordEscape", default:false,
      name:"Step out of the word", desc:"Let a highlighted part of a word carry on past the word it came from",
      searchTerms:["Leave the word","Word escape"],
      visible: both(on("navigation.moveSelection.inlineEnabled"), eq("navigation.moveSelection.inlineMoveMode","auto")),
      tip:"Shown only for <code>Auto</code>. Off, letters selected inside a word stop at the edge of the word. On, they keep going into the next word: <b>te|xt more</b> becomes <b>te xtmore</b>. Off is how it always worked" },
    { kind:"toggle", id:"move-text-cross", path:"navigation.moveSelection.inlineBoundaryJump", default:true,
      name:"Continue past Separators", desc:"Let the highlighted text leave your text and move into the tags at either end",
      visible: on("navigation.moveSelection.inlineEnabled"),
      tip:"Off, selected text stays between the Separators and never slides into the tags at the start or the dates at the end. Turn it on when you want to move a phrase past a tag",
      seeAlso:{ id:"in-line-cross", label:"The cursor has the same setting of its own" } },
    { kind:"custom", id:"move-line-sub", render: subheader("Moving lines (left and right)",
        "This half works with nothing selected: the same two keys change the marker at the start of the line or its indent. The line you are on decides which; the tables at the top of this group show the order") },
    { kind:"toggle", id:"prefix-cycle-enabled", path:"navigation.moveSelection.prefixCyclerEnabled", default:true,
      name:"Cycle line Prefixes", desc:"Turn a line into a heading, a bullet, a numbered item or plain text, one press at a time",
      searchTerms:["Enable PrefixCycler"],
      tip:"<code>Move right</code> goes down the list below, <code>Move left</code> goes back up; an empty row means plain text. This works on lines with no indent; on an indented line the keys change the indent instead. Whether <code>Move right</code> cycles too is set in the row below" },
    { kind:"custom", id:"cycle-order", render: cycleOrder,
      visible: on("navigation.moveSelection.prefixCyclerEnabled") },
    { kind:"toggle", id:"right-cycles", path:"navigation.moveSelection.rightCycles", default:true,
      name:"Cycle in both directions", desc:"On: <code>Move right</code> changes the marker too, but only on a line with no indent",
      visible: on("navigation.moveSelection.prefixCyclerEnabled"),
      tip:"On: at the left edge both keys change the marker. Indented lines are not affected — there <code>Move right</code> still indents. <b>The cost</b>: at the left edge <code>Move right</code> no longer indents until the list runs out, and with <b>Start over</b> in <code>After the last one</code> it never does, so indent with <code>Tab</code>. Off: <code>Move left</code> changes the marker, <code>Move right</code> only indents" },
    { kind:"dropdown", id:"prefix-cycle-end", path:"navigation.moveSelection.onCycleEnd", default:"indent",
      name:"After the last one", desc:"What happens when you reach the bottom of the list below",
      tip:"<b>Start over</b> goes back to the top of the list, so you can keep pressing. <b>Indent</b> stops changing the marker and starts indenting the line instead",
      searchTerms:["On cycle end"], visible: on("navigation.moveSelection.prefixCyclerEnabled"),
      options:[ {value:"indent",label:"Indent"}, {value:"wrap",label:"Start over"} ] },
    { kind:"toggle", id:"indent-fallback", path:"navigation.moveSelection.indentFallbackEnabled", default:true,
      name:"Change the indent", desc:"<code>Move right</code> indents a list item one step, <code>Move left</code> takes one step off",
      searchTerms:["Indent fallback"],
      /* \u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043d\u0435 \u0441\u0441\u044b\u043b\u0430\u0435\u0442\u0441\u044f \u043d\u0430 \u00ab\u0434\u0432\u0430 \u0434\u0435\u043b\u0430 \u0432\u044b\u0448\u0435\u00bb: \u043f\u0440\u0438 \u0432\u044b\u043a\u043b\u044e\u0447\u0435\u043d\u043d\u043e\u043c `Cycle line
         Prefixes` \u0441\u0442\u0440\u043e\u043a \u0432\u044b\u0448\u0435 \u043d\u0435 \u0432\u0438\u0434\u043d\u043e \u2014 \u0435\u0433\u043e \u0437\u0430\u043c\u0435\u0447\u0430\u043d\u0438\u0435 \u043a \u0442\u0435\u0441\u0442\u0443 1 \u0446\u0438\u043a\u043b\u0430 98
         (2026-09-28): \u00ab\u0442\u0435\u043a\u0443\u0449\u0435\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 indent-fallback \u0441\u0435\u0439\u0447\u0430\u0441 \u043d\u0435 \u043b\u043e\u0433\u0438\u0447\u043d\u043e\u0435\u00bb. */
      tip:"With <code>Cycle line Prefixes</code> on, the keys change the indent and the Prefix in turn: <code>Move left</code> removes the indent first, then changes the Prefix. Plain text is never indented, since that would turn it into a code block. Off, the keys never indent — pick that if you indent with <code>Tab</code>" },
    { kind:"toggle", id:"indent-tree", path:"navigation.moveSelection.indentWithChildren", default:false,
      name:"Indent the whole tree", desc:"The lines indented under the line take the same step with it",
      visible: on("navigation.moveSelection.indentFallbackEnabled"),
      tip:"Off, <code>Move right</code> indents only the item, and the lines under it end up at its level. On, they all move one step together and stay under it. Changing the Prefix never moves them" }
  ]
},
{
  id: "in-line", tab: "navigation", order: 400, heading: "Jump inside a line (left/right)",
  intro: "A line can hold tags before your text and dates after it. These keys move the cursor between those parts without leaving the line",
  tip: "Arrow keys crawl through tags one character at a time. These keys hop instead — by word, by sentence or straight to one end of your text. By default they stop at the Separators, so the cursor never lands inside a tag by accident",
  commands: ["Jump left", "Jump right"],
  items: [
    { kind:"toggle", id:"in-line-enabled", path:"navigation.navigateInline.enabled", default:true,
      name:"Move cursor inside a line", desc:"Let the keys walk the cursor along the line",
      tip:"The keys move the cursor through your own text by word, by sentence or to its start or end, and stop where a Separator begins. Off, the commands stay but do nothing",
      searchTerms:["Enable Navigate Inline"] },
    { kind:"dropdown", id:"in-line-step", path:"navigation.navigateInline.stepMode", default:"word",
      name:"Step size", desc:"How big a hop the cursor makes each time",
      tip:"<b>Word</b> is the everyday choice. <b>Sentence</b> suits long paragraphs. <b>Start or end</b> skips the middle entirely and lands at one end of your text",
      searchTerms:["Step mode"], visible: on("navigation.navigateInline.enabled"),
      options:[ {value:"word",label:"Word"}, {value:"sentence",label:"Sentence"},
                {value:"begin-end",label:"Start or end"} ] },
    { kind:"toggle", id:"in-line-cross", path:"navigation.navigateInline.boundaryJump", default:false,
      name:"Continue past Separators", desc:"Let the cursor leave your text and walk into the tags at either end",
      searchTerms:["Allow crossing Separators", "Continue past Separators"], visible: on("navigation.navigateInline.enabled"),
      tip:"Off is safer while writing: the cursor stays in your text and cannot wander into the tags. Turn it on to reach a tag with the same keys instead of the mouse" },
    { kind:"dropdown", id:"in-line-boundary", path:"navigation.navigateInline.onBoundary", default:"wrap",
      name:"What to do at the end", desc:"When there is nowhere further to go in the line",
      searchTerms:["On boundary", "At the far end"], visible: on("navigation.navigateInline.enabled"),
      tip:"On the last word before the closing Separator, you press again: <b>Stop</b> does nothing, <b>Wrap around</b> goes back to the first word, <b>Next line</b> moves on to the next line",
      options:[ {value:"stay",label:"Stop"}, {value:"wrap",label:"Wrap around"},
                {value:"next-line",label:"Next line"} ] }
  ]
},
{
  id: "heading-jumps", tab: "navigation", order: 500, heading: "Jump inside a note (up/down)",
  intro: "Skip through a long note by its headings instead of scrolling",
  tip: "Jump through a long note a section at a time — faster than scrolling or the outline once your hands are on the keyboard. Below you choose where the keys stop (headings or lines), where on the line you land, and whether the note scrolls to show it",
  commands: ["Jump up", "Jump down"],
  items: [
    { kind:"toggle", id:"heading-jumps-enabled", path:"navigation.jumpToHeader.enabled", default:true,
      name:"Jump between headings", desc:"Turn on the <code>Jump up</code> and <code>Jump down</code> commands",
      tip:"Off, the commands do nothing, but any hotkey you gave them is kept. Walking line by line is a mode of the same commands, set below",
      searchTerms:["Enable Jump To Header"] },
    { kind:"dropdown", id:"heading-jumps-mode", path:"navigation.jumpToHeader.jumpMode", default:"edge",
      name:"Jump target", desc:"Hop between headings, or crawl from one written line to the next",
      searchTerms:["Jump mode"], visible: on("navigation.jumpToHeader.enabled"),
      options:[ {value:"edge",label:"Headings"}, {value:"line",label:"Lines"} ],
      tip:"<b>Headings</b>: find your way around a long note. <b>Lines</b>: step from one written line to the next, skipping empty lines, rules and table rows — an alternative to the arrow keys" },
    { kind:"dropdown", id:"heading-jumps-edge", path:"navigation.jumpToHeader.edgeMode", default:"start-end",
      name:"Where in the section", desc:"Land at the start of the part you jump to, or at its end",
      tip:"<b>Start and end</b>: one press takes you to the start, the next to the end, so you reach both without changing the setting",
      searchTerms:["Edge behavior"],
      visible: both(on("navigation.jumpToHeader.enabled"), eq("navigation.jumpToHeader.jumpMode","edge")),
      options:[ {value:"start-end",label:"Start and end"},
                {value:"start",label:"Start only"}, {value:"end",label:"End only"} ] },
    { kind:"dropdown", id:"heading-jumps-cursor", path:"navigation.jumpToHeader.jumpCursorPosition", default:"section-end",
      name:"Cursor position after jumping", desc:"Where on that line the cursor ends up",
      searchTerms:["Jump cursor position", "Cursor on arrival"], visible: on("navigation.jumpToHeader.enabled"),
      options:[ {value:"start",label:"Line start"}, {value:"end",label:"Line end"},
                {value:"section-start",label:"Text start"},
                {value:"section-end",label:"Text end"} ],
      tip:"<b>Text end</b>: after your last word, before the tags and dates, so you can keep typing. <b>Text start</b>: right after the tags at the start. This also sets where <code>Jump right</code> lands when you step in from the tags",
      seeAlso:{ id:"separator-2", label:"Where your text ends is set by the second Separator" } },
    { kind:"toggle", id:"heading-jumps-center", path:"navigation.jumpToHeader.centerCursor", default:true,
      name:"Follow the jump target", desc:"After a jump, scroll the note so the line you landed on is on screen",
      searchTerms:["Center the target","Center the screen on target","Scroll on jump"],
      tip:"Off, you often land at the bottom edge of the window with the section still off screen. On, the note scrolls so you can read right away; the row below sets where the line appears",
      visible: on("navigation.jumpToHeader.enabled") },
    { kind:"dropdown", id:"heading-jumps-view-position", path:"navigation.jumpToHeader.viewPosition", default:"center",
      name:"Where the target lands", desc:"The place on screen the line you jump to is scrolled to",
      searchTerms:["Scroll position","Center on jump"],
      visible: both(on("navigation.jumpToHeader.enabled"), on("navigation.jumpToHeader.centerCursor")),
      options:[ {value:"center",label:"Center"},
                {value:"top",label:"Top"},
                {value:"bottom",label:"Bottom"} ],
      tip:"Same choices as in <code>Move lines</code>. The line lands in the same place every time; near the start or end of a note, as close as the note allows" }
  ]
}
];
