/**
 * ВНИМАНИЕ: файл сгенерирован из docs/prototype/settings_prototype.html.
 * Руками не правится. Правится прототип, затем `npm run gen:schema`.
 *
 * Тексты согласованы заказчиком и совпадают с Приложением B PRD.
 */

import type { SettingsGroup } from "../types.ts";
import { on, eq, both } from "../types.ts";
import { callout } from "../custom/callouts.ts";
import { dispatchTables } from "../custom/dispatch_tables.ts";
import { cycleOrder } from "../custom/order_lists.ts";
import { subheader } from "../custom/subheader.ts";

export const NAVIGATION_GROUPS: readonly SettingsGroup[] = [
{ id: "nav-intro",       tab: "navigation", order: 50, heading: "Before you start",
  items: [
    { kind:"custom", id:"nav-callout", render: callout("navigation") }
  ],
  visible: on("general.help.showCallouts") },
{
  id: "move-lines", tab: "navigation", order: 100, heading: "Move lines (up/down)",
  intro: "Reorder a note without cut and paste: move a line up or down with a key",
  tip: "A line with other lines indented under it is a <b>tree</b>. Say <code>- ask about Friday</code> sits indented under <code>- call Anna</code>. The settings below decide if <code>ask about Friday</code> moves with its parent line or stays behind",
  commands: ["Move up", "Move down"],
  items: [
    { kind:"toggle", id:"move-lines-enabled", path:"navigation.moveLine.enabled", default:true,
      name:"Move lines", desc:"Let the keys pick up a line and move it",
      tip:"- <b>On</b> — <code>Move down</code> swaps the line with the one below: <code>- call Anna</code>, <code>- buy milk</code> → <code>- buy milk</code>, <code>- call Anna</code>\n- <b>Off</b> — the commands do nothing. Your hotkeys and settings are kept for when you turn it back on",
      searchTerms:["Enable Move Line"] },
    { kind:"dropdown", id:"move-lines-no-selection", path:"navigation.moveLine.noSelectionMode", default:"line-only",
      name:"Moving behavior", desc:"Whether the tree under the line travels with it",
      searchTerms:["No-selection mode"], visible: on("navigation.moveLine.enabled"),
      options:[ {value:"line-only",label:"Line only"}, {value:"with-children",label:"Whole tree"} ],
      tip:"Say <code>- ask about Friday</code> is indented under <code>- call Anna</code>, and you press <code>Move down</code> on <code>call Anna</code>:\n- <b>Line only</b> — <code>call Anna</code> moves alone and drops below <code>ask about Friday</code>\n- <b>Whole tree</b> — both lines move together, below the next line" },
    { kind:"toggle", id:"move-lines-jump-trees", path:"navigation.moveLine.jumpNeighborTrees", default:false,
      name:"Jump over neighbor trees", desc:"Move the tree past the whole tree next to it instead of into its lines",
      visible: both(on("navigation.moveLine.enabled"), eq("navigation.moveLine.noSelectionMode","with-children")),
      tip:"The next tree is <code>- buy milk</code> with <code>- oat milk</code> under it. You press <code>Move down</code> on your tree:\n- <b>On</b> — one press puts your tree below the whole <code>buy milk</code> tree. <code>oat milk</code> stays with <code>buy milk</code>\n- <b>Off</b> — your tree moves one line, right below <code>buy milk</code>. <code>oat milk</code> ends up under your tree" },
    { kind:"dropdown", id:"move-lines-heading", path:"navigation.moveLine.headerMode", default:"move-as-line",
      name:"Moving headings", desc:"If you are moving a heading, this decides whether the whole section moves or just the heading line",
      searchTerms:["Header mode"], visible: on("navigation.moveLine.enabled"),
      options:[ {value:"move-as-line",label:"Heading only"}, {value:"move-with-section",label:"Whole section"} ],
      tip:"You press <code>Move down</code> on <code>## Plans</code>, and <code>## Ideas</code> comes next:\n- <b>Heading only</b> — just the heading line moves, one step per press. The text under it stays where it was\n- <b>Whole section</b> — <code>## Plans</code> and all its text jump below the whole <code>## Ideas</code> section" },
    { kind:"toggle", id:"move-lines-cross", path:"navigation.moveLine.crossSectionAllowed", default:true,
      name:"Cross heading boundaries", desc:"Let a line travel past a heading into the part of the note below it",
      searchTerms:["Cross-section allowed"], visible: on("navigation.moveLine.enabled"),
      tip:"<code>- call Anna</code> is the last line under <code>## Plans</code>, and you press <code>Move down</code>:\n- <b>On</b> — the line goes past <code>## Ideas</code> and lands right under it\n- <b>Off</b> — nothing happens. The line stays under its own heading" },
    { kind:"toggle", id:"move-lines-select", path:"navigation.moveLine.highlightMovedLines", default:false,
      name:"Highlight after moving", desc:"Keep the lines highlighted once they land, so you can see what moved",
      tip:"- <b>On</b> — after a move the lines stay tinted, so you can see the whole tree came along\n- <b>Off</b> — only the cursor shows where the line went",
      searchTerms:["Highlight moved lines", "Select after moving"], visible: on("navigation.moveLine.enabled") },
    { kind:"color", id:"move-lines-select-color", path:"navigation.moveLine.highlightColor", default:"",
      allowReset:true,
      name:"Moved lines color", desc:"Leave it unset to use the selection color of your theme",
      searchTerms:["Highlight color after moving"],
      tip:"Unset, moved lines use your theme's selection color. Pick your own if that is too pale to see; the reset button brings the theme color back",
      visible: both(on("navigation.moveLine.enabled"), on("navigation.moveLine.highlightMovedLines")) },
    { kind:"toggle", id:"move-lines-view", path:"navigation.moveLine.keepInView", default:true,
      name:"Follow the moved line", desc:"Scroll the note to the line you moved instead of leaving the view where it was",
      searchTerms:["Scroll on move","Keep in view","Screen jumps"], visible: on("navigation.moveLine.enabled"),
      tip:"- <b>On</b> — the note scrolls with the line, so it never goes out of sight. Where it sits is set in the row below\n- <b>Off</b> — the note never scrolls. Move a line past the bottom edge and it goes out of sight" },
    { kind:"dropdown", id:"move-lines-view-position", path:"navigation.moveLine.viewPosition", default:"center",
      name:"Where the line lands", desc:"The place on screen the moved line is scrolled to",
      searchTerms:["Scroll position","Center on move"],
      visible: both(on("navigation.moveLine.enabled"), on("navigation.moveLine.keepInView")),
      options:[ {value:"center",label:"Center"},
                {value:"top",label:"Top"},
                {value:"bottom",label:"Bottom"} ],
      tip:"Where the moved line sits on screen after each press:\n- <b>Center</b> — in the middle of the window\n- <b>Top</b> — at the top edge\n- <b>Bottom</b> — at the bottom edge\nNear the start or end of a note it gets as close as it can" }
  ]
},
{
  id: "left-right", tab: "navigation", order: 200, heading: "Move lines (left/right)",
  intro: "Two keys, three jobs: slide selected text along a line, change the marker at the start of a line, or change its indent. What you get depends on what is selected",
  tip: "<code>Move left</code> and <code>Move right</code> do three jobs:\n- <b>Text selected</b> — it slides along the line: <code>call Anna</code> → <code>Anna call</code>\n- <b>Line with no indent</b> — its marker changes: <code>call Anna</code> → <code>- call Anna</code>\n- <b>Indented line</b> — its indent changes\nSwitch off any job below to keep only the ones you want",
  items: [
    { kind:"custom", id:"left-right-order", render: dispatchTables },
    { kind:"custom", id:"move-text-sub", render: subheader("Move text",
        "This half works on selected text: highlight a phrase and the keys slide it along the line. With nothing selected, the settings further down apply instead") },
    { kind:"toggle", id:"move-text-enabled", path:"navigation.moveSelection.inlineEnabled", default:true,
      name:"Move selected text", desc:"Slide a highlighted phrase along its line",
      searchTerms:["Enable inline text move"],
      tip:"- <b>On</b> — select <code>call</code> in <code>call Anna today</code> and press <code>Move right</code>: <code>Anna call today</code>. The word stays selected, so you can keep pressing\n- <b>Off</b> — selected text does not move" },
    { kind:"dropdown", id:"move-text-step", path:"navigation.moveSelection.inlineMoveMode", default:"auto",
      name:"Movement step", desc:"How far the highlighted text goes on each press",
      searchTerms:["Inline move mode"], visible: on("navigation.moveSelection.inlineEnabled"),
      options:[ {value:"auto",label:"Auto"}, {value:"char",label:"Character"},
                {value:"word",label:"Word"}, {value:"disabled",label:"Off"} ],
      tip:"How far selected text goes on one press of <code>Move right</code>:\n- <b>Auto</b> — part of a word moves by letter: <code>e</code> in <code>teh</code> → <code>the</code>. A whole word moves by word: <code>call</code> → <code>Anna call</code>\n- <b>Character</b> — always one letter, even for a whole word\n- <b>Word</b> — always one word: <code>call Anna</code> → <code>Anna call</code>\n- <b>Off</b> — selected text does not move" },
    { kind:"toggle", id:"move-text-word-escape", path:"navigation.moveSelection.inlineWordEscape", default:false,
      name:"Step out of the word", desc:"Let a highlighted part of a word carry on past the word it came from",
      searchTerms:["Leave the word","Word escape"],
      visible: both(on("navigation.moveSelection.inlineEnabled"), eq("navigation.moveSelection.inlineMoveMode","auto")),
      tip:"Only for <code>Auto</code>. You select <code>ll</code> at the end of <code>call</code> in <code>call Anna</code> and press <code>Move right</code>:\n- <b>On</b> — the letters step out of the word: <code>call Anna</code> → <code>ca llAnna</code>\n- <b>Off</b> — nothing happens. Letters stop at the edge of their word, as it always worked" },
    { kind:"toggle", id:"move-text-cross", path:"navigation.moveSelection.inlineBoundaryJump", default:true,
      name:"Continue past Separators", desc:"Let the highlighted text leave your text and move into the tags at either end",
      visible: on("navigation.moveSelection.inlineEnabled"),
      tip:"You select <code>call</code> in <code>- #todo :: call Anna :: 📅2026-10-06</code> and press <code>Move left</code>:\n- <b>On</b> — the word jumps over the Separator: <code>- #todo call :: Anna :: 📅2026-10-06</code>\n- <b>Off</b> — nothing happens. Selected text stays between the Separators",
      seeAlso:{ id:"in-line-cross", label:"The cursor has the same setting of its own" } },
    { kind:"custom", id:"move-line-sub", render: subheader("Moving lines (left and right)",
        "This half works with nothing selected: the same two keys change the marker at the start of the line or its indent. The line you are on decides which; the tables at the top of this group show the order") },
    { kind:"toggle", id:"prefix-cycle-enabled", path:"navigation.moveSelection.prefixCyclerEnabled", default:true,
      name:"Cycle line Prefixes", desc:"Turn a line into a heading, a bullet, a numbered item or plain text, one press at a time",
      searchTerms:["Enable PrefixCycler"],
      tip:"- <b>On</b> — on a line with no indent the keys change the marker. <code>Move right</code>: <code>call Anna</code> → <code>- call Anna</code>. <code>Move left</code>: <code>call Anna</code> → <code>1. call Anna</code>\n- <b>Off</b> — the keys never change the marker\nThe order is the list below; an empty row means plain text. A task loses its checkbox: <code>- [ ] call Anna</code> → <code>call Anna</code>" },
    { kind:"custom", id:"cycle-order", render: cycleOrder,
      visible: on("navigation.moveSelection.prefixCyclerEnabled") },
    { kind:"toggle", id:"right-cycles", path:"navigation.moveSelection.rightCycles", default:true,
      name:"Cycle in both directions", desc:"On: <code>Move right</code> changes the marker too, but only on a line with no indent",
      visible: on("navigation.moveSelection.prefixCyclerEnabled"),
      tip:"- <b>On</b> — <code>Move right</code> changes the marker too: <code>call Anna</code> → <code>- call Anna</code>. Indented lines still get indented\n- <b>Off</b> — only <code>Move left</code> changes the marker. <code>Move right</code> only indents list items\nThe cost of On: <code>Move right</code> indents only once the list runs out. With <b>Start over</b> in <code>After the last one</code> it never does, so indent with <code>Tab</code>" },
    { kind:"dropdown", id:"prefix-cycle-end", path:"navigation.moveSelection.onCycleEnd", default:"indent",
      name:"After the last one", desc:"What happens when you reach the bottom of the list below",
      tip:"The line has the last marker of the list, <code>- </code> by default, and you press <code>Move right</code>:\n- <b>Indent</b> — the line moves one indent step right: <code>- call Anna</code> becomes a nested item\n- <b>Start over</b> — the list starts again from the top: <code>- call Anna</code> → <code># call Anna</code>",
      searchTerms:["On cycle end"], visible: on("navigation.moveSelection.prefixCyclerEnabled"),
      options:[ {value:"indent",label:"Indent"}, {value:"wrap",label:"Start over"} ] },
    { kind:"toggle", id:"indent-fallback", path:"navigation.moveSelection.indentFallbackEnabled", default:true,
      name:"Change the indent", desc:"<code>Move right</code> indents a list item one step, <code>Move left</code> takes one step off",
      searchTerms:["Indent fallback"],
      /* \u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043d\u0435 \u0441\u0441\u044b\u043b\u0430\u0435\u0442\u0441\u044f \u043d\u0430 \u00ab\u0434\u0432\u0430 \u0434\u0435\u043b\u0430 \u0432\u044b\u0448\u0435\u00bb: \u043f\u0440\u0438 \u0432\u044b\u043a\u043b\u044e\u0447\u0435\u043d\u043d\u043e\u043c `Cycle line
         Prefixes` \u0441\u0442\u0440\u043e\u043a \u0432\u044b\u0448\u0435 \u043d\u0435 \u0432\u0438\u0434\u043d\u043e \u2014 \u0435\u0433\u043e \u0437\u0430\u043c\u0435\u0447\u0430\u043d\u0438\u0435 \u043a \u0442\u0435\u0441\u0442\u0443 1 \u0446\u0438\u043a\u043b\u0430 98
         (2026-09-28): \u00ab\u0442\u0435\u043a\u0443\u0449\u0435\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 indent-fallback \u0441\u0435\u0439\u0447\u0430\u0441 \u043d\u0435 \u043b\u043e\u0433\u0438\u0447\u043d\u043e\u0435\u00bb. */
      tip:"- <b>On</b> — <code>Move right</code> indents a list item one step, <code>Move left</code> takes one step off. On an indented line <code>Move left</code> removes the indent first, then changes the marker\n- <b>Off</b> — the keys never indent. Pick it if you indent with <code>Tab</code>\nPlain text is never indented, since Obsidian would show it as a code block" },
    { kind:"toggle", id:"indent-tree", path:"navigation.moveSelection.indentWithChildren", default:false,
      name:"Indent the whole tree", desc:"The lines indented under the line take the same step with it",
      visible: on("navigation.moveSelection.indentFallbackEnabled"),
      tip:"<code>- ask about Friday</code> is indented under <code>- call Anna</code>, and you press <code>Move right</code> on <code>call Anna</code>:\n- <b>On</b> — both lines move one step right. <code>ask about Friday</code> stays under <code>call Anna</code>\n- <b>Off</b> — only <code>call Anna</code> moves. <code>ask about Friday</code> ends up at its level\nChanging the marker never moves the lines under it" }
  ]
},
{
  id: "in-line", tab: "navigation", order: 400, heading: "Jump inside a line (left/right)",
  intro: "A line can hold tags before your text and dates after it. These keys move the cursor between those parts without leaving the line",
  tip: "Arrow keys crawl through a line one letter at a time. <code>Jump left</code> and <code>Jump right</code> hop instead: by word, by sentence or straight to one end of your text. By default they stay between the Separators, so in <code>- #todo :: call Anna :: 📅2026-10-06</code> the cursor never lands in <code>#todo</code> or the date by accident",
  commands: ["Jump left", "Jump right"],
  items: [
    { kind:"toggle", id:"in-line-enabled", path:"navigation.navigateInline.enabled", default:true,
      name:"Move cursor inside a line", desc:"Let the keys walk the cursor along the line",
      tip:"- <b>On</b> — <code>Jump right</code> hops through your own text: <code>|call Anna</code> → <code>call |Anna</code>. How far is set below\n- <b>Off</b> — the commands stay but do nothing",
      searchTerms:["Enable Navigate Inline"] },
    { kind:"dropdown", id:"in-line-step", path:"navigation.navigateInline.stepMode", default:"word",
      name:"Step size", desc:"How big a hop the cursor makes each time",
      tip:"Where one press of <code>Jump right</code> takes the cursor <code>|</code>:\n- <b>Word</b> — to the next word: <code>|call Anna. Ask Bob</code> → <code>call |Anna. Ask Bob</code>\n- <b>Sentence</b> — to the end of the sentence: <code>|call Anna. Ask Bob</code> → <code>call Anna|. Ask Bob</code>\n- <b>Start or end</b> — to the end of your text: <code>|call Anna. Ask Bob</code> → <code>call Anna. Ask Bob|</code>",
      searchTerms:["Step mode"], visible: on("navigation.navigateInline.enabled"),
      options:[ {value:"word",label:"Word"}, {value:"sentence",label:"Sentence"},
                {value:"begin-end",label:"Start or end"} ] },
    { kind:"toggle", id:"in-line-cross", path:"navigation.navigateInline.boundaryJump", default:false,
      name:"Continue past Separators", desc:"Let the cursor leave your text and walk into the tags at either end",
      searchTerms:["Allow crossing Separators", "Continue past Separators"], visible: on("navigation.navigateInline.enabled"),
      tip:"The cursor is at <code>- #todo :: |call Anna :: 📅2026-10-06</code> and you press <code>Jump left</code>:\n- <b>On</b> — it walks into the tags: <code>- |#todo :: call Anna</code>. Handy to reach a tag without the mouse\n- <b>Off</b> — it never leaves your text, so it cannot land in a tag by accident. Safer while writing" },
    { kind:"dropdown", id:"in-line-boundary", path:"navigation.navigateInline.onBoundary", default:"wrap",
      name:"What to do at the end", desc:"When there is nowhere further to go in the line",
      searchTerms:["On boundary", "At the far end"], visible: on("navigation.navigateInline.enabled"),
      tip:"The cursor is at the end of your text, <code>call Anna|</code>, and you press <code>Jump right</code>:\n- <b>Stop</b> — nothing happens: <code>call Anna|</code>\n- <b>Wrap around</b> — back to the start: <code>|call Anna</code>\n- <b>Next line</b> — to the start of the text on the next line: <code>|buy milk</code>",
      options:[ {value:"stay",label:"Stop"}, {value:"wrap",label:"Wrap around"},
                {value:"next-line",label:"Next line"} ] }
  ]
},
{
  id: "heading-jumps", tab: "navigation", order: 500, heading: "Jump inside a note (up/down)",
  intro: "Skip through a long note by its headings instead of scrolling",
  tip: "Jump through a long note a section at a time — faster than scrolling or the outline once your hands are on the keyboard. Below you choose where the keys stop (headings or lines), where on the line you land, and whether the note scrolls to show it",
  commands: ["Jump up", "Jump down"],
  items: [
    { kind:"toggle", id:"heading-jumps-enabled", path:"navigation.jumpToHeader.enabled", default:true,
      name:"Jump between headings", desc:"Turn on the <code>Jump up</code> and <code>Jump down</code> commands",
      tip:"- <b>On</b> — <code>Jump up</code> and <code>Jump down</code> take the cursor through the note section by section\n- <b>Off</b> — the commands do nothing, but any hotkey you gave them is kept\nThe same commands can also walk line by line, see <code>Jump target</code> below",
      searchTerms:["Enable Jump To Header"] },
    { kind:"dropdown", id:"heading-jumps-mode", path:"navigation.jumpToHeader.jumpMode", default:"edge",
      name:"Jump target", desc:"Hop between headings, or crawl from one written line to the next",
      searchTerms:["Jump mode"], visible: on("navigation.jumpToHeader.enabled"),
      options:[ {value:"edge",label:"Headings"}, {value:"line",label:"Lines"} ],
      tip:"- <b>Headings</b> — hops section by section, so a long note goes by in a few presses. Where it stops is set below\n- <b>Lines</b> — steps to the next written line, skipping empty lines, rules and tables. A heading counts as a line. An alternative to the arrow keys" },
    { kind:"dropdown", id:"heading-jumps-edge", path:"navigation.jumpToHeader.edgeMode", default:"start-end",
      name:"Where in the section", desc:"Land at the start of the part you jump to, or at its end",
      tip:"<code>## Plans</code> and <code>## Ideas</code> have two lines each. Pressing <code>Jump down</code> from <code>## Plans</code> stops at:\n- <b>Start and end</b> — the last line of Plans, then the first of Ideas, then the last of Ideas\n- <b>Start only</b> — the first line of Plans, then the first of Ideas\n- <b>End only</b> — the last line of Plans, then the last of Ideas",
      searchTerms:["Edge behavior"],
      visible: both(on("navigation.jumpToHeader.enabled"), eq("navigation.jumpToHeader.jumpMode","edge")),
      options:[ {value:"start-end",label:"Start and end"},
                {value:"start",label:"Start only"}, {value:"end",label:"End only"} ] },
    { kind:"dropdown", id:"heading-jumps-cursor", path:"navigation.jumpToHeader.jumpCursorPosition", default:"section-end",
      name:"Cursor position after jumping", desc:"Where on that line the cursor ends up",
      searchTerms:["Jump cursor position", "Cursor on arrival"], visible: on("navigation.jumpToHeader.enabled"),
      options:[ {value:"start",label:"Line start"}, {value:"end",label:"Line end"},
                {value:"section-start",label:"Text start"},
                {value:"section-end",label:"Text end"} ],
      tip:"Where the cursor lands on <code>- #todo :: call Anna :: 📅2026-10-06</code>:\n- <b>Line start</b> — after the list marker: <code>- |#todo</code>\n- <b>Line end</b> — after the date: <code>📅2026-10-06|</code>\n- <b>Text start</b> — after the tags: <code>:: |call Anna</code>\n- <b>Text end</b> — after your last word, ready to type: <code>call Anna| ::</code>",
      seeAlso:{ id:"separator-2", label:"Where your text ends is set by the second Separator" } },
    { kind:"toggle", id:"heading-jumps-center", path:"navigation.jumpToHeader.centerCursor", default:true,
      name:"Follow the jump target", desc:"After a jump, scroll the note so the line you landed on is on screen",
      searchTerms:["Center the target","Center the screen on target","Scroll on jump"],
      tip:"- <b>On</b> — the note scrolls so the line you land on is on screen. Where it sits is set in the row below\n- <b>Off</b> — the note does not scroll. You often land at the bottom edge with the section still out of sight",
      visible: on("navigation.jumpToHeader.enabled") },
    { kind:"dropdown", id:"heading-jumps-view-position", path:"navigation.jumpToHeader.viewPosition", default:"center",
      name:"Where the target lands", desc:"The place on screen the line you jump to is scrolled to",
      searchTerms:["Scroll position","Center on jump"],
      visible: both(on("navigation.jumpToHeader.enabled"), on("navigation.jumpToHeader.centerCursor")),
      options:[ {value:"center",label:"Center"},
                {value:"top",label:"Top"},
                {value:"bottom",label:"Bottom"} ],
      tip:"Where the line you jump to sits on screen, as in <code>Move lines</code>:\n- <b>Center</b> — in the middle of the window\n- <b>Top</b> — at the top edge, with the section below it in view\n- <b>Bottom</b> — at the bottom edge\nNear the start or end of a note it gets as close as it can" }
  ]
}
];
