/**
 * ВНИМАНИЕ: файл сгенерирован из docs/prototype/settings_prototype.html.
 * Руками не правится. Правится прототип, затем `npm run gen:schema`.
 *
 * Тексты согласованы заказчиком и совпадают с Приложением B PRD.
 */

import type { SettingsGroup } from "../types.ts";
import { on, eq } from "../types.ts";
import { callout } from "../custom/callouts.ts";
import { floatingButton, sourcePreview } from "../custom/previews.ts";
import { smartRules } from "../custom/smart_rules.ts";
import { sourceFields } from "../custom/source_fields.ts";

export const TRANSFORM_GROUPS: readonly SettingsGroup[] = [
{ id: "transform-intro", tab: "transform",  order: 50, heading: "Before you start",
  items: [
    { kind:"custom", id:"transform-callout", render: callout("transform") }
  ],
  visible: on("general.help.showCallouts") },
{
  id: "inline-to-note", tab: "transform", order: 100, heading: "Inline to note",
  tip: "One press does three things: it picks the note, puts your text into it and tidies up your line. The groups below go in that order. Nothing happens until <code>Inline to note</code> just below is on",
  intro: "Press a key and the line you wrote becomes a note of its own, or is added to a note you already have. If you want, the line keeps a link to that note",
  commands: ["Transform inline to note"],
  items: [
    { kind:"toggle", id:"i2n-enabled", path:"transform.inline2note.enabled", default:false,
      name:"Inline to note", desc:"Allow this to create notes and add to notes you already have",
      searchTerms:["Inline2Note enabled"],
      tip:"This is the main switch that lets the plugin write to your vault. Everything else on this tab only decides how. One press can add a note, change a note and edit your line, so make a backup first" },
    { kind:"folder", id:"i2n-templates-folder", clearable:true, path:"transform.inline2note.templatesFolder", default:"",
      name:"Templates folder", desc:"The folder your note templates live in",
      placeholder:"Pick or type a folder",
      tip:"A template is a normal note that each new note starts as a copy of. Templates in this folder appear in the lists below. Start typing to pick one of your folders. A new name is fine too: the folder is created the first time it is needed",
      visible: on("transform.inline2note.enabled") },
    { kind:"dropdown", id:"i2n-default-template", path:"transform.inline2note.defaultTemplate", default:"",
      name:"Default template", desc:"The template on creation of new note when no special rules apply (see <code>Smart Rules</code> below)",
      tip:"Smart Rules below can pick a different template for certain lines. This one covers everything else. The list shows only notes from <code>Templates folder</code>, so set that first",
      visible: on("transform.inline2note.enabled"),
      /* Только заметки из назначенной папки (1.6.2.4). Постоянных строк
         нет: что показать, когда папки нет, решает сам источник. */
      options:[], optionsFrom:"templates" },
    { kind:"folder", id:"i2n-output-folder", clearable:true, path:"transform.inline2note.outputFolder", default:"",
      name:"New notes folder", desc:"Where to put the notes this creates. Leave it empty to keep them next to the note you are in",
      placeholder:"Next to the current note",
      tip:"Start typing to pick one of your folders. A new name is fine too: the folder is created when the first note goes into it",
      searchTerms:["Output folder for new notes"], visible: on("transform.inline2note.enabled") },
    { kind:"toggle", id:"i2n-floating", path:"transform.inline2note.floatingButton", default:false,
      name:"Floating button", desc:"Put a small button at the end of the line you are on",
      searchTerms:["Flying button"],
      visible: on("transform.inline2note.enabled"),
      tip:"Clicking it does the same as pressing the key. The button only shows on screen and is never saved into your note",
      seeAlso:{ id:"i2n-button-preview", label:"See where it appears" } },
    { kind:"slider", id:"i2n-floating-gap", path:"transform.inline2note.floatingButtonGap", default:12,
      min:0, max:40, step:1, unit:"px",
      name:"Distance from the text", desc:"How much room to leave between the line and the button",
      searchTerms:["Floating button gap","Button offset"],
      visible:{ deps:["transform.inline2note.enabled","transform.inline2note.floatingButton"],
                test: c => Boolean(c.get("transform.inline2note.enabled") && c.get("transform.inline2note.floatingButton")) },
      tip:"On a short line the button can sit so close that it looks like part of the text. <code>0</code> puts it right against the text. The widest setting puts it a whole word away",
      seeAlso:{ id:"i2n-button-preview", label:"The preview below moves with it" } },
    { kind:"custom", id:"i2n-button-preview", render: floatingButton,
      visible:{ deps:["transform.inline2note.enabled","transform.inline2note.floatingButton"],
                test: c => Boolean(c.get("transform.inline2note.enabled") && c.get("transform.inline2note.floatingButton")) } },
    { kind:"toggle", id:"content-open", path:"transform.inline2note.openTarget", default:false,
      name:"Open note after creation", desc:"Jump straight to the note once it is written",
      tip:"Keep it on while you set things up, so you can see the result. Turn it off once you trust it, and you stay where you were writing",
      searchTerms:["Open transformed note", "Open the note afterwards"],
      visible: on("transform.inline2note.enabled") }
  ]
},
{
  id: "naming", tab: "transform", order: 200, heading: "New note naming",
  intro: "Every new note needs a name. Here you choose where that name comes from",
  tip: "The plugin tries three sources in order and takes the first that works: the text between your <code>Name brackets</code>, then a heading on the line, then the first few words",
  visible: on("transform.inline2note.enabled"),
  items: [
    { kind:"dropdown", id:"naming-mode", path:"transform.inline2note.noteName.mode", default:"auto",
      name:"Note name", desc:"Take the name from the line, or stop and ask you for it",
      tip:"<b>Ask</b> opens a small box with the suggested name already filled in, so you can accept it or type your own. Pick it if you want to check each name before the note is made",
      searchTerms:["Note name mode"],
      options:[ {value:"auto",label:"From line"}, {value:"manual",label:"Ask"} ] },
    { kind:"text", id:"naming-delimiters", path:"transform.inline2note.noteName.delimiters", default:"[]", mono:true,
      name:"Name brackets", desc:"Two characters. Whatever you put between them becomes the name",
      searchTerms:["Title delimiters", "Explicit name delimiters", "Name brackets"],
      tip:"With <code>()</code> here, the line <code>- call (Anna about the contract) || text</code> gives a note called <b>Anna about the contract</b>. Leave it empty and the name comes from a heading or the first words" },
    { kind:"number", id:"naming-word-count", path:"transform.inline2note.noteName.wordCount", default:6, min:1, max:20,
      name:"Words to use instead", desc:"How many of the first words to use when there are no brackets",
      searchTerms:["Auto title word count"],
      tip:"With 3, the line <code>- draft the settings prototype today</code> becomes a note called <b>draft the settings</b>. Too few words and the names all look alike. Too many and they get long" },
    { kind:"dropdown", id:"naming-collision", path:"transform.inline2note.nameCollision.mode", default:"new_note",
      name:"If the name already taken", desc:"What to do when you already have a note with that name",
      searchTerms:["Name collision mode", "If the name is taken"],
      options:[ {value:"new_note",label:"New note"}, {value:"add_to_note",label:"Add to existing"},
                {value:"overwrite",label:"Overwrite"} ],
      tip:"- <b>New note</b> — adds a number to the name and never touches your old note, so it is the safe choice\n- <b>Add to existing</b> — suits a running log\n- <b>Overwrite</b> — deletes the old contents for good, and the plugin cannot bring them back" }
  ]
},
{
  id: "note-content", tab: "transform", order: 300, heading: "Note content",
  intro: "What the new note looks like inside: where your text goes and what sits above it",
  tip: "You make two choices here. First, where your text lands: at the top, at the end, or at the end of a section you name. The section option is handy when one note collects many entries. Second, what goes on the line above each entry to keep them apart: a date, a word of your own, or nothing. The rest of the note comes from the template you chose above",
  visible: on("transform.inline2note.enabled"),
  items: [
    { kind:"dropdown", id:"content-position", path:"transform.inline2note.placement.position", default:"end",
      name:"Where to put the text", desc:"At the top of the note, or after whatever is already there",
      searchTerms:["Where to place inline text?"],
      options:[ {value:"beginning",label:"Beginning"}, {value:"end",label:"End"},
                {value:"custom-header",label:"Under heading"} ],
      tip:"If you add to the same note again and again, like a diary or a call log, pick <b>at the end</b> to keep entries in the order you wrote them. <b>Under heading</b> puts each entry at the end of the section you name below. For a brand new note it makes no difference" },
    { kind:"text", id:"content-target-header", clearable:true, path:"transform.inline2note.placement.targetHeader",
      default:"", mono:true, placeholder:"# Heading name",
      name:"Name of the heading", desc:"The heading your text is filed under",
      tip:"Type the heading as it appears in the note. With hashes, like <code>## Log</code>, only a heading of that level counts. Without them, any level does. Case does not matter, and if two headings match, the first one is used. If the heading is missing, it is created at the level you set here (no hashes means level 1)",
      visible: eq("transform.inline2note.placement.position","custom-header") },
    { kind:"dropdown", id:"content-header-missing", path:"transform.inline2note.placement.fallback",
      default:"end",
      name:"If heading not found", desc:"Where the heading is added when the note has none",
      options:[ {value:"beginning",label:"Beginning"}, {value:"end",label:"End"} ],
      tip:"A new note has no such heading yet, so it is <b>written for you</b> here, exactly as you named it above, and your text goes under it. Later entries find it and join the same section instead of starting a new one",
      visible: eq("transform.inline2note.placement.position","custom-header") },
    { kind:"dropdown", id:"content-header-mode", path:"transform.inline2note.placement.headerMode", default:"datetime",
      name:"Line above the text", desc:"Something to put above your text so entries stay apart",
      tip:"In a note that collects many entries, a date or a word of your own above each entry keeps them from running together. Whether that line is a heading is set in the row below",
      searchTerms:["Inserted block header"],
      options:[ {value:"custom",label:"Fixed text"}, {value:"datetime",label:"Date and time"},
                {value:"none",label:"None"} ] },
    { kind:"dropdown", id:"content-header-level", path:"transform.inline2note.placement.headerLevel", default:"3",
      name:"Line above is a heading", desc:"Make that line a heading you can fold, or leave it as plain text",
      tip:"A heading folds and shows in the outline, which suits a note that collects many entries. The number sets the level: <code>1</code> is the biggest. You do not type the hashes because this row adds them",
      visible:{ deps:["transform.inline2note.placement.headerMode"],
                test: c => String(c.get("transform.inline2note.placement.headerMode") || "") !== "none" },
      options:[ {value:"0",label:"Plain text"}, {value:"1",label:"1"}, {value:"2",label:"2"},
                {value:"3",label:"3"}, {value:"4",label:"4"}, {value:"5",label:"5"}, {value:"6",label:"6"} ] },
    { kind:"text", id:"content-header-text", clearable:true, path:"transform.inline2note.placement.customHeader", default:"Captured", mono:true,
      name:"Text of the line above", desc:"Typed into the note exactly as you write it here",
      tip:"Type only the words. The hashes come from <code>Line above is a heading</code>, and any hashes you type here are removed",
      visible: eq("transform.inline2note.placement.headerMode","custom") },
    { kind:"text", id:"content-datetime", clearable:true, path:"transform.inline2note.placement.datetimeFormat", default:"YYYY-MM-DD HH:mm", mono:true,
      name:"Date format", desc:"Today\u2019s date, written the way you set out here",
      searchTerms:["Datetime header format"],
      visible: eq("transform.inline2note.placement.headerMode","datetime"),
      tip:"- <code>YYYY</code> — the year\n- <code>MM</code>, <code>DD</code> — the month, the day\n- <code>HH mm ss</code> — the time\nAnything else stays as you typed it, so <code>YYYY-MM-DD</code> gives <b>2026-08-21</b>" }
  ]
},
{
  id: "source-line", tab: "transform", order: 400, heading: "Source line",
  intro: "What happens to the line you pressed on, after the note is safely saved",
  tip: "Your line changes only after the note is saved, so nothing is lost if saving fails. The plugin can replace your text with a link to the note, and it can add a mark that shows the line is done. Both are optional. With both off, the line looks untouched, and pressing again by mistake makes a second note",
  visible: on("transform.inline2note.enabled"),
  items: [
    { kind:"custom", id:"source-preview", render: sourcePreview },
    { kind:"dropdown", id:"content-sublines", path:"transform.inline2note.sublines", default:"stay",
      name:"Sub-lines (tree) behavior", desc:"Leave them where they are, or take them into the note too",
      tip:"Say the line has three sub-points:\n- <b>Move</b> — takes all four lines into the note and removes them from here\n- <b>Keep</b> — copies all four into the note and leaves the sub-points where they are",
      searchTerms:["Sublines behavior"],
      options:[ {value:"stay",label:"Keep"}, {value:"remove",label:"Move"} ],
      visible: on("transform.inline2note.enabled") },
    { kind:"dropdown", id:"source-text", path:"transform.inline2note.sourceProcessing.text", default:"remove",
      name:"What happens with current line", desc:"The text goes into the note either way \u2014 this is about the line you pressed on",
      searchTerms:["What happens to your text"],
      options:[ {value:"remove",label:"Remove"}, {value:"leave",label:"Keep"},
                {value:"leave_named",label:"Keep without name"},
                {value:"words",label:"Keep first words"} ],
      tip:"- <b>Remove</b> — the line gets short and the link still points to your text\n- <b>Keep</b> — every word stays, which is good when you add to a note rather than move\n- <b>Keep without name</b> — the link replaces the words that became the name\n- <b>Keep first words</b> — the same, trimmed to <code>Words to keep</code>",
      visible: on("transform.inline2note.enabled") },
    { kind:"number", id:"source-keep-words", path:"transform.inline2note.sourceProcessing.keepWords", default:3, min:1, max:20,
      name:"Words to keep", desc:"How much of the line stays behind",
      tip:"Counted after the words that became the note name are gone, since the link takes their place. The rest of the text moves into the note. If the whole text became the name, only the link is left",
      visible: eq("transform.inline2note.sourceProcessing.text","words") },
    { kind:"note", id:"source-fields-head",
      name:"Fields to keep", desc:"Which Fields stay on the line you pressed on",
      tip:"Ticked Fields stay on the line. Unticked ones go into the note with the text. A kept Field is still copied into the note as well. Tick nothing and the line keeps only your text and the mark",
      visible: on("transform.inline2note.enabled") },
    { kind:"custom", id:"source-fields", render: sourceFields,
      visible: on("transform.inline2note.enabled") },
    { kind:"toggle", id:"source-keep-sub", path:"transform.inline2note.sourceProcessing.keepSubFields", default:false,
      name:"Keep sub-fields",
      desc:"A Field you keep keeps its child Values on the line too",
      tip:"Child Fields have no row of their own in the list above. They follow their parent:\n- <b>Off</b> — the kept Field stays on the line and its child Values go into the note\n- <b>On</b> — they stay on the line too, and a copy still goes into the note",
      visible: on("transform.inline2note.enabled") },
    { kind:"toggle", id:"source-link", path:"transform.inline2note.sourceProcessing.replaceWithLink", default:true,
      name:"Insert wikilink in current line", desc:"Put a link to the new note on the line you pressed on",
      searchTerms:["Replace payload with note link", "Leave a link behind"],
      tip:"On: click the link on the line to open the note. Off, with the text removed: nothing on the line shows where it went, and pressing again by mistake makes a second note. The mark below is the usual way to prevent that" },
    { kind:"text", id:"source-marker", clearable:true, path:"transform.inline2note.sourceProcessing.token", default:"#processed", mono:true,
      name:"Mark transformed line", desc:"A word or tag added to the line so you can see it has been handled",
      searchTerms:["Processed token", "Mark the line as done"],
      tip:"Type something like <code>#moved</code>. Then search for it to find everything you have filed, or hide those lines from a to-do list. Leave it empty to add nothing" },
    { kind:"dropdown", id:"source-marker-position", path:"transform.inline2note.sourceProcessing.panel", default:"right",
      name:"Where the mark goes", desc:"Before your text, or after it",
      tip:"The mark shows the line is already a note, so it is not done twice. The Left Block puts the mark with the tags. The Right Block keeps your sentence first. Pick whichever reads better to you",
      searchTerms:["Processed token panel"],
      visible:{ deps:["transform.inline2note.sourceProcessing.token"],
                test: c => String(c.get("transform.inline2note.sourceProcessing.token") || "").trim() !== "" },
      options:[ {value:"left",label:"Left Block"}, {value:"right",label:"Right Block"} ] },
    { kind:"toggle", id:"source-dim", path:"transform.inline2note.sourceProcessing.visual.enabled", default:false,
      name:"Dim transformed line", desc:"Fade a line once it carries the mark above, so your eye skips it",
      searchTerms:["Dim the lines already filed"],
      visible:{ deps:["transform.inline2note.sourceProcessing.token"],
                test: c => String(c.get("transform.inline2note.sourceProcessing.token") || "").trim() !== "" },
      tip:"Lines that are already notes stand out as much as the rest of the page. When they are faded, they stay in place and you can still search them, but they no longer catch your eye. Only the look changes. If you remove the mark by hand, the line goes back to normal" },
    { kind:"slider", id:"source-dim-opacity", path:"transform.inline2note.sourceProcessing.visual.opacity", default:65,
      min:0, max:80, step:5, unit:"%", invert:100,
      name:"Opacity of transformed line", desc:"Zero leaves the line as it is, eighty makes it barely readable",
      searchTerms:["How much is left"],
      tip:"Only the look changes: the text stays whole, search still finds it and <code>Undo</code> still works. Use the least fade that lets your eye skip the line. Too much, and you may miss a line you still need to fix",
      visible:{ deps:["transform.inline2note.sourceProcessing.token","transform.inline2note.sourceProcessing.visual.enabled"],
                test: c => String(c.get("transform.inline2note.sourceProcessing.token") || "").trim() !== ""
                  && Boolean(c.get("transform.inline2note.sourceProcessing.visual.enabled")) } },
    { kind:"color", id:"source-dim-color", path:"transform.inline2note.sourceProcessing.visual.color", default:"",
      name:"Color of transformed line", desc:"Leave it unset to keep the color your theme gives the text",
      allowReset:true,
      searchTerms:["Color of a filed line"],
      tip:"Set it only if fading alone does not make finished lines easy to spot. Your color replaces the theme’s, and the fade above still applies",
      visible:{ deps:["transform.inline2note.sourceProcessing.token","transform.inline2note.sourceProcessing.visual.enabled"],
                test: c => String(c.get("transform.inline2note.sourceProcessing.token") || "").trim() !== ""
                  && Boolean(c.get("transform.inline2note.sourceProcessing.visual.enabled")) } }
  ]
},
{
  id: "backlinks", tab: "transform", order: 450, heading: "Auto-MOC in your links",
  intro: "When a line links to other notes, each of them can get a link back to the new note",
  tip: "A line often names the notes it belongs to, like a project, a person or a place. With this on, each of them gets a link to the new note, so a project note slowly lists everything filed under it. Only links that are a Value of a Field count. Links inside your own sentence are left alone",
  visible: on("transform.inline2note.enabled"),
  items: [
    { kind:"toggle", id:"backlink-enabled", path:"transform.inline2note.backlink.enabled", default:false,
      name:"Link the notes you mention",
      desc:"Write a link to the new note into the notes of the link Values on this line",
      searchTerms:["Create wikilink to transformed note in reference notes","Backlinks into the notes you mention","Automatic MOC"],
      tip:"Links use the full path, so they find the right note even when two notes share a name. Only existing notes get the link. Missing Value notes are not created, but a navigator’s note is. A note that already links to the new one is left as it is" },
    { kind:"toggle", id:"backlink-navigator", path:"transform.inline2note.backlink.navigator", default:false,
      name:"Link to Navigator",
      desc:"Also write the link into the navigator note of a child link",
      tip:"Normally a child link’s navigator gets nothing. With this on, the navigator note gets the link too, and a child under two navigators gets links from both. A missing navigator note is created empty. A Tag navigator is not a note, so nothing is written for it",
      visible: on("transform.inline2note.backlink.enabled") },
    { kind:"toggle", id:"backlink-empty-line", path:"transform.inline2note.backlink.emptyLine", default:true,
      name:"Add empty line before wikilink",
      desc:"Keep a blank line between the links written into a note",
      tip:"- <b>On</b> — each link gets an empty line above it and stands apart\n- <b>Off</b> — links go one under another as a tight list\nThis applies wherever the link goes, under a heading too",
      visible: on("transform.inline2note.backlink.enabled") },
    { kind:"dropdown", id:"backlink-position", path:"transform.inline2note.backlink.placement.position", default:"end",
      name:"Where to put the link", desc:"At the top of that note, or after whatever is already there",
      searchTerms:["Where the backlink goes"],
      options:[ {value:"beginning",label:"Beginning"}, {value:"end",label:"End"},
                {value:"custom-header",label:"Under heading"} ],
      tip:"- <b>End</b> — keeps links in the order you filed them, which is best for a growing list\n- <b>Under heading</b> — puts each link at the end of the section you name below",
      visible: on("transform.inline2note.backlink.enabled") },
    { kind:"text", id:"backlink-target-header", clearable:true,
      path:"transform.inline2note.backlink.placement.targetHeader", default:"", mono:true,
      placeholder:"# Heading name",
      name:"Name of the heading", desc:"The heading the link is filed under",
      tip:"Type the heading as it appears in the note. With hashes, like <code>## Log</code>, only a heading of that level counts. Without them, any level does. Case does not matter. If the heading is missing, it is created at the level you set here (no hashes means level 1)",
      visible:{ deps:["transform.inline2note.backlink.enabled","transform.inline2note.backlink.placement.position"],
                test: c => Boolean(c.get("transform.inline2note.backlink.enabled"))
                  && String(c.get("transform.inline2note.backlink.placement.position") || "") === "custom-header" } },
    { kind:"dropdown", id:"backlink-header-missing", path:"transform.inline2note.backlink.placement.fallback",
      default:"end",
      name:"If heading not found", desc:"Where the heading is added when that note has none",
      options:[ {value:"beginning",label:"Beginning"}, {value:"end",label:"End"} ],
      tip:"If a note has no such heading, it is written for you here, exactly as you named it above, and the link goes under it. Later links find it and join the same section",
      visible:{ deps:["transform.inline2note.backlink.enabled","transform.inline2note.backlink.placement.position"],
                test: c => Boolean(c.get("transform.inline2note.backlink.enabled"))
                  && String(c.get("transform.inline2note.backlink.placement.position") || "") === "custom-header" } }
  ]
},
{
  id: "smart-rules", tab: "transform", order: 500, heading: "Smart Rules",
  intro: "Different kinds of line deserve different notes. A rule spots a kind of line and picks the template for it",
  tip: "Rules are checked from the top and the first match wins. Lines that match no rule get the default template. Put narrow rules above broad ones, or the broad rule will match first. Drag a rule by its handle to change the order",
  visible: on("transform.inline2note.enabled"),
  items: [
    { kind:"custom", id:"smart-rules-list", render: smartRules }
  ]
}
];
