/**
 * ВНИМАНИЕ: файл сгенерирован из docs/prototype/settings_prototype.html.
 * Руками не правится. Правится прототип, затем `npm run gen:schema`.
 *
 * Тексты согласованы заказчиком и совпадают с Приложением B PRD.
 */

import type { SettingsGroup } from "../types.ts";
import { on, eq } from "../types.ts";
import { callout } from "../custom/callouts.ts";
import { floatingButton, sourcePreview } from "../custom/previews.ts";
import { smartRules } from "../custom/smart_rules.ts";
import { sourceFields } from "../custom/source_fields.ts";

export const TRANSFORM_GROUPS: readonly SettingsGroup[] = [
{ id: "transform-intro", tab: "transform",  order: 50, heading: "Before you start",
  items: [
    { kind:"custom", id:"transform-callout", render: callout("transform") }
  ],
  visible: on("general.help.showCallouts") },
{
  id: "inline-to-note", tab: "transform", order: 100, heading: "Inline to note",
  tip: "One press of <code>Transform inline to note</code> turns your line into a note. It picks a name, writes your text into the note and tidies up your line. The groups below go in that order\n<code>- call Anna</code> → <code>- [[call Anna]] :: #processed</code>, and the new note <b>call Anna</b> holds your text\nNothing happens until <code>Inline to note</code> just below is on",
  intro: "Press a key and the line you wrote becomes a note of its own, or is added to a note you already have. If you want, the line keeps a link to that note",
  commands: ["Transform inline to note"],
  items: [
    { kind:"toggle", id:"i2n-enabled", path:"transform.inline2note.enabled", default:false,
      name:"Inline to note", desc:"Allow this to create notes and add to notes you already have",
      searchTerms:["Inline2Note enabled"],
      tip:"The main switch that lets the plugin write to your vault\n- <b>On</b> — <code>Transform inline to note</code> works: it can make a note, add to a note and edit your line\n- <b>Off</b> — the command only tells you it is switched off\nOne press can change a note and your line, so make a backup first" },
    { kind:"folder", id:"i2n-templates-folder", clearable:true, path:"transform.inline2note.templatesFolder", default:"",
      name:"Templates folder", desc:"The folder your note templates live in",
      placeholder:"Pick or type a folder",
      tip:"A template is a normal note that each new note starts as a copy of. Templates from this folder appear in the lists below\nInside a template, <code>{{title}}</code> becomes the note name and <code>{{date}}</code> the date of the press, such as <code>2026-08-21</code>\nPick a folder or type a new name: the folder is created the first time it is needed",
      visible: on("transform.inline2note.enabled") },
    { kind:"dropdown", id:"i2n-default-template", path:"transform.inline2note.defaultTemplate", default:"",
      name:"Default template", desc:"The template on creation of new note when no special rules apply (see <code>Smart Rules</code> below)",
      tip:"Smart Rules below can pick a different template for certain lines. This one covers everything else. The list shows only notes from <code>Templates folder</code>, so set that first",
      visible: on("transform.inline2note.enabled"),
      /* Только заметки из назначенной папки (1.6.2.4). Постоянных строк
         нет: что показать, когда папки нет, решает сам источник. */
      options:[], optionsFrom:"templates" },
    { kind:"folder", id:"i2n-output-folder", clearable:true, path:"transform.inline2note.outputFolder", default:"",
      name:"New notes folder", desc:"Where to put the notes this creates. Leave it empty to keep them next to the note you are in",
      placeholder:"Next to the current note",
      tip:"Where new notes go\n- <b>Empty</b> — next to the note you are in\n- <b>Inbox</b> — into that folder: <code>- call Anna</code> → <code>- [[Inbox/call Anna]]</code>\nA new folder name is fine too: the folder is created with the first note",
      searchTerms:["Output folder for new notes"], visible: on("transform.inline2note.enabled") },
    { kind:"toggle", id:"i2n-floating", path:"transform.inline2note.floatingButton", default:false,
      name:"Floating button", desc:"Put a small button at the end of the line you are on",
      searchTerms:["Flying button"],
      visible: on("transform.inline2note.enabled"),
      tip:"- <b>On</b> — a small button sits at the end of the line you are on. Clicking it does the same as <code>Transform inline to note</code>\n- <b>Off</b> — no button: use the command or its hotkey\nThe button only shows on screen and is never saved into your note",
      seeAlso:{ id:"i2n-button-preview", label:"See where it appears" } },
    { kind:"slider", id:"i2n-floating-gap", path:"transform.inline2note.floatingButtonGap", default:12,
      min:0, max:40, step:1, unit:"px",
      name:"Distance from the text", desc:"How much room to leave between the line and the button",
      searchTerms:["Floating button gap","Button offset"],
      visible:{ deps:["transform.inline2note.enabled","transform.inline2note.floatingButton"],
                test: c => Boolean(c.get("transform.inline2note.enabled") && c.get("transform.inline2note.floatingButton")) },
      tip:"Room between the end of the line and the button\n- <b>0</b> — the button touches the last letter\n- <b>40</b> — the widest gap\nOn a short line, a bigger gap keeps the button from looking like part of the text",
      seeAlso:{ id:"i2n-button-preview", label:"The preview below moves with it" } },
    { kind:"custom", id:"i2n-button-preview", render: floatingButton,
      visible:{ deps:["transform.inline2note.enabled","transform.inline2note.floatingButton"],
                test: c => Boolean(c.get("transform.inline2note.enabled") && c.get("transform.inline2note.floatingButton")) } },
    { kind:"toggle", id:"content-open", path:"transform.inline2note.openTarget", default:false,
      name:"Open note after creation", desc:"Jump straight to the note once it is written",
      tip:"- <b>On</b> — the new note opens in a new tab, so you can check the result\n- <b>Off</b> — you stay on your line, and a short message names the new note\nKeep it on while you set things up, then turn it off once you trust it",
      searchTerms:["Open transformed note", "Open the note afterwards"],
      visible: on("transform.inline2note.enabled") }
  ]
},
{
  id: "naming", tab: "transform", order: 200, heading: "New note naming",
  intro: "Every new note needs a name. Here you choose where that name comes from",
  tip: "The name comes from the first of these that the line has:\n- <b>Brackets</b> — <code>- call [Anna] today</code> → note <b>Anna</b>\n- <b>Heading</b> — <code>## Weekly report</code> → note <b>Weekly report</b>\n- <b>First words</b> — <code>- call Anna today</code> → note <b>call Anna today</b>",
  visible: on("transform.inline2note.enabled"),
  items: [
    { kind:"dropdown", id:"naming-mode", path:"transform.inline2note.noteName.mode", default:"auto",
      name:"Note name", desc:"Take the name from the line, or stop and ask you for it",
      tip:"- <b>From line</b> — names the note at once, from brackets, a heading or the first words\n- <b>Ask</b> — opens a small box first. Type a name and press <code>Enter</code>, or press <code>Escape</code> to cancel and leave the line as it was",
      searchTerms:["Note name mode"],
      options:[ {value:"auto",label:"From line"}, {value:"manual",label:"Ask"} ] },
    { kind:"text", id:"naming-delimiters", path:"transform.inline2note.noteName.delimiters", default:"[]", mono:true,
      name:"Name brackets", desc:"Two characters. Whatever you put between them becomes the name",
      searchTerms:["Title delimiters", "Explicit name delimiters", "Name brackets"],
      tip:"Two characters: one opens the name, one closes it. The name leaves the text that goes into the note\n- <b>[]</b> — <code>- call [Anna] today</code> → note <b>Anna</b> with the text <code>- call today</code>\n- <b>()</b> — <code>- call (Anna about the contract) today</code> → note <b>Anna about the contract</b>\nLeft empty, it works as <code>[]</code>" },
    { kind:"number", id:"naming-word-count", path:"transform.inline2note.noteName.wordCount", default:6, min:1, max:20,
      name:"Words to use instead", desc:"How many of the first words to use when there are no brackets",
      searchTerms:["Auto title word count"],
      tip:"Used when the line has no brackets and no heading\n- <b>3</b> — <code>- draft the settings prototype today</code> → note <b>draft the settings</b>\n- <b>6</b> — the same line → note <b>draft the settings prototype today</b>\nFew words make names that look alike. Many words make long names" },
    { kind:"dropdown", id:"naming-collision", path:"transform.inline2note.nameCollision.mode", default:"new_note",
      name:"If the name already taken", desc:"What to do when you already have a note with that name",
      searchTerms:["Name collision mode", "If the name is taken"],
      options:[ {value:"new_note",label:"New note"}, {value:"add_to_note",label:"Add to existing"},
                {value:"overwrite",label:"Overwrite"} ],
      tip:"What happens when the note <b>call Anna</b> already exists and you press on <code>- call Anna</code>:\n- <b>New note</b> — keeps the old note and makes <b>call Anna-01</b>, next time <b>call Anna-02</b>: <code>- call Anna</code> → <code>- [[call Anna-01]]</code>\n- <b>Add to existing</b> — adds your text to <b>call Anna</b>, where <code>Where to put the text</code> says. Good for a running log\n- <b>Overwrite</b> — replaces everything in <b>call Anna</b> with your text. The plugin cannot bring the old text back" }
  ]
},
{
  id: "note-content", tab: "transform", order: 300, heading: "Note content",
  intro: "What the new note looks like inside: where your text goes and what sits above it",
  tip: "Two choices here: where your text lands in the note, and what line goes above it to keep entries apart. With the usual settings a new note gets:\n<code>### 2026-08-21 09:05</code>\n<code>- call Anna</code>\nThe rest of the note comes from the template you chose above",
  visible: on("transform.inline2note.enabled"),
  items: [
    { kind:"dropdown", id:"content-position", path:"transform.inline2note.placement.position", default:"end",
      name:"Where to put the text", desc:"At the top of the note, or after whatever is already there",
      searchTerms:["Where to place inline text?"],
      options:[ {value:"beginning",label:"Beginning"}, {value:"end",label:"End"},
                {value:"custom-header",label:"Under heading"} ],
      tip:"Matters when the note already has text, from a template or from earlier entries. Say it holds <code>old entry</code> and you add <code>- call Anna</code>:\n- <b>Beginning</b> — <code>- call Anna</code> goes above <code>old entry</code>\n- <b>End</b> — it goes below, so entries keep the order you wrote them\n- <b>Under heading</b> — it goes to the end of the section you name below, such as <code>## Log</code>" },
    { kind:"text", id:"content-target-header", clearable:true, path:"transform.inline2note.placement.targetHeader",
      default:"", mono:true, placeholder:"# Heading name",
      name:"Name of the heading", desc:"The heading your text is filed under",
      tip:"Type the heading as it is in the note. Case does not matter, and if two match, the first one is used\n- <code>## Log</code> — only a level 2 heading <code>Log</code> counts\n- <code>Log</code> — a heading <code>Log</code> of any level counts\nIf the note has no such heading, it gets one: <code>## Log</code> stays as typed, and <code>Log</code> becomes <code># Log</code>",
      visible: eq("transform.inline2note.placement.position","custom-header") },
    { kind:"dropdown", id:"content-header-missing", path:"transform.inline2note.placement.fallback",
      default:"end",
      name:"If heading not found", desc:"Where the heading is added when the note has none",
      options:[ {value:"beginning",label:"Beginning"}, {value:"end",label:"End"} ],
      tip:"When the note has no heading by that name, the plugin writes it for you, with your text under it:\n- <b>Beginning</b> — at the top of the note\n- <b>End</b> — at the bottom: <code>old entry</code>, then <code>## Log</code> and <code>- call Anna</code>\nLater entries find that heading and join its section",
      visible: eq("transform.inline2note.placement.position","custom-header") },
    { kind:"dropdown", id:"content-header-mode", path:"transform.inline2note.placement.headerMode", default:"datetime",
      name:"Line above the text", desc:"Something to put above your text so entries stay apart",
      tip:"The line written above each entry, so entries do not run together:\n- <b>Fixed text</b> — your own words, such as <code>### Call</code>\n- <b>Date and time</b> — the moment you pressed, such as <code>### 2026-08-21 09:05</code>\n- <b>None</b> — no line, the entry follows the one before it\nWhether that line is a heading is set in the row below",
      searchTerms:["Inserted block header"],
      options:[ {value:"custom",label:"Fixed text"}, {value:"datetime",label:"Date and time"},
                {value:"none",label:"None"} ] },
    { kind:"dropdown", id:"content-header-level", path:"transform.inline2note.placement.headerLevel", default:"3",
      name:"Line above is a heading", desc:"Make that line a heading you can fold, or leave it as plain text",
      tip:"- <b>Plain text</b> — <code>2026-08-21 09:05</code>, a plain line\n- <b>1</b> to <b>6</b> — a heading of that level: <b>3</b> gives <code>### 2026-08-21 09:05</code>\nA heading folds and shows in the outline. <code>1</code> is the biggest. This row adds the hashes, so you do not type them",
      visible:{ deps:["transform.inline2note.placement.headerMode"],
                test: c => String(c.get("transform.inline2note.placement.headerMode") || "") !== "none" },
      options:[ {value:"0",label:"Plain text"}, {value:"1",label:"1"}, {value:"2",label:"2"},
                {value:"3",label:"3"}, {value:"4",label:"4"}, {value:"5",label:"5"}, {value:"6",label:"6"} ] },
    { kind:"text", id:"content-header-text", clearable:true, path:"transform.inline2note.placement.customHeader", default:"Captured", mono:true,
      name:"Text of the line above", desc:"Typed into the note exactly as you write it here",
      tip:"Type only the words. The hashes come from <code>Line above is a heading</code>\n- <code>Call</code> with <b>3</b> there — <code>### Call</code>\n- <code>## Call</code> with <b>3</b> there — still <code>### Call</code>, because hashes typed here are removed",
      visible: eq("transform.inline2note.placement.headerMode","custom") },
    { kind:"text", id:"content-datetime", clearable:true, path:"transform.inline2note.placement.datetimeFormat", default:"YYYY-MM-DD HH:mm", mono:true,
      name:"Date format", desc:"Today\u2019s date, written the way you set out here",
      searchTerms:["Datetime header format"],
      visible: eq("transform.inline2note.placement.headerMode","datetime"),
      tip:"Letters stand for parts of the date. Everything else stays as you typed it\n- <code>YYYY</code>, <code>YY</code> — the year, or its last two digits\n- <code>MM</code>, <code>DD</code> — the month, the day\n- <code>HH</code>, <code>mm</code>, <code>ss</code> — the hour, the minute, the second\n<code>DD.MM.YYYY HH:mm</code> → <code>21.08.2026 09:05</code>" }
  ]
},
{
  id: "source-line", tab: "transform", order: 400, heading: "Source line",
  intro: "What happens to the line you pressed on, after the note is safely saved",
  tip: "Your line changes only after the note is saved, so nothing is lost if saving fails. With the usual settings:\n<code>- call Anna</code> → <code>- [[call Anna]] :: #processed</code>\nThe link and the mark are both optional. With both off and the text kept, the line looks untouched, and a second press files it twice",
  visible: on("transform.inline2note.enabled"),
  items: [
    { kind:"custom", id:"source-preview", render: sourcePreview },
    { kind:"dropdown", id:"content-sublines", path:"transform.inline2note.sublines", default:"stay",
      name:"Sub-lines (tree) behavior", desc:"Leave them where they are, or take them into the note too",
      tip:"Say <code>- call Anna</code> has two sub-points under it, <code>- ask about the price</code> and <code>- send the contract</code>. The note gets all three lines either way\n- <b>Keep</b> — the sub-points stay here, under <code>- [[call Anna]]</code>\n- <b>Move</b> — they leave, and only <code>- [[call Anna]]</code> stays here",
      searchTerms:["Sublines behavior"],
      options:[ {value:"stay",label:"Keep"}, {value:"remove",label:"Move"} ],
      visible: on("transform.inline2note.enabled") },
    { kind:"dropdown", id:"source-text", path:"transform.inline2note.sourceProcessing.text", default:"remove",
      name:"What happens with current line", desc:"The text goes into the note either way \u2014 this is about the line you pressed on",
      searchTerms:["What happens to your text"],
      options:[ {value:"remove",label:"Remove"}, {value:"leave",label:"Keep"},
                {value:"leave_named",label:"Keep without name"},
                {value:"words",label:"Keep first words"} ],
      tip:"Your text goes into the note either way. Say the line is <code>- call Anna about the contract</code> and the note is named <b>call Anna</b>:\n- <b>Remove</b> — <code>- [[call Anna]]</code>\n- <b>Keep</b> — <code>- call Anna about the contract [[call Anna]]</code>\n- <b>Keep without name</b> — <code>- [[call Anna]] about the contract</code>\n- <b>Keep first words</b> — with <b>2</b> in <code>Words to keep</code>: <code>- [[call Anna]] about the</code>",
      visible: on("transform.inline2note.enabled") },
    { kind:"number", id:"source-keep-words", path:"transform.inline2note.sourceProcessing.keepWords", default:3, min:1, max:20,
      name:"Words to keep", desc:"How much of the line stays behind",
      tip:"How many words stay after the link. The words that became the note name do not count, since the link takes their place. With the note <b>call Anna</b> from <code>- call Anna about the contract</code>:\n- <b>1</b> — <code>- [[call Anna]] about</code>\n- <b>2</b> — <code>- [[call Anna]] about the</code>\nThe rest moves into the note",
      visible: eq("transform.inline2note.sourceProcessing.text","words") },
    { kind:"note", id:"source-fields-head",
      name:"Fields to keep", desc:"Which Fields stay on the line you pressed on",
      tip:"Ticked Fields stay on the line. The rest leave with the text. The note always gets the whole line. With <code>- [ ] #todo :: call Anna</code> and the mark <code>#moved</code>:\n- <b>Type ticked</b> — <code>- [ ] #todo :: [[call Anna]] :: #moved</code>\n- <b>Nothing ticked</b> — <code>- [[call Anna]] :: #moved</code>",
      visible: on("transform.inline2note.enabled") },
    { kind:"custom", id:"source-fields", render: sourceFields,
      visible: on("transform.inline2note.enabled") },
    { kind:"toggle", id:"source-keep-sub", path:"transform.inline2note.sourceProcessing.keepSubFields", default:false,
      name:"Keep sub-fields",
      desc:"A Field you keep keeps its child Values on the line too",
      tip:"Child Fields have no row of their own in the list above. They follow their parent:\n- <b>Off</b> — the kept Field stays on the line and its child Values go into the note\n- <b>On</b> — they stay on the line too, and a copy still goes into the note",
      visible: on("transform.inline2note.enabled") },
    { kind:"toggle", id:"source-link", path:"transform.inline2note.sourceProcessing.replaceWithLink", default:true,
      name:"Insert wikilink in current line", desc:"Put a link to the new note on the line you pressed on",
      searchTerms:["Replace payload with note link", "Leave a link behind"],
      tip:"Examples with <b>Remove</b> above:\n- <b>On</b> — <code>- call Anna</code> → <code>- [[call Anna]]</code>. Click the link to open the note\n- <b>Off</b> — <code>- call Anna</code> → <code>-</code>, and nothing shows where the text went\nThe mark below tells you the line is done, link or not" },
    { kind:"text", id:"source-marker", clearable:true, path:"transform.inline2note.sourceProcessing.token", default:"#processed", mono:true,
      name:"Mark transformed line", desc:"A word or tag added to the line so you can see it has been handled",
      searchTerms:["Processed token", "Mark the line as done"],
      tip:"A word or tag added to the line once it is a note. Search for it to find everything you filed, or hide those lines from a to-do list\n- <code>#moved</code> — <code>- call Anna</code> → <code>- [[call Anna]] :: #moved</code>\n- <b>Empty</b> — nothing is added\nA line with the mark is never filed twice: a second press only shows a message" },
    { kind:"dropdown", id:"source-marker-position", path:"transform.inline2note.sourceProcessing.panel", default:"right",
      name:"Where the mark goes", desc:"Before your text, or after it",
      tip:"From <code>- call Anna</code>:\n- <b>Left Block</b> — <code>- #moved :: [[call Anna]]</code>, next to the tags\n- <b>Right Block</b> — <code>- [[call Anna]] :: #moved</code>, after your text\nPick whichever reads better to you",
      searchTerms:["Processed token panel"],
      visible:{ deps:["transform.inline2note.sourceProcessing.token"],
                test: c => String(c.get("transform.inline2note.sourceProcessing.token") || "").trim() !== "" },
      options:[ {value:"left",label:"Left Block"}, {value:"right",label:"Right Block"} ] },
    { kind:"toggle", id:"source-dim", path:"transform.inline2note.sourceProcessing.visual.enabled", default:false,
      name:"Dim transformed line", desc:"Fade a line once it carries the mark above, so your eye skips it",
      searchTerms:["Dim the lines already filed"],
      visible:{ deps:["transform.inline2note.sourceProcessing.token"],
                test: c => String(c.get("transform.inline2note.sourceProcessing.token") || "").trim() !== "" },
      tip:"- <b>On</b> — lines with the mark fade, such as <code>- [[call Anna]] :: #processed</code>, so your eye skips them\n- <b>Off</b> — they look like any other line\nOnly the look changes: the text stays and search finds it. Remove the mark by hand, and the line looks normal again" },
    { kind:"slider", id:"source-dim-opacity", path:"transform.inline2note.sourceProcessing.visual.opacity", default:65,
      min:0, max:80, step:5, unit:"%", invert:100,
      name:"Opacity of transformed line", desc:"Zero leaves the line as it is, eighty makes it barely readable",
      searchTerms:["How much is left"],
      tip:"How much a marked line fades\n- <b>0</b> — no fade at all\n- <b>80</b> — barely readable\nOnly the look changes: search still finds the line and <code>Undo</code> still works. Use the least fade that lets your eye skip it",
      visible:{ deps:["transform.inline2note.sourceProcessing.token","transform.inline2note.sourceProcessing.visual.enabled"],
                test: c => String(c.get("transform.inline2note.sourceProcessing.token") || "").trim() !== ""
                  && Boolean(c.get("transform.inline2note.sourceProcessing.visual.enabled")) } },
    { kind:"color", id:"source-dim-color", path:"transform.inline2note.sourceProcessing.visual.color", default:"",
      name:"Color of transformed line", desc:"Leave it unset to keep the color your theme gives the text",
      allowReset:true,
      searchTerms:["Color of a filed line"],
      tip:"- <b>Unset</b> — the line keeps the text color of your theme and only fades\n- <b>Set</b> — the line takes your color, and the fade above still applies\nSet it only if fading alone does not make finished lines easy to spot",
      visible:{ deps:["transform.inline2note.sourceProcessing.token","transform.inline2note.sourceProcessing.visual.enabled"],
                test: c => String(c.get("transform.inline2note.sourceProcessing.token") || "").trim() !== ""
                  && Boolean(c.get("transform.inline2note.sourceProcessing.visual.enabled")) } }
  ]
},
{
  id: "backlinks", tab: "transform", order: 450, heading: "Auto-MOC in your links",
  intro: "When a line links to other notes, each of them can get a link back to the new note",
  tip: "A line often links to the notes it belongs to: a project, a person, a place. With this on, each of them gets a link to the new note, so a project note slowly lists everything filed under it\n<code>- [ ] #todo [[Anna]] :: call about the price</code> → the note <b>Anna</b> gets <code>- [[call about the price]]</code>\nOnly links that are a Value of a Field count. A link in your sentence, like <code>call [[Bob]]</code>, is left alone",
  visible: on("transform.inline2note.enabled"),
  items: [
    { kind:"toggle", id:"backlink-enabled", path:"transform.inline2note.backlink.enabled", default:false,
      name:"Link the notes you mention",
      desc:"Write a link to the new note into the notes of the link Values on this line",
      searchTerms:["Create wikilink to transformed note in reference notes","Backlinks into the notes you mention","Automatic MOC"],
      tip:"- <b>On</b> — each note this line links to as a Value gets a link to the new note, such as <code>- [[call about the price]]</code>\n- <b>Off</b> — no other note is touched\nThe link uses the full path, so it finds the right note when two share a name. Only notes that exist get it, and a note that already links there is skipped" },
    { kind:"toggle", id:"backlink-navigator", path:"transform.inline2note.backlink.navigator", default:false,
      name:"Link to Navigator",
      desc:"Also write the link into the navigator note of a child link",
      tip:"Normally a child link’s navigator gets nothing. With this on, the navigator note gets the link too, and a child under two navigators gets links from both. A missing navigator note is created empty. A Tag navigator is not a note, so nothing is written for it",
      visible: on("transform.inline2note.backlink.enabled") },
    { kind:"toggle", id:"backlink-empty-line", path:"transform.inline2note.backlink.emptyLine", default:true,
      name:"Add empty line before wikilink",
      desc:"Keep a blank line between the links written into a note",
      tip:"- <b>On</b> — an empty line between links: <code>- [[old note]]</code>, empty line, <code>- [[new note]]</code>\n- <b>Off</b> — links stand one under another as a tight list\nThis applies wherever the link goes, under a heading too",
      visible: on("transform.inline2note.backlink.enabled") },
    { kind:"dropdown", id:"backlink-position", path:"transform.inline2note.backlink.placement.position", default:"end",
      name:"Where to put the link", desc:"At the top of that note, or after whatever is already there",
      searchTerms:["Where the backlink goes"],
      options:[ {value:"beginning",label:"Beginning"}, {value:"end",label:"End"},
                {value:"custom-header",label:"Under heading"} ],
      tip:"Say the note <b>Anna</b> already lists <code>- [[old note]]</code>:\n- <b>Beginning</b> — the new link goes above it, below the note properties\n- <b>End</b> — it goes below, so links keep the order you filed them\n- <b>Under heading</b> — it goes to the end of the section you name below, such as <code>## Calls</code>",
      visible: on("transform.inline2note.backlink.enabled") },
    { kind:"text", id:"backlink-target-header", clearable:true,
      path:"transform.inline2note.backlink.placement.targetHeader", default:"", mono:true,
      placeholder:"# Heading name",
      name:"Name of the heading", desc:"The heading the link is filed under",
      tip:"Type the heading as it is in the note. Case does not matter\n- <code>## Calls</code> — only a level 2 heading <code>Calls</code> counts\n- <code>Calls</code> — a heading <code>Calls</code> of any level counts\nIf the note has no such heading, it gets one: <code>## Calls</code> stays as typed, and <code>Calls</code> becomes <code># Calls</code>",
      visible:{ deps:["transform.inline2note.backlink.enabled","transform.inline2note.backlink.placement.position"],
                test: c => Boolean(c.get("transform.inline2note.backlink.enabled"))
                  && String(c.get("transform.inline2note.backlink.placement.position") || "") === "custom-header" } },
    { kind:"dropdown", id:"backlink-header-missing", path:"transform.inline2note.backlink.placement.fallback",
      default:"end",
      name:"If heading not found", desc:"Where the heading is added when that note has none",
      options:[ {value:"beginning",label:"Beginning"}, {value:"end",label:"End"} ],
      tip:"When a note has no heading by that name, the plugin writes it for you, with the link under it:\n- <b>Beginning</b> — at the top of the note\n- <b>End</b> — at the bottom: <code>## Calls</code>, then <code>- [[call about the price]]</code>\nLater links find that heading and join its section",
      visible:{ deps:["transform.inline2note.backlink.enabled","transform.inline2note.backlink.placement.position"],
                test: c => Boolean(c.get("transform.inline2note.backlink.enabled"))
                  && String(c.get("transform.inline2note.backlink.placement.position") || "") === "custom-header" } }
  ]
},
{
  id: "smart-rules", tab: "transform", order: 500, heading: "Smart Rules",
  intro: "Different kinds of line deserve different notes. A rule spots a kind of line and picks the template for it",
  tip: "Rules are checked from the top and the first match wins. Lines that match no rule get the default template. Put narrow rules above broad ones, or the broad rule will match first. Drag a rule by its handle to change the order",
  visible: on("transform.inline2note.enabled"),
  items: [
    { kind:"custom", id:"smart-rules-list", render: smartRules }
  ]
}
];
