/**
 * ВНИМАНИЕ: файл сгенерирован из docs/prototype/settings_prototype.html.
 * Руками не правится. Правится прототип, затем `npm run gen:schema`.
 *
 * Тексты согласованы заказчиком и совпадают с Приложением B PRD.
 */

import type { SettingsGroup } from "../types.ts";
import { on } from "../types.ts";
import { callout } from "../custom/callouts.ts";
import { barsPreview, caretPreview, jumpFlashPreview, linkPreview, tagPreview, wheelPreview } from "../custom/previews.ts";
import { subheader } from "../custom/subheader.ts";
import { userTagColors } from "../custom/user_tags.ts";

export const VISUAL_GROUPS: readonly SettingsGroup[] = [
{ id: "visual-intro",    tab: "visual",     order: 50, heading: "Before you start",
  items: [
    { kind:"custom", id:"visual-callout", render: callout("visual") }
  ],
  visible: on("general.help.showCallouts") },
{
  id: "tag-appearance", tab: "visual", order: 100, heading: "Inline appearance",
  intro: "Makes tagged lines easier to read: tags become small colored bubbles, and links and dates stay ordinary text. Your file stays exactly the same",
  tip: "The <b>opacity</b> rows fade the tags, dates and links on each side so your own text stands out. <b>Line view</b> sets how big they are and adds a colored Stripe behind them. <b>Tag view</b> shapes the tag bubble. You set the colors of single Values on each Field, on the <code>Tags & PKM</code> tab",
  items: [
    { kind:"custom", id:"tag-preview", render: tagPreview },
    { kind:"custom", id:"line-view-sub", render: subheader("Line view",
        "These rows change the tags, dates and links before and after your text: how faded they are, how big they are, and whether a colored Stripe runs behind them. Your own text between the Separators never changes") },
    { kind:"slider", id:"tags-opacity-left", path:"visual.tags.opacityLeft", default:100,
      min:0, max:100, step:1, unit:"%",
      name:"Opacity of the Left Block", desc:"Dims everything written before your text, tags and elements alike",
      tip:"Faded is not hidden. Even at 0 the Left Block is still on the line, still searchable and still moved by the commands. Tip: turn it down a little so your sentence comes first",
      searchTerms:["Opacity Left"],
      seeAlso:{ id:"field-editor", label:"Tag colors are set per Value under Fields" } },
    { kind:"slider", id:"tags-opacity-right", path:"visual.tags.opacityRight", default:100,
      min:0, max:100, step:1, unit:"%",
      name:"Opacity of the Right Block", desc:"Dims everything written after your text, tags and elements alike",
      tip:"This is separate from the left side because dates and links after your text usually need less attention than the tags before it. Even at 0 everything is still there and still works",
      searchTerms:["Opacity Right"] },
    { kind:"slider", id:"tags-text-size-left", path:"visual.tags.textSizePctLeft", default:100,
      min:50, max:140, step:5, unit:"%",
      name:"Left Block text size", desc:"How big everything before your text is written, next to the rest of your note",
      tip:"Tags, dates and links all change size together. Your own text keeps its size. Below 100 the Block steps back and your sentence leads. Above 100 the Block competes with it",
      searchTerms:["Tag text size", "Text size Left"] },
    { kind:"slider", id:"tags-text-size-right", path:"visual.tags.textSizePctRight", default:100,
      min:50, max:140, step:5, unit:"%",
      name:"Right Block text size", desc:"How big everything after your text is written, next to the rest of your note",
      tip:"This is separate from the left side because dates and links after your text often read better a size smaller, while the tags before it stay as they are. Your own text keeps its size either way",
      searchTerms:["Tag text size", "Text size Right"] },
    { kind:"toggle", id:"tags-block-fill", path:"visual.tags.blockFill.enabled", default:false,
      /* Имя его словами (З-13, 2026-09-19): «измени названия
         контролов: tags-block-fill на `Color the Block with Stripe`…» — и оно
         стоит в панели дословно: ровно пять слов, предел имени
         соблюдён. Прежняя подпись `Color the Blocks` была моим
         компромиссом вместо его же `Color Left\\Right blocks`, и новое слово
         сильнее старого; старая осталась в `searchTerms`, чтобы поиск
         панели её находил. */
      name:"Color the Block with Stripe", desc:"A Stripe behind the Left Block and the Right Block, so the two stand out from your text",
      searchTerms:["Block background", "Color the Blocks"],
      tip:"The Stripe runs from the first Value of a Block to the last one. Your own text and empty Blocks get no Stripe, and everything on the line stays clickable. A single tag bubble can hide the Stripe, so raise <code>Stripe height</code> or <code>Stripe width</code> to make it show" },
    { kind:"dropdown", id:"tags-block-fill-direction", path:"visual.tags.blockFill.direction", default:"both",
      name:"Stripe direction", desc:"Which of the two Blocks gets a Stripe",
      tip:"<code>Both</code> is the usual choice. Pick <code>Left</code> or <code>Right</code> when you read one side and the other side is just bookkeeping. Empty Blocks and your own text never get a Stripe",
      options:[ {value:"left",label:"Left"}, {value:"right",label:"Right"}, {value:"both",label:"Both"} ],
      visible: on("visual.tags.blockFill.enabled") },
    { kind:"color", id:"tags-block-fill-color", path:"visual.tags.blockFill.color", default:"",
      name:"Stripe color", desc:"Leave it unset and the Stripe follows your theme",
      searchTerms:["Block color"],
      tip:"Unset uses your theme’s accent color, so the Stripe still fits when you switch themes. Pick a color only if you want a specific one",
      visible: on("visual.tags.blockFill.enabled") },
    { kind:"slider", id:"tags-block-fill-opacity", path:"visual.tags.blockFill.opacity", default:12,
      min:0, max:100, step:1, unit:"%",
      name:"Stripe opacity", desc:"How strongly the Stripe shows through",
      searchTerms:["Block color strength"],
      tip:"Keep it low: the Stripe should catch your eye without covering the writing. Around a tenth is enough to see where a Block starts and ends",
      visible: on("visual.tags.blockFill.enabled") },
    { kind:"slider", id:"tags-block-fill-height", path:"visual.tags.blockFill.heightPct", default:60,
      min:0, max:100, step:20, unit:"%",
      name:"Stripe height", desc:"How far the Stripe reaches above and below the writing",
      searchTerms:["Band height"],
      tip:"At <code>0</code> the Stripe is exactly as tall as the writing, so a single tag bubble can hide it. At <code>100</code> it fills the whole line, and the Stripes of neighboring lines meet without overlapping. Every step in between changes the Stripe on any theme",
      visible: on("visual.tags.blockFill.enabled") },
    { kind:"slider", id:"tags-block-fill-width", path:"visual.tags.blockFill.widthPct", default:50,
      min:0, max:100, step:5, unit:"%",
      name:"Stripe width", desc:"How far the Stripe reaches past the Block on both of its sides",
      searchTerms:["Band width"],
      tip:"At <code>0</code> the Stripe covers only the Values. At <code>50</code> it reaches the Separator next to your text. At <code>100</code> it covers the Separator too. On the Left Block it never covers the bullet or the checkbox",
      visible: on("visual.tags.blockFill.enabled") },
    { kind:"custom", id:"tag-view-sub", render: subheader("Tag view",
        "These rows shape only the tag bubble: the space around the word, how tall the bubble is and how round its corners are. Dates and links have no bubble, so these rows don’t change them") },
    { kind:"slider", id:"tags-bubble-width", path:"visual.tags.bubbleWidthPct", default:100,
      min:20, max:140, step:5, unit:"%",
      name:"Tag bubble width", desc:"How much breathing room there is either side of the word",
      tip:"The word keeps its size, and only the bubble around it grows. Turned down, the word sits almost at the edge of the bubble. Above 100, tags look like separate chips even in a crowded Block",
      searchTerms:["Tag bubble size - width", "Bubble width"] },
    { kind:"slider", id:"tags-bubble-height", path:"visual.tags.bubbleHeightPct", default:100,
      min:20, max:140, step:5, unit:"%",
      name:"Tag bubble height", desc:"How tall the bubble is around the word",
      tip:"Keep it modest: tall bubbles push the lines of your note apart and make the page harder to read. Turned down, the bubble hugs the word above and below",
      searchTerms:["Tag bubble size - height", "Bubble height"] },
    { kind:"slider", id:"tags-corners", path:"visual.tags.cornersPct", default:0,
      min:0, max:100, step:1,
      name:"Tag bubble corners", desc:"Slide from fully rounded to completely square",
      tip:"At 0 the bubble is a pill, and at 100 it is a rectangle. The color, padding and text size stay the same. Square corners look denser and go well with narrow bubbles",
      searchTerms:["Tag shape", "Bubble corners"] },
    { kind:"slider", id:"tags-empty-bubble", path:"visual.tags.emptyBubblePct", default:100,
      min:10, max:180, step:5, unit:"%",
      name:"Empty tag bubble width", desc:"Width of a bubble whose <code>Show</code> is set to <code>empty</code>",
      searchTerms:["Empty bubble size", "Empty bubble width"],
      tip:"Under <code>Fields</code> you can set a Value to <code>empty</code>. It then shows its color but no text, like a marker. This row sets how wide that marker is",
      seeAlso:{ id:"field-editor", label:"Set a Value to empty under Fields" } },
    { kind:"custom", id:"link-view-sub", render: subheader("Link view",
        "These rows are for link Values shown as your own text (<code>Show</code> = <code>custom</code>) instead of <code>[[the note name]]</code>. A click always opens the note. The two rows below bring back the hover preview and the dragging that ordinary links have") },
    { kind:"toggle", id:"link-hover-preview", path:"visual.tags.linkShown.hoverPreview", default:false,
      name:"Preview on hover", desc:"Hovering a Value shown as your own text opens the page preview — hold <code>Ctrl</code> while hovering",
      tip:"This works like Obsidian’s own <code>Page preview</code>: hold <code>Ctrl</code> (<code>Cmd</code> on macOS) while you hover. To open the preview by hovering alone, turn off the modifier key for <code>Page preview → Source mode</code>. Off by default, because a preview popping up over the line you are writing can get in the way",
      searchTerms:["Link hover preview", "Custom link preview"] },
    { kind:"toggle", id:"link-draggable", path:"visual.tags.linkShown.draggable", default:false,
      name:"Drag to move", desc:"Drag a Value shown as your own text into another note",
      tip:"Drop the Value into another note and you get a link to the same note, just like with an ordinary link. Off by default because it is easy to grab by accident. While it is on, pressing the Value starts a drag instead of placing the cursor",
      searchTerms:["Link drag", "Custom link drag"] },
    { kind:"color", id:"link-target-color", path:"visual.tags.linkAsWritten.targetColor", default:"",
      name:"Link target color", desc:"What you read in a wikilink: the name between <code>[[</code> and <code>]]</code>",
      searchTerms:["Link color", "Wikilink color", "Link text color"],
      tip:"Colors the note name in a wikilink, which is a link Value with <code>Show</code> = <code>default</code>. Hyperlinks have their own rows below. Leave it empty to keep your theme’s link color",
      allowReset:true },
    { kind:"color", id:"link-brackets-color", path:"visual.tags.linkAsWritten.bracketsColor", default:"",
      name:"Link brackets color", desc:"The markup around it: <code>[[</code> and <code>]]</code>",
      searchTerms:["Bracket color", "Wikilink brackets"],
      tip:"Colors <code>[[</code> and <code>]]</code> differently from the name. You see it in the previews here and on the line your cursor is on. Everywhere else Obsidian hides the brackets, so there is nothing to color. Leave it empty to keep your theme’s color",
      allowReset:true },
    { kind:"color", id:"hyperlink-target-color", path:"visual.tags.hyperlink.targetColor", default:"",
      name:"Hyperlink target color", desc:"The text you read in a Markdown link — what stands between the square brackets",
      searchTerms:["Hyperlink color", "External link color", "URL color"],
      tip:"Colors the text in <code>[a link](an address)</code>. Addresses use <code>Hyperlink address color</code> below. This works in every note. Links inside backticks and images are not changed. Leave it empty to keep your theme’s link color",
      allowReset:true },
    { kind:"color", id:"hyperlink-brackets-color", path:"visual.tags.hyperlink.bracketsColor", default:"",
      name:"Hyperlink brackets color", desc:"The markup around it: the square brackets and the round ones, without the address",
      searchTerms:["Hyperlink brackets", "URL markup color", "Address color"],
      tip:"Colors only <code>[</code>, <code>](</code> and <code>)</code>. The address has its own row below. You see it in the preview and on the line your cursor is on. Everywhere else Obsidian hides the brackets. Leave it empty to keep your theme’s color",
      allowReset:true },
    { kind:"color", id:"hyperlink-address-color", path:"visual.tags.hyperlink.addressColor", default:"",
      name:"Hyperlink address color", desc:"The address itself — inside the round brackets, or written on its own",
      searchTerms:["Address color", "URL color", "Link href color"],
      tip:"Colors every address, both inside <code>[a link](an address)</code> and on its own, like <code>https://…</code> or <code>www.…</code>. An address on its own is always colored. An address inside brackets is colored only on the line your cursor is on. Leave it empty to keep your theme’s color",
      allowReset:true },
    { kind:"custom", id:"link-preview", render: linkPreview }
  ]
},
{
  id: "tag-bars", tab: "visual", order: 200, heading: "Tag Bars",
  intro: "A colored Bar in the margin shows at a glance what a line and everything nested under it is about, without reading the tags",
  tip: "Bars take their colors from the Values of one tag Field, which you choose below. Links and dates have no colors, so they can’t draw Bars. A Bar runs down its line and everything nested under it. A deeper line with its own Value gets its own Bar beside it. Your text does not move, and once the Bar shows the Value you can hide the tag",
  items: [
    { kind:"custom", id:"bars-preview", render: barsPreview },
    { kind:"toggle", id:"bars-active", path:"visual.tagBars.active", default:false,
      name:"Tag Bars", desc:"Draw the Bars",
      tip:"Bars show without any text which Value a line has and how deep it sits in the list. They use the colors you already gave the Values, so you don’t color anything twice. Turn it off to hide the Bars and keep the settings below",
      searchTerms:["Activate strip","Strip","Hierarchy Bars","Level Bars"] },
    { kind:"dropdown", id:"bars-field", path:"visual.tagBars.fieldId", default:"",
      name:"Which Field draws Bars", desc:"Bars work with tag Fields only, and only for the one chosen here",
      searchTerms:["Strip Field"], visible: on("visual.tagBars.active"),
      /* Список — ваши Fields, а не эти два имени: они мокданные прототипа
         (Р8), и в панели их быть не должно. Первая строка отвечает за
         значение по умолчанию: без неё список показывал первый Field,
         когда не выбрано ничего (замечание заказчика 1.5.3.2). */
      options:[ {value:"",label:"None"} ], optionsFrom:"tag-fields",
      tip:"Pick the one thing you look for on a page, usually progress or urgency. Only your tag Fields are listed, because a Bar uses the color of a Value",
      seeAlso:{ id:"field-editor", label:"Bar colors are the Value colors under Fields" } },
    { kind:"slider", id:"bars-count", path:"visual.tagBars.stripesToShow", default:2,
      min:1, max:3, step:1,
      name:"Number of Bars", desc:"How far down the nesting to keep drawing them",
      searchTerms:["Stripes to show"], visible: on("visual.tagBars.active"),
      tip:"At 1 only the parent line gets a Bar. At 2 a child with its own Value gets a second Bar. At 3 a grandchild gets a third. A line without a Value never gets a Bar" },
    { kind:"toggle", id:"bars-show-tag", path:"visual.tagBars.tagVisibility", default:true,
      name:"Show the Field’s tag", desc:"Keep the tag on the line, or let the Bar speak for it",
      searchTerms:["Strip tag visibility"], visible: on("visual.tagBars.active"),
      tip:"The Bar already shows the Value by its color, so the tag is often not needed. Hide the tag to free up room on the line. The tag stays in your note and stays searchable" },
    { kind:"toggle", id:"bars-hide-separator", path:"visual.tagBars.hideSeparatorWhenOnlyStripToken", default:false,
      name:"Hide the leftover marker", desc:"Tidy away a Separator that has nothing left beside it",
      searchTerms:["Hide Separator?"],
      visible:{ deps:["visual.tagBars.active","visual.tagBars.tagVisibility"],
                test: c => Boolean(c.get("visual.tagBars.active")) && !c.get("visual.tagBars.tagVisibility") },
      tip:"If the hidden tag was the only thing before your text, a lone Separator is left at the start of the line. This setting hides it" },
    { kind:"dropdown", id:"bars-mode", path:"visual.tagBars.mode", default:"default",
      name:"Bar arrangement", desc:"Which lane each level of the tree draws its Bar in",
      searchTerms:["Strip mode"], visible: on("visual.tagBars.active"),
      options:[ {value:"default",label:"Parent outside"}, {value:"crossing",label:"Rotate"} ],
      tip:"With <b>parent keeps the outer lane</b>, each level of the list always uses the same lane, so you can count the nesting from the left. With <b>lanes rotate</b>, each level takes the next lane in turn. Deep lists stay narrower, but a lane no longer tells you the level" },
    { kind:"slider", id:"bars-thickness", path:"visual.tagBars.thickness", default:2,
      min:1, max:12, step:1, unit:"px",
      name:"Bar thickness", desc:"How wide each Bar is",
      tip:"One width for all Bars, because Bars of different widths look like a mistake. Thin Bars suit dense notes. Wide Bars are easier to tell apart when your Value colors are similar",
      searchTerms:["Strip thickness"], visible: on("visual.tagBars.active") },
    { kind:"slider", id:"bars-gap", path:"visual.tagBars.childOffset", default:12,
      min:2, max:20, step:1, unit:"px",
      name:"Space between Bars", desc:"The gap between one level and the next",
      tip:"The space between the lanes of two levels. With little space a deep list looks like one ribbon. With more space the levels stay apart, but there is less room for your text",
      searchTerms:["Parent/child strip distance"], visible: on("visual.tagBars.active") },
    { kind:"slider", id:"bars-distance", path:"visual.tagBars.spacing", default:20,
      min:8, max:48, step:1, unit:"px",
      name:"Distance from the text", desc:"How far the Bars sit from where your line begins",
      tip:"Moves all the Bars together, away from your text. Increase it if your notes are indented and the Bars crowd the list markers",
      searchTerms:["Strip spacing"], visible: on("visual.tagBars.active") },
    { kind:"slider", id:"bars-line-gap", path:"visual.tagBars.lineGap", default:2,
      min:0, max:8, step:1, unit:"px",
      name:"Vertical gap between Bars", desc:"Blank left above and below a Bar, so two lines in a row stay apart",
      searchTerms:["Bar height"], visible: on("visual.tagBars.active"),
      tip:"Without a gap, the Bars of lines one under another merge into one, and you can’t tell which part belongs to which line. A small gap separates them, and a bigger number makes each Bar shorter. At <code>0</code> the Bars touch again" },
    { kind:"toggle", id:"bars-whole-tree", path:"visual.tagBars.drawWholeTree", default:true,
      name:"Bars for the whole tree", desc:"A Bar runs down everything nested under its line, not just the line itself",
      searchTerms:["Draw bars for the whole tree","Bars for subtree"], visible: on("visual.tagBars.active"),
      tip:"When on, a Bar runs down its line and everything indented under it, so a nested line can carry several Bars. When off, each Bar covers only its own line, lines without their own Value get no Bar, and <code>Join Bars in a tree</code> has no effect" },
    { kind:"toggle", id:"bars-join-tree", path:"visual.tagBars.joinTree", default:true,
      name:"Join Bars in a tree", desc:"A parent and its own children draw one unbroken Bar",
      searchTerms:["Tree gap"], visible: on("visual.tagBars.active"),
      tip:"The gap between lines also cuts a Bar that runs down through nested lines. With this on, there is no gap where a Bar continues from a parent into its children. Lines that are not related stay apart" }
  ]
},
{
  id: "tagwheel", tab: "visual", order: 300, heading: "tagWheel",
  intro: "tagWheel is a picker that opens over the line. Your Fields run across it and the Values of the current Field run down. You pick a Value by looking instead of remembering a hotkey for each Field",
  tip: "Every Field has its own pair of hotkeys, which is too many to remember. Instead, one command opens the picker over the line. Left and right move between Fields, and up and down move between Values. <code>Tab</code> jumps to the Fields on the other side of your text, and <code>Escape</code> closes it without changing anything. The settings below control how it looks",
  commands: ["tagWheel Left", "tagWheel Right"],
  items: [
    { kind:"custom", id:"wheel-preview", render: wheelPreview },
    { kind:"custom", id:"panel-sub", render: subheader("Panel",
      "The strip drawn over your line: what each cell shows and the colors of the strip. The box of neighboring Values has its own rows below. You choose which Field it opens on in <code>Tags & PKM</code> → <code>tagWheel behavior</code>") },
    { kind:"toggle", id:"panel-markers", path:"visual.tagWheel.showMarkers", default:true,
      name:"Show tag markers", desc:"Show the hash and emoji in the picker, or just the words",
      searchTerms:["Show Prefix"],
      tip:"Words alone are quicker to read than words with hashes in front. What goes into your note is the same either way" },
    { kind:"dropdown", id:"panel-value-names", path:"visual.tagWheel.valueNames", default:"default",
      name:"tagWheel Value names", desc:"What the picker prints for a Field that already carries a Value",
      searchTerms:["Value names","Custom text in the picker","Printed name"],
      options:[ {value:"default",label:"Default"},
                {value:"custom",label:"Custom"},
                {value:"both",label:"Custom + default"} ],
      tip:"<code>Default</code> shows the Value as it is written in your line. <code>Custom</code> shows the custom text set for the Value under Fields (<code>Show</code> = <code>custom</code>), such as an emoji or a short word. <code>Custom + default</code> shows both, with the custom text first. If a Value has no custom text, all three show the written Value" },
    { kind:"toggle", id:"panel-highlight", path:"visual.tagWheel.highlightLine", default:true,
      name:"Highlight the tagWheel line", desc:"Mark the line while the picker is open, so it stands out from the page",
      searchTerms:["Highlight the line"],
      tip:"On a busy page the picker is hard to tell from your note. When on, the line is wrapped in <code>==</code> while the picker is open. <code>Background color</code> below sets the color, and without it Obsidian uses its own highlight. The marks go away when the picker closes, and nothing is left in your note" },
    { kind:"color", id:"panel-text-color", path:"visual.tagWheel.textColor", default:"",
      name:"Inactive Field text color", desc:"The color of the Field names you are not standing on, while the line is marked",
      searchTerms:["Text color"],
      tip:"Works only while <code>Highlight the tagWheel line</code> is on. The box of neighboring Values below uses your theme’s colors and is not affected",
      allowReset:true },
    { kind:"toggle", id:"panel-bold-names", path:"visual.tagWheel.boldFieldNames", default:false,
      name:"Bold Field names", desc:"Print every Field that shows its own name in bold, while the line is marked",
      searchTerms:["Bold names","Empty Fields in bold"],
      tip:"Off: only the Field you are on is bold. On: every Field that still shows its name is bold, so the Fields without a Value stand out. Fields that have a Value stay regular. Needs <code>Highlight the tagWheel line</code> on" },
    { kind:"color", id:"panel-active-color", path:"visual.tagWheel.activeTextColor", default:"",
      name:"Active Field text color", desc:"The color of the Field you are on, while the line is marked",
      searchTerms:["Current Field color"],
      tip:"The up and down keys move through the Field you are on. Without its own color, only bold text tells it apart, which is easy to miss on a line with many Fields. Leave it empty to use <code>Inactive Field text color</code>",
      allowReset:true },
    { kind:"color", id:"panel-chosen-color", path:"visual.tagWheel.chosenValueColor", default:"",
      name:"Chosen Value text color", desc:"The color of a Field that already carries a Value, while the line is marked",
      searchTerms:["Chosen value color","Picked value color"],
      tip:"Gives Fields that already have a Value their own color, so one glance shows which Fields on the line are filled in. Leave it empty to use <code>Inactive Field text color</code>. The Field you are on has its own row above",
      allowReset:true },
    { kind:"color", id:"panel-background", path:"visual.tagWheel.fillColor", default:"",
      name:"Background color", desc:"The color behind the picker, while the line is marked",
      searchTerms:["Background"],
      tip:"Pick a color solid enough to read on, since the picker covers your text. Needs <code>Highlight the tagWheel line</code> on", allowReset:true },
    { kind:"custom", id:"scroller-sub", render: subheader("Scroller",
      "A box of neighboring Values that opens from the Field you are on, so you can see what comes next. It has its own colors, separate from the panel. The preview at the top of this group shows both") },
    { kind:"toggle", id:"scroller-enabled", path:"visual.tagWheel.scroller.enabled", default:false,
      name:"Scroller", desc:"Show the next and previous Values around the current one",
      tip:"When off, you see only the current Value and step through blindly. When on, you see what is coming, which makes long lists much quicker to go through",
      searchTerms:["tagWheel Scroller"] },
    { kind:"dropdown", id:"scroller-direction", path:"visual.tagWheel.scroller.direction", default:"full",
      name:"Scroller opening direction", desc:"Which way the Values unroll from the Field you are on",
      tip:"<code>Up</code> keeps your line at the bottom of the box, and your note stays visible below it. <code>Down</code> does the opposite. <code>Both</code> puts the current Value in the middle and is easiest to read when a Field has many Values",
      searchTerms:["Scroller direction","Opens"], visible: on("visual.tagWheel.scroller.enabled"),
      options:[ {value:"up",label:"Up"}, {value:"down",label:"Down"},
                {value:"full",label:"Both"} ] },
    { kind:"dropdown", id:"scroller-labels", path:"visual.tagWheel.scroller.labels", default:"value",
      name:"Scroller Value names", desc:"What the box shows for each neighboring Value",
      tip:"<code>Default</code> shows the Value as it is written in your line. <code>Custom</code> shows the custom text set for the Value under Fields (<code>Show</code> = <code>custom</code>), such as an emoji or a short word. <code>Custom + default</code> shows both, with the custom text first. If a Value has no custom text, all three show the written Value",
      searchTerms:["Scroller names","Custom text in the scroller","Printed name","As written","Custom text when set"],
      visible: on("visual.tagWheel.scroller.enabled"),
      options:[ {value:"value",label:"Default"},
                {value:"custom",label:"Custom"},
                {value:"both",label:"Custom + default"} ] },
    { kind:"color", id:"scroller-fill", path:"visual.tagWheel.scroller.fillColor", default:"",
      name:"Scroller background color", desc:"The color behind the box of neighboring Values",
      searchTerms:["Scroller background"],
      tip:"Leave it empty to use your theme’s popup color. Set a color to make the box stand out from your note, for example on a pale theme",
      visible: on("visual.tagWheel.scroller.enabled"), allowReset:true },
    { kind:"color", id:"scroller-text", path:"visual.tagWheel.scroller.textColor", default:"",
      name:"Scroller text color", desc:"The color of the Values you are not on, inside the box",
      searchTerms:["Scroller text"],
      tip:"Leave it empty to use your theme’s text color. The Value you are on is not in the box. It shows in the line, colored by <code>Active Field text color</code>",
      visible: on("visual.tagWheel.scroller.enabled"), allowReset:true },
    { kind:"slider", id:"scroller-size", path:"visual.tagWheel.scroller.size", default:3,
      min:1, max:20, step:1,
      name:"Scroller size", desc:"How many neighboring Values stay visible around the current one",
      tip:"This counts the Values on each side, not in total. A small number keeps the box out of the way. A large number shows every Value of a short Field at once",
      searchTerms:["Values per side"], visible: on("visual.tagWheel.scroller.enabled") }
  ]
},
{
  id: "text-cursor", tab: "visual", order: 400, heading: "Text cursor",
  intro: "The blinking line that shows where your typing goes. Give it its own color so it stops getting lost on the page",
  tip: "By default the cursor is the same color as your text, so in long notes or one-color themes it is easy to lose. Pick a color you use nowhere else and it stands out at a glance. This changes the cursor in your notes only. This window and the search box keep their usual cursor",
  items: [
    { kind:"toggle", id:"caret-enabled", path:"visual.caret.enabled", default:false,
      name:"Color the text cursor", desc:"Draw the blinking caret in a color you pick instead of the color of your text",
      searchTerms:["Caret color","Cursor color"],
      tip:"When off, your theme decides the cursor color. When on, the color below is used, only in the editor" },
    { kind:"color", id:"caret-color", path:"visual.caret.color", default:"",
      name:"Cursor color", desc:"The color of the blinking caret in your notes",
      searchTerms:["Caret"], visible: on("visual.caret.enabled"),
      tip:"Leave it empty to keep your theme’s color. For the cursor to stand out, pick a color your page does not already use", allowReset:true },
    { kind:"toggle", id:"caret-shape", path:"visual.caret.shapeEnabled", default:false,
      name:"Shape the text cursor", desc:"Set how thick the caret is and how fast it blinks, instead of taking both from your theme",
      searchTerms:["Caret width","Cursor blink","Caret thickness"],
      tip:"This works separately from the color, and you can use either one alone. When off, the cursor keeps the thickness and blinking your theme and Obsidian give it" },
    { kind:"slider", id:"caret-width", path:"visual.caret.width", default:2,
      min:1, max:8, step:1, unit:"px",
      name:"Cursor width", desc:"How thick the caret is drawn, in pixels",
      searchTerms:["Caret thickness"], visible: on("visual.caret.shapeEnabled"),
      tip:"Obsidian’s cursor is about one pixel wide, which is easy to miss on a bright background or a large screen. Two or three pixels is easy to find and still doesn’t look like a selection" },
    { kind:"slider", id:"caret-blink", path:"visual.caret.blinkSpeed", default:5,
      min:0, max:10, step:1,
      name:"Blink speed", desc:"How fast the caret blinks, from not blinking at all to very fast",
      searchTerms:["Blink rate","Cursor blinking"], visible: on("visual.caret.shapeEnabled"),
      tip:"At <code>0</code> the cursor stops blinking, which is the calmest setting. <code>5</code> is Obsidian’s current speed, and each step above it blinks faster" },
    { kind:"custom", id:"caret-preview", render: caretPreview }
  ]
},
{
  id: "jump-highlight", tab: "visual", order: 450, heading: "Cursor jump highlight",
  intro: "After a jump, the cursor is hard to find again. This shows a circle where it lands, and the circle shrinks away by itself",
  tip: "The circle only appears on screen for a moment. Nothing is written into your note. It shows only on jumps, not when you type or use the arrow keys. The last row decides whether short hops within one line count as jumps too",
  commands: ["Jump up", "Jump down"],
  items: [
    { kind:"toggle", id:"jump-flash", path:"visual.jumpFlash.enabled", default:false,
      name:"Highlight where you land", desc:"Draw a fading circle where the cursor lands, so you do not hunt for it",
      searchTerms:["Flash on jump","Highlight the jump target","Show me where the cursor went"],
      tip:"The circle shows only on jumps, not when you type or use the arrow keys. Nothing is written into your file" },
    { kind:"color", id:"jump-flash-color", path:"visual.jumpFlash.color", default:"",
      allowReset:true,
      name:"Highlight color", desc:"Leave it unset to use the accent color of your theme",
      searchTerms:["Color of the jump circle"],
      tip:"Unset uses your theme’s accent color, so the circle matches the editor. Pick your own if the accent color is too faint on your background",
      visible: on("visual.jumpFlash.enabled") },
    { kind:"slider", id:"jump-flash-radius", path:"visual.jumpFlash.radius", default:18,
      min:6, max:40, step:1, unit:"px",
      name:"Highlight size", desc:"How wide the circle is at the moment it appears",
      searchTerms:["Size of the jump circle"],
      tip:"Too small, and it is no easier to spot than the cursor. Too large, and it covers the words you jumped to until it fades",
      visible: on("visual.jumpFlash.enabled") },
    { kind:"slider", id:"jump-flash-fade", path:"visual.jumpFlash.fadeMs", default:450,
      min:100, max:1500, step:50, unit:"ms",
      name:"How long it lasts", desc:"The time the circle takes to shrink and disappear",
      searchTerms:["Fade speed of the jump circle"],
      tip:"A short time just catches the corner of your eye. A long time gets annoying when you jump several times in a row. To skip the circle while you jump quickly, use the row below",
      visible: on("visual.jumpFlash.enabled") },
    { kind:"slider", id:"jump-flash-delay", path:"visual.jumpFlash.quietMs", default:0,
      min:0, max:1000, step:50, unit:"ms",
      name:"Minimum time between jumps", desc:"Jumps closer together than this get no circle at all",
      searchTerms:["Do not flash on every jump","Quiet time"],
      tip:"If you hold a key down, the circle would flash on every step. Set a minimum time and only the jump you stop on gets a circle. At <code>0</code> every jump gets a circle",
      visible: on("visual.jumpFlash.enabled") },
    { kind:"toggle", id:"jump-flash-inline", path:"visual.jumpFlash.inLine", default:false,
      name:"Use inside current line", desc:"Also mark the cursor when it hops between the parts of one line",
      searchTerms:["Flash on in-line jumps"],
      tip:"<code>Jump left</code> and <code>Jump right</code> move the cursor only a short way, so it usually stays where you are looking. Turn this on if you lose the cursor on long lines too",
      visible: on("visual.jumpFlash.enabled") },
    { kind:"custom", id:"jump-flash-preview", render: jumpFlashPreview,
      visible: on("visual.jumpFlash.enabled") }
  ]
},
{
  id: "user-tag-colors", tab: "visual", order: 500, heading: "Color custom tags",
  intro: "Colors for tags you type yourself that are not a Value of any Field in <code>Tags & PKM → Fields</code>. These tags still get a bubble, and here you choose how it looks",
  tip: "Each row is one tag. You set the bubble color, the text color, and whether it shows the word, the word with its hash, or nothing. Values of a Field get their colors on <code>Tags & PKM</code>. Use these rows for every other tag, including tags added by other plugins. Leave a color unset and the tag follows your theme",
  items: [
    { kind:"custom", id:"user-tag-list", render: userTagColors }
  ]
}
];
