/**
 * ВНИМАНИЕ: файл сгенерирован из docs/prototype/settings_prototype.html.
 * Руками не правится. Правится прототип, затем `npm run gen:schema`.
 *
 * Тексты согласованы заказчиком и совпадают с Приложением B PRD.
 */

import type { SettingsGroup } from "../types.ts";
import { on } from "../types.ts";
import { callout } from "../custom/callouts.ts";
import { barsPreview, caretPreview, jumpFlashPreview, linkPreview, tagPreview, wheelPreview } from "../custom/previews.ts";
import { subheader } from "../custom/subheader.ts";
import { userTagColors } from "../custom/user_tags.ts";

export const VISUAL_GROUPS: readonly SettingsGroup[] = [
{ id: "visual-intro",    tab: "visual",     order: 50, heading: "Before you start",
  items: [
    { kind:"custom", id:"visual-callout", render: callout("visual") }
  ],
  visible: on("general.help.showCallouts") },
{
  id: "tag-appearance", tab: "visual", order: 100, heading: "Inline appearance",
  intro: "Makes tagged lines easier to read: tags become small colored bubbles, and links and dates stay ordinary text. Your file stays exactly the same",
  tip: "- <b>Opacity</b> — the rows fade the tags, dates and links on each side so your own text stands out\n- <b>Line view</b> — sets how big they are and adds a colored Stripe behind them\n- <b>Tag view</b> — shapes the tag bubble\nYou set the colors of single Values on each Field, on the <code>Tags & PKM</code> tab",
  items: [
    { kind:"custom", id:"tag-preview", render: tagPreview },
    { kind:"custom", id:"line-view-sub", render: subheader("Line view",
        "These rows change the tags, dates and links before and after your text: how faded they are, how big they are, and whether a colored Stripe runs behind them. Your own text between the Separators never changes") },
    { kind:"slider", id:"tags-opacity-left", path:"visual.tags.opacityLeft", default:100,
      min:0, max:100, step:1, unit:"%",
      name:"Opacity of the Left Block", desc:"Dims everything written before your text, tags and elements alike",
      tip:"Fades everything before your text. Faded is not hidden: it stays on the line, in search and in the commands\n- <b>100</b> — <code>#todo :: call Anna</code> looks as usual\n- <b>40</b> — <code>#todo</code> turns pale and <code>call Anna</code> stands out\n- <b>0</b> — the Left Block is invisible but still there",
      searchTerms:["Opacity Left"],
      seeAlso:{ id:"field-editor", label:"Tag colors are set per Value under Fields" } },
    { kind:"slider", id:"tags-opacity-right", path:"visual.tags.opacityRight", default:100,
      min:0, max:100, step:1, unit:"%",
      name:"Opacity of the Right Block", desc:"Dims everything written after your text, tags and elements alike",
      tip:"Fades everything after your text, apart from the left side. Things there usually need less attention\n- <b>100</b> — <code>call Anna :: [[Meeting]]</code> looks as usual\n- <b>40</b> — <code>[[Meeting]]</code> turns pale and <code>call Anna</code> stands out\n- <b>0</b> — the Right Block is invisible but still there and still works",
      searchTerms:["Opacity Right"] },
    { kind:"slider", id:"tags-text-size-left", path:"visual.tags.textSizePctLeft", default:100,
      min:50, max:140, step:5, unit:"%",
      name:"Left Block text size", desc:"How big everything before your text is written, next to the rest of your note",
      tip:"Changes the size of the tags, dates and links before your text. Your own text keeps its size\n- <b>100</b> — <code>#todo</code> in <code>#todo :: call Anna</code> has its usual size\n- <b>70</b> — <code>#todo</code> is smaller, so your sentence leads\n- <b>130</b> — <code>#todo</code> is bigger and competes with your text",
      searchTerms:["Tag text size", "Text size Left"] },
    { kind:"slider", id:"tags-text-size-right", path:"visual.tags.textSizePctRight", default:100,
      min:50, max:140, step:5, unit:"%",
      name:"Right Block text size", desc:"How big everything after your text is written, next to the rest of your note",
      tip:"Changes the size of the tags, dates and links after your text, apart from the left side. Your own text keeps its size\n- <b>100</b> — <code>[[Meeting]]</code> in <code>call Anna :: [[Meeting]]</code> has its usual size\n- <b>80</b> — <code>[[Meeting]]</code> is a size smaller and reads as a side note",
      searchTerms:["Tag text size", "Text size Right"] },
    { kind:"toggle", id:"tags-block-fill", path:"visual.tags.blockFill.enabled", default:false,
      /* Имя его словами (З-13, 2026-09-19): «измени названия
         контролов: tags-block-fill на `Color the Block with Stripe`…» — и оно
         стоит в панели дословно: ровно пять слов, предел имени
         соблюдён. Прежняя подпись `Color the Blocks` была моим
         компромиссом вместо его же `Color Left\\Right blocks`, и новое слово
         сильнее старого; старая осталась в `searchTerms`, чтобы поиск
         панели её находил. */
      name:"Color the Block with Stripe", desc:"A Stripe behind the Left Block and the Right Block, so the two stand out from your text",
      searchTerms:["Block background", "Color the Blocks"],
      tip:"- <b>On</b> — in <code>#todo :: call Anna :: [[Meeting]]</code> a colored Stripe runs behind <code>#todo</code> and behind <code>[[Meeting]]</code>\n- <b>Off</b> — no Stripe\nYour own text and empty Blocks never get a Stripe, and everything stays clickable. A single tag bubble can hide the Stripe: raise <code>Stripe height</code> or <code>Stripe width</code>" },
    { kind:"dropdown", id:"tags-block-fill-direction", path:"visual.tags.blockFill.direction", default:"both",
      name:"Stripe direction", desc:"Which of the two Blocks gets a Stripe",
      tip:"Example line: <code>#todo :: call Anna :: [[Meeting]]</code>\n- <b>Left</b> — a Stripe only behind <code>#todo</code>\n- <b>Right</b> — a Stripe only behind <code>[[Meeting]]</code>\n- <b>Both</b> — a Stripe on each side. The usual choice\nYour own text never gets a Stripe",
      options:[ {value:"left",label:"Left"}, {value:"right",label:"Right"}, {value:"both",label:"Both"} ],
      visible: on("visual.tags.blockFill.enabled") },
    { kind:"color", id:"tags-block-fill-color", path:"visual.tags.blockFill.color", default:"",
      name:"Stripe color", desc:"Leave it unset and the Stripe follows your theme",
      searchTerms:["Block color"],
      tip:"- <b>Unset</b> — the Stripe takes your theme’s accent color and still fits when you switch themes\n- <b>A color</b> — the Stripe is always that color, for example pale yellow behind <code>#todo</code>",
      visible: on("visual.tags.blockFill.enabled") },
    { kind:"slider", id:"tags-block-fill-opacity", path:"visual.tags.blockFill.opacity", default:12,
      min:0, max:100, step:1, unit:"%",
      name:"Stripe opacity", desc:"How strongly the Stripe shows through",
      searchTerms:["Block color strength"],
      tip:"How strongly the Stripe shows. Keep it low so the writing stays easy to read\n- <b>0</b> — the Stripe is invisible\n- <b>12</b> — a light tint that shows where a Block starts and ends\n- <b>50</b> — a strong color behind the Values",
      visible: on("visual.tags.blockFill.enabled") },
    { kind:"slider", id:"tags-block-fill-height", path:"visual.tags.blockFill.heightPct", default:60,
      min:0, max:100, step:20, unit:"%",
      name:"Stripe height", desc:"How far the Stripe reaches above and below the writing",
      searchTerms:["Band height"],
      tip:"- <b>0</b> — the Stripe is exactly as tall as the writing, so a single tag bubble can hide it\n- <b>60</b> — it reaches a good way above and below the writing\n- <b>100</b> — it fills the whole line. Stripes of lines one under another meet without overlapping",
      visible: on("visual.tags.blockFill.enabled") },
    { kind:"slider", id:"tags-block-fill-width", path:"visual.tags.blockFill.widthPct", default:50,
      min:0, max:100, step:5, unit:"%",
      name:"Stripe width", desc:"How far the Stripe reaches past the Block on both of its sides",
      searchTerms:["Band width"],
      tip:"Example line: <code>#todo :: call Anna</code>\n- <b>0</b> — the Stripe covers only <code>#todo</code>\n- <b>50</b> — it reaches up to the Separator <code>::</code>\n- <b>100</b> — it covers <code>::</code> too\nOn the Left Block it never covers the bullet or the checkbox",
      visible: on("visual.tags.blockFill.enabled") },
    { kind:"custom", id:"tag-view-sub", render: subheader("Tag view",
        "These rows shape only the tag bubble: the space around the word, how tall the bubble is and how round its corners are. Dates and links have no bubble, so these rows don’t change them") },
    { kind:"slider", id:"tags-bubble-width", path:"visual.tags.bubbleWidthPct", default:100,
      min:20, max:140, step:5, unit:"%",
      name:"Tag bubble width", desc:"How much breathing room there is either side of the word",
      tip:"Sets the room on each side of the word. The word keeps its size\n- <b>20</b> — the word sits almost at the edge of the bubble\n- <b>100</b> — the usual bubble\n- <b>140</b> — wide bubbles, so <code>#todo #urgent</code> look like separate chips",
      searchTerms:["Tag bubble size - width", "Bubble width"] },
    { kind:"slider", id:"tags-bubble-height", path:"visual.tags.bubbleHeightPct", default:100,
      min:20, max:140, step:5, unit:"%",
      name:"Tag bubble height", desc:"How tall the bubble is around the word",
      tip:"Sets the room above and below the word. Keep it modest: tall bubbles push the lines of your note apart\n- <b>20</b> — the bubble hugs the word\n- <b>100</b> — the usual bubble\n- <b>140</b> — a taller bubble around the word",
      searchTerms:["Tag bubble size - height", "Bubble height"] },
    { kind:"slider", id:"tags-corners", path:"visual.tags.cornersPct", default:0,
      min:0, max:100, step:1,
      name:"Tag bubble corners", desc:"Slide from fully rounded to completely square",
      tip:"Changes only the corners. The color, the room around the word and the text size stay the same\n- <b>0</b> — <code>#todo</code> sits in a round pill\n- <b>50</b> — rounded corners, less round than a pill\n- <b>100</b> — a sharp rectangle, which looks denser and suits narrow bubbles",
      searchTerms:["Tag shape", "Bubble corners"] },
    { kind:"slider", id:"tags-empty-bubble", path:"visual.tags.emptyBubblePct", default:100,
      min:10, max:180, step:5, unit:"%",
      name:"Empty tag bubble width", desc:"Width of a bubble whose <code>Show</code> is set to <code>empty</code>",
      searchTerms:["Empty bubble size", "Empty bubble width"],
      tip:"Under <code>Fields</code> you can set a Value’s <code>Show</code> to <code>empty</code>. Then <code>#urgent</code> shows only its color, as a bubble with no text. This row sets how wide it is\n- <b>50</b> — half the usual width\n- <b>100</b> — the usual width\n- <b>180</b> — almost twice as wide",
      seeAlso:{ id:"field-editor", label:"Set a Value to empty under Fields" } },
    { kind:"custom", id:"link-view-sub", render: subheader("Link view",
        "These rows are for link Values shown as your own text (<code>Show</code> = <code>custom</code>) instead of <code>[[the note name]]</code>. A click always opens the note. The two rows below bring back the hover preview and the dragging that ordinary links have") },
    { kind:"toggle", id:"link-hover-preview", path:"visual.tags.linkShown.hoverPreview", default:false,
      name:"Preview on hover", desc:"Hovering a Value shown as your own text opens the page preview — hold <code>Ctrl</code> while hovering",
      tip:"For link Values shown as your own text, for example <code>[[Project Alpha]]</code> shown as <code>Alpha</code>\n- <b>On</b> — hold <code>Ctrl</code> (<code>Cmd</code> on macOS) and hover <code>Alpha</code> to see the note, like Obsidian’s <code>Page preview</code>\n- <b>Off</b> — hovering shows nothing. A click still opens the note\nTo preview without <code>Ctrl</code>, turn off the modifier key for <code>Page preview → Source mode</code>",
      searchTerms:["Link hover preview", "Custom link preview"] },
    { kind:"toggle", id:"link-draggable", path:"visual.tags.linkShown.draggable", default:false,
      name:"Drag to move", desc:"Drag a Value shown as your own text into another note",
      tip:"For link Values shown as your own text, for example <code>[[Project Alpha]]</code> shown as <code>Alpha</code>\n- <b>On</b> — drag <code>Alpha</code> into another note and you get the link <code>[[Project Alpha]]</code> there. Pressing the Value starts a drag instead of placing the cursor\n- <b>Off</b> — the Value cannot be dragged. Off by default because it is easy to grab by accident",
      searchTerms:["Link drag", "Custom link drag"] },
    { kind:"color", id:"link-target-color", path:"visual.tags.linkAsWritten.targetColor", default:"",
      name:"Link target color", desc:"What you read in a wikilink: the name between <code>[[</code> and <code>]]</code>",
      searchTerms:["Link color", "Wikilink color", "Link text color"],
      tip:"Colors the note name in a link Value written as <code>[[Meeting]]</code> (<code>Show</code> = <code>default</code>)\n- <b>Empty</b> — <code>Meeting</code> keeps your theme’s link color\n- <b>A color</b> — <code>Meeting</code> takes that color, the brackets do not\nHyperlinks have their own rows below",
      allowReset:true },
    { kind:"color", id:"link-brackets-color", path:"visual.tags.linkAsWritten.bracketsColor", default:"",
      name:"Link brackets color", desc:"The markup around it: <code>[[</code> and <code>]]</code>",
      searchTerms:["Bracket color", "Wikilink brackets"],
      tip:"Colors <code>[[</code> and <code>]]</code> around <code>[[Meeting]]</code>, apart from the name\n- <b>Empty</b> — the brackets keep your theme’s color\n- <b>A color</b> — the brackets take that color\nYou see it only in the previews here and on the line your cursor is on. Everywhere else Obsidian hides the brackets",
      allowReset:true },
    { kind:"color", id:"hyperlink-target-color", path:"visual.tags.hyperlink.targetColor", default:"",
      name:"Hyperlink target color", desc:"The text you read in a Markdown link — what stands between the square brackets",
      searchTerms:["Hyperlink color", "External link color", "URL color"],
      tip:"Colors the text you read in a Markdown link, in every note\n- <b>Empty</b> — <code>Docs</code> in <code>[Docs](https://example.com)</code> keeps your theme’s link color\n- <b>A color</b> — <code>Docs</code> takes that color\nLinks inside backticks and images are not changed. The address has its own row below",
      allowReset:true },
    { kind:"color", id:"hyperlink-brackets-color", path:"visual.tags.hyperlink.bracketsColor", default:"",
      name:"Hyperlink brackets color", desc:"The markup around it: the square brackets and the round ones, without the address",
      searchTerms:["Hyperlink brackets", "URL markup color", "Address color"],
      tip:"Colors only <code>[</code>, <code>](</code> and <code>)</code> in <code>[Docs](https://example.com)</code>\n- <b>Empty</b> — they keep your theme’s color\n- <b>A color</b> — they take that color. <code>Docs</code> and the address do not\nYou see them only in the preview and on the line your cursor is on. Everywhere else Obsidian hides them",
      allowReset:true },
    { kind:"color", id:"hyperlink-address-color", path:"visual.tags.hyperlink.addressColor", default:"",
      name:"Hyperlink address color", desc:"The address itself — inside the round brackets, or written on its own",
      searchTerms:["Address color", "URL color", "Link href color"],
      tip:"Colors every web address. Leave it empty to keep your theme’s color\n- <b>On its own</b> — <code>https://example.com</code> or <code>www.example.com</code> is always colored\n- <b>Inside a link</b> — the address in <code>[Docs](https://example.com)</code> is colored only on the line your cursor is on",
      allowReset:true },
    { kind:"custom", id:"link-preview", render: linkPreview }
  ]
},
{
  id: "tag-bars", tab: "visual", order: 200, heading: "Tag Bars",
  intro: "A colored Bar in the margin shows at a glance what a line and everything nested under it is about, without reading the tags",
  tip: "Bars take their colors from the Values of one tag Field, which you choose below. Links and dates have no colors, so they can’t draw Bars. A Bar runs down its line and everything nested under it. A deeper line with its own Value gets its own Bar beside it. Your text does not move, and once the Bar shows the Value you can hide the tag",
  items: [
    { kind:"custom", id:"bars-preview", render: barsPreview },
    { kind:"toggle", id:"bars-active", path:"visual.tagBars.active", default:false,
      name:"Tag Bars", desc:"Draw the Bars",
      tip:"- <b>On</b> — a colored Bar in the margin runs along <code>- #todo :: plan trip</code> and the lines nested under it\n- <b>Off</b> — no Bars. The settings below are kept\nBars use the colors you already gave the Values, so you color nothing twice",
      searchTerms:["Activate strip","Strip","Hierarchy Bars","Level Bars"] },
    { kind:"dropdown", id:"bars-field", path:"visual.tagBars.fieldId", default:"",
      name:"Which Field draws Bars", desc:"Bars work with tag Fields only, and only for the one chosen here",
      searchTerms:["Strip Field"], visible: on("visual.tagBars.active"),
      /* Список — ваши Fields, а не эти два имени: они мокданные прототипа
         (Р8), и в панели их быть не должно. Первая строка отвечает за
         значение по умолчанию: без неё список показывал первый Field,
         когда не выбрано ничего (замечание заказчика 1.5.3.2). */
      options:[ {value:"",label:"None"} ], optionsFrom:"tag-fields",
      tip:"Pick the one tag Field you look for on a page, usually progress or urgency\n- <b>None</b> — no Field is chosen, so no Bars are drawn\n- <b>A tag Field</b> — a line with <code>#urgent</code> gets a Bar in the color of <code>#urgent</code>\nOnly tag Fields are listed: links and dates have no colors",
      seeAlso:{ id:"field-editor", label:"Bar colors are the Value colors under Fields" } },
    { kind:"slider", id:"bars-count", path:"visual.tagBars.stripesToShow", default:2,
      min:1, max:3, step:1,
      name:"Number of Bars", desc:"How far down the nesting to keep drawing them",
      searchTerms:["Stripes to show"], visible: on("visual.tagBars.active"),
      tip:"How many levels of a list can show a Bar\n- <b>1</b> — one Bar: <code>- #todo :: plan trip</code> and all lines under it show the color of <code>#todo</code>\n- <b>2</b> — a child line with its own Value, like <code>#urgent</code>, adds a second Bar\n- <b>3</b> — a grandchild with its own Value adds a third" },
    { kind:"toggle", id:"bars-show-tag", path:"visual.tagBars.tagVisibility", default:true,
      name:"Show the Field’s tag", desc:"Keep the tag on the line, or let the Bar speak for it",
      searchTerms:["Strip tag visibility"], visible: on("visual.tagBars.active"),
      tip:"- <b>On</b> — <code>- #todo :: call Anna</code> shows both the tag and the Bar\n- <b>Off</b> — the line shows <code>- :: call Anna</code>, and the Bar alone tells you it is <code>#todo</code>\nThe tag stays in your note and stays searchable" },
    { kind:"toggle", id:"bars-hide-separator", path:"visual.tagBars.hideSeparatorWhenOnlyStripToken", default:false,
      name:"Hide the leftover marker", desc:"Tidy away a Separator that has nothing left beside it",
      searchTerms:["Hide Separator?"],
      visible:{ deps:["visual.tagBars.active","visual.tagBars.tagVisibility"],
                test: c => Boolean(c.get("visual.tagBars.active")) && !c.get("visual.tagBars.tagVisibility") },
      tip:"Works when the Field’s tag is hidden and was the only thing on that side of your text\n- <b>On</b> — <code>- #todo :: call Anna</code> shows as <code>- call Anna</code>\n- <b>Off</b> — it shows as <code>- :: call Anna</code>" },
    { kind:"dropdown", id:"bars-mode", path:"visual.tagBars.mode", default:"default",
      name:"Bar arrangement", desc:"Which lane each level of the tree draws its Bar in",
      searchTerms:["Strip mode"], visible: on("visual.tagBars.active"),
      options:[ {value:"default",label:"Parent outside"}, {value:"crossing",label:"Rotate"} ],
      tip:"- <b>Parent outside</b> — every level of the list has its own lane, so you can count the nesting from the left. A level without a Value leaves its lane empty\n- <b>Rotate</b> — only lines with a Value take a lane, so the Bars sit side by side. Deep lists stay narrower, but a lane no longer tells you the level" },
    { kind:"slider", id:"bars-thickness", path:"visual.tagBars.thickness", default:2,
      min:1, max:12, step:1, unit:"px",
      name:"Bar thickness", desc:"How wide each Bar is",
      tip:"One width for all Bars\n- <b>2</b> — thin Bars that suit dense notes\n- <b>6</b> — wide Bars, easier to tell apart when your Value colors are similar",
      searchTerms:["Strip thickness"], visible: on("visual.tagBars.active") },
    { kind:"slider", id:"bars-gap", path:"visual.tagBars.childOffset", default:12,
      min:2, max:20, step:1, unit:"px",
      name:"Space between Bars", desc:"The gap between one level and the next",
      tip:"The space between the Bars of two levels\n- <b>2</b> — the Bars of a deep list almost touch and look like one ribbon\n- <b>12</b> — the levels stay clearly apart\nMore space leaves less room for your text",
      searchTerms:["Parent/child strip distance"], visible: on("visual.tagBars.active") },
    { kind:"slider", id:"bars-distance", path:"visual.tagBars.spacing", default:20,
      min:8, max:48, step:1, unit:"px",
      name:"Distance from the text", desc:"How far the Bars sit from where your line begins",
      tip:"Moves all the Bars together, away from where your line begins\n- <b>8</b> — the Bars sit close to your list\n- <b>30</b> — more room, useful when your notes are indented and the Bars crowd the bullets",
      searchTerms:["Strip spacing"], visible: on("visual.tagBars.active") },
    { kind:"slider", id:"bars-line-gap", path:"visual.tagBars.lineGap", default:2,
      min:0, max:8, step:1, unit:"px",
      name:"Vertical gap between Bars", desc:"Blank left above and below a Bar, so two lines in a row stay apart",
      searchTerms:["Bar height"], visible: on("visual.tagBars.active"),
      tip:"Blank space above and below each Bar, so lines one under another stay apart\n- <b>0</b> — the Bars of two lines in a row merge into one long Bar\n- <b>2</b> — a small break between the lines\n- <b>8</b> — a big break, and each Bar gets shorter" },
    { kind:"toggle", id:"bars-whole-tree", path:"visual.tagBars.drawWholeTree", default:true,
      name:"Bars for the whole tree", desc:"A Bar runs down everything nested under its line, not just the line itself",
      searchTerms:["Draw bars for the whole tree","Bars for subtree"], visible: on("visual.tagBars.active"),
      tip:"Example: <code>- #todo :: plan trip</code> with <code>- book hotel</code> nested under it\n- <b>On</b> — the Bar of <code>#todo</code> runs down both lines\n- <b>Off</b> — only <code>plan trip</code> gets a Bar. <code>book hotel</code> has no Value of its own, so it gets none, and <code>Join Bars in a tree</code> has no effect" },
    { kind:"toggle", id:"bars-join-tree", path:"visual.tagBars.joinTree", default:true,
      name:"Join Bars in a tree", desc:"A parent and its own children draw one unbroken Bar",
      searchTerms:["Tree gap"], visible: on("visual.tagBars.active"),
      tip:"Example: <code>- #todo :: plan trip</code> with <code>- book hotel</code> nested under it\n- <b>On</b> — the Bar of <code>#todo</code> runs unbroken from <code>plan trip</code> down into <code>book hotel</code>\n- <b>Off</b> — the Bar has a small break between the two lines, from <code>Vertical gap between Bars</code>\nLines that are not nested in each other stay apart either way" }
  ]
},
{
  id: "tagwheel", tab: "visual", order: 300, heading: "tagWheel",
  intro: "tagWheel is a picker that opens over the line. Your Fields run across it and the Values of the current Field run down. You pick a Value by looking instead of remembering a hotkey for each Field",
  tip: "Every Field has its own pair of hotkeys, which is too many to remember. Instead, one command opens the picker over the line. Left and right move between Fields, and up and down move between Values. <code>Tab</code> jumps to the Fields on the other side of your text, and <code>Escape</code> closes it without changing anything. The settings below control how it looks",
  commands: ["tagWheel Left", "tagWheel Right"],
  items: [
    { kind:"custom", id:"wheel-preview", render: wheelPreview },
    { kind:"custom", id:"panel-sub", render: subheader("Panel",
      "The strip drawn over your line: what each cell shows and the colors of the strip. The box of neighboring Values has its own rows below. You choose which Field it opens on in <code>Tags & PKM</code> → <code>tagWheel behavior</code>") },
    { kind:"toggle", id:"panel-markers", path:"visual.tagWheel.showMarkers", default:true,
      name:"Show tag markers", desc:"Show the hash and emoji in the picker, or just the words",
      searchTerms:["Show Prefix"],
      tip:"Changes only what the picker shows. What goes into your note is the same\n- <b>On</b> — the picker shows <code>#todo</code>\n- <b>Off</b> — the picker shows <code>todo</code>, which is quicker to read" },
    { kind:"dropdown", id:"panel-value-names", path:"visual.tagWheel.valueNames", default:"default",
      name:"tagWheel Value names", desc:"What the picker prints for a Field that already carries a Value",
      searchTerms:["Value names","Custom text in the picker","Printed name"],
      options:[ {value:"default",label:"Default"},
                {value:"custom",label:"Custom"},
                {value:"both",label:"Custom + default"} ],
      tip:"What the picker shows for a Field that has a Value. Example: <code>#idea</code> with the custom text <code>💡</code> under Fields (<code>Show</code> = <code>custom</code>)\n- <b>Default</b> — <code>#idea</code>\n- <b>Custom</b> — <code>💡</code>\n- <b>Custom + default</b> — <code>💡#idea</code>\nA Value without custom text always shows as written" },
    { kind:"toggle", id:"panel-highlight", path:"visual.tagWheel.highlightLine", default:true,
      name:"Highlight the tagWheel line", desc:"Mark the line while the picker is open, so it stands out from the page",
      searchTerms:["Highlight the line"],
      tip:"- <b>On</b> — while the picker is open, its line is wrapped in <code>==</code> and shows as highlighted, so it stands out from your note\n- <b>Off</b> — the picker looks like plain text on a busy page\n<code>Background color</code> below sets the color. The marks go away when the picker closes, and nothing is left in your note" },
    { kind:"color", id:"panel-text-color", path:"visual.tagWheel.textColor", default:"",
      name:"Inactive Field text color", desc:"The color of the Field names you are not standing on, while the line is marked",
      searchTerms:["Text color"],
      tip:"Colors the Fields you are not on. In the picker <code>#todo [Due] Imp</code> you stand on <code>Due</code>, so this colors <code>Imp</code>\n- <b>Empty</b> — your theme’s text color\n- <b>A color</b> — those Fields take that color\nWorks only while <code>Highlight the tagWheel line</code> is on. The box of neighboring Values is not affected",
      allowReset:true },
    { kind:"toggle", id:"panel-bold-names", path:"visual.tagWheel.boldFieldNames", default:false,
      name:"Bold Field names", desc:"Print every Field that shows its own name in bold, while the line is marked",
      searchTerms:["Bold names","Empty Fields in bold"],
      tip:"Example picker: <code>#todo [Due] Imp</code>, you stand on <code>Due</code>\n- <b>Off</b> — only the Field you are on, <code>[Due]</code>, is bold\n- <b>On</b> — <code>Imp</code> is bold too, so empty Fields stand out. <code>#todo</code> has a Value and stays regular\nNeeds <code>Highlight the tagWheel line</code> on" },
    { kind:"color", id:"panel-active-color", path:"visual.tagWheel.activeTextColor", default:"",
      name:"Active Field text color", desc:"The color of the Field you are on, while the line is marked",
      searchTerms:["Current Field color"],
      tip:"Colors the Field you are on, the one the up and down keys change. In <code>#todo [Due] Imp</code> that is <code>[Due]</code>\n- <b>Empty</b> — it uses <code>Inactive Field text color</code> and is easy to miss on a line with many Fields\n- <b>A color</b> — it stands out at a glance",
      allowReset:true },
    { kind:"color", id:"panel-chosen-color", path:"visual.tagWheel.chosenValueColor", default:"",
      name:"Chosen Value text color", desc:"The color of a Field that already carries a Value, while the line is marked",
      searchTerms:["Chosen value color","Picked value color"],
      tip:"Colors Fields that already have a Value, so you see at a glance what is filled in. In <code>#todo [Due] Imp</code> that is <code>#todo</code>\n- <b>Empty</b> — they use <code>Inactive Field text color</code>\n- <b>A color</b> — <code>#todo</code> takes that color, <code>Imp</code> does not\nThe Field you are on has its own row above",
      allowReset:true },
    { kind:"color", id:"panel-background", path:"visual.tagWheel.fillColor", default:"",
      name:"Background color", desc:"The color behind the picker, while the line is marked",
      searchTerms:["Background"],
      tip:"The color behind the picker line while it is open\n- <b>Empty</b> — Obsidian’s own highlight color\n- <b>A color</b> — that color. Pick one solid enough to read on\nNeeds <code>Highlight the tagWheel line</code> on", allowReset:true },
    { kind:"custom", id:"scroller-sub", render: subheader("Scroller",
      "A box of neighboring Values that opens from the Field you are on, so you can see what comes next. It has its own colors, separate from the panel. The preview at the top of this group shows both") },
    { kind:"toggle", id:"scroller-enabled", path:"visual.tagWheel.scroller.enabled", default:false,
      name:"Scroller", desc:"Show the next and previous Values around the current one",
      tip:"- <b>On</b> — a box next to the Field you are on lists the Values that come next, so long lists are quicker to go through\n- <b>Off</b> — you see only the current Value and step through blindly",
      searchTerms:["tagWheel Scroller"] },
    { kind:"dropdown", id:"scroller-direction", path:"visual.tagWheel.scroller.direction", default:"full",
      name:"Scroller opening direction", desc:"Which way the Values unroll from the Field you are on",
      tip:"- <b>Up</b> — one box above your line, with the Values the up key brings next. Your note below stays in view\n- <b>Down</b> — one box below your line, with the Values the down key brings next\n- <b>Both</b> — a box above and a box below, so the current Value sits in the middle. Easiest to read when a Field has many Values",
      searchTerms:["Scroller direction","Opens"], visible: on("visual.tagWheel.scroller.enabled"),
      options:[ {value:"up",label:"Up"}, {value:"down",label:"Down"},
                {value:"full",label:"Both"} ] },
    { kind:"dropdown", id:"scroller-labels", path:"visual.tagWheel.scroller.labels", default:"value",
      name:"Scroller Value names", desc:"What the box shows for each neighboring Value",
      tip:"What the box shows for each Value. Example: <code>#idea</code> with the custom text <code>💡</code> under Fields (<code>Show</code> = <code>custom</code>)\n- <b>Default</b> — <code>#idea</code>\n- <b>Custom</b> — <code>💡</code>\n- <b>Custom + default</b> — <code>💡#idea</code>\nA Value without custom text always shows as written",
      searchTerms:["Scroller names","Custom text in the scroller","Printed name","As written","Custom text when set"],
      visible: on("visual.tagWheel.scroller.enabled"),
      options:[ {value:"value",label:"Default"},
                {value:"custom",label:"Custom"},
                {value:"both",label:"Custom + default"} ] },
    { kind:"color", id:"scroller-fill", path:"visual.tagWheel.scroller.fillColor", default:"",
      name:"Scroller background color", desc:"The color behind the box of neighboring Values",
      searchTerms:["Scroller background"],
      tip:"- <b>Empty</b> — the box uses your theme’s popup color\n- <b>A color</b> — the box gets that color, for example to stand out on a pale theme. Without its own text color the text turns black or white so you can read it",
      visible: on("visual.tagWheel.scroller.enabled"), allowReset:true },
    { kind:"color", id:"scroller-text", path:"visual.tagWheel.scroller.textColor", default:"",
      name:"Scroller text color", desc:"The color of the Values you are not on, inside the box",
      searchTerms:["Scroller text"],
      tip:"Colors the Values listed in the box\n- <b>Empty</b> — your theme’s text color, or black or white on your own <code>Scroller background color</code>\n- <b>A color</b> — the Values in the box take that color\nThe Value you are on is not in the box. It shows in the line, colored by <code>Active Field text color</code>",
      visible: on("visual.tagWheel.scroller.enabled"), allowReset:true },
    { kind:"slider", id:"scroller-size", path:"visual.tagWheel.scroller.size", default:3,
      min:1, max:20, step:1,
      name:"Scroller size", desc:"How many neighboring Values stay visible around the current one",
      tip:"How many Values the box shows on each side of the current one, not in total\n- <b>1</b> — one Value above and one below, with <code>Both</code>\n- <b>3</b> — up to three above and three below\n- <b>20</b> — every Value of a short Field at once",
      searchTerms:["Values per side"], visible: on("visual.tagWheel.scroller.enabled") }
  ]
},
{
  id: "text-cursor", tab: "visual", order: 400, heading: "Text cursor",
  intro: "The blinking line that shows where your typing goes. Give it its own color so it stops getting lost on the page",
  tip: "By default the cursor is the same color as your text, so in long notes or one-color themes it is easy to lose. Pick a color you use nowhere else and it stands out at a glance. This changes the cursor in your notes only. This window and the search box keep their usual cursor",
  items: [
    { kind:"toggle", id:"caret-enabled", path:"visual.caret.enabled", default:false,
      name:"Color the text cursor", desc:"Draw the blinking caret in a color you pick instead of the color of your text",
      searchTerms:["Caret color","Cursor color"],
      tip:"- <b>On</b> — the blinking cursor in your notes takes the color you pick below, for example bright orange\n- <b>Off</b> — your theme decides the cursor color\nThis window and the search box keep their usual cursor" },
    { kind:"color", id:"caret-color", path:"visual.caret.color", default:"",
      name:"Cursor color", desc:"The color of the blinking caret in your notes",
      searchTerms:["Caret"], visible: on("visual.caret.enabled"),
      tip:"- <b>Empty</b> — the cursor keeps your theme’s color\n- <b>A color</b> — the cursor takes it. Pick a color your page does not already use, and it stands out at a glance", allowReset:true },
    { kind:"toggle", id:"caret-shape", path:"visual.caret.shapeEnabled", default:false,
      name:"Shape the text cursor", desc:"Set how thick the caret is and how fast it blinks, instead of taking both from your theme",
      searchTerms:["Caret width","Cursor blink","Caret thickness"],
      tip:"Works apart from the color, so you can use either one alone\n- <b>On</b> — the cursor uses <code>Cursor width</code> and <code>Blink speed</code> below\n- <b>Off</b> — the cursor keeps the thickness and blinking your theme and Obsidian give it" },
    { kind:"slider", id:"caret-width", path:"visual.caret.width", default:2,
      min:1, max:8, step:1, unit:"px",
      name:"Cursor width", desc:"How thick the caret is drawn, in pixels",
      searchTerms:["Caret thickness"], visible: on("visual.caret.shapeEnabled"),
      tip:"Obsidian’s cursor is about one pixel wide and easy to miss on a bright background or a large screen\n- <b>1</b> — a thin line, like Obsidian’s own\n- <b>2</b> or <b>3</b> — easy to find and still not like a selection\n- <b>8</b> — a thick line" },
    { kind:"slider", id:"caret-blink", path:"visual.caret.blinkSpeed", default:5,
      min:0, max:10, step:1,
      name:"Blink speed", desc:"How fast the caret blinks, from not blinking at all to very fast",
      searchTerms:["Blink rate","Cursor blinking"], visible: on("visual.caret.shapeEnabled"),
      tip:"- <b>0</b> — the cursor does not blink. The calmest setting\n- <b>1</b> — a slow blink, once every 2 seconds\n- <b>5</b> — Obsidian’s usual speed, once every 1.2 seconds\n- <b>10</b> — a fast blink, five times a second" },
    { kind:"custom", id:"caret-preview", render: caretPreview }
  ]
},
{
  id: "jump-highlight", tab: "visual", order: 450, heading: "Cursor jump highlight",
  intro: "After a jump, the cursor is hard to find again. This shows a circle where it lands, and the circle shrinks away by itself",
  tip: "The circle only appears on screen for a moment. Nothing is written into your note. It shows only on jumps, not when you type or use the arrow keys. The last row decides whether short hops within one line count as jumps too",
  commands: ["Jump up", "Jump down"],
  items: [
    { kind:"toggle", id:"jump-flash", path:"visual.jumpFlash.enabled", default:false,
      name:"Highlight where you land", desc:"Draw a fading circle where the cursor lands, so you do not hunt for it",
      searchTerms:["Flash on jump","Highlight the jump target","Show me where the cursor went"],
      tip:"- <b>On</b> — after a jump like <code>Jump down</code>, a colored circle appears on the cursor and shrinks away\n- <b>Off</b> — no circle\nTyping and the arrow keys never show it. Nothing is written into your note" },
    { kind:"color", id:"jump-flash-color", path:"visual.jumpFlash.color", default:"",
      allowReset:true,
      name:"Highlight color", desc:"Leave it unset to use the accent color of your theme",
      searchTerms:["Color of the jump circle"],
      tip:"- <b>Unset</b> — the circle takes your theme’s accent color and matches the editor\n- <b>A color</b> — the circle takes that color. Useful when the accent color is too faint on your background",
      visible: on("visual.jumpFlash.enabled") },
    { kind:"slider", id:"jump-flash-radius", path:"visual.jumpFlash.radius", default:18,
      min:6, max:40, step:1, unit:"px",
      name:"Highlight size", desc:"How wide the circle is at the moment it appears",
      searchTerms:["Size of the jump circle"],
      tip:"How big the circle is when it appears. The number is the distance from the cursor to its edge\n- <b>6</b> — a small dot, not much easier to spot than the cursor\n- <b>18</b> — a circle about 36 pixels across\n- <b>40</b> — a big circle that covers the words around until it fades",
      visible: on("visual.jumpFlash.enabled") },
    { kind:"slider", id:"jump-flash-fade", path:"visual.jumpFlash.fadeMs", default:450,
      min:100, max:1500, step:50, unit:"ms",
      name:"How long it lasts", desc:"The time the circle takes to shrink and disappear",
      searchTerms:["Fade speed of the jump circle"],
      tip:"- <b>100</b> — a quick flash that just catches the corner of your eye\n- <b>450</b> — the circle shrinks away in about half a second\n- <b>1500</b> — a slow fade that gets annoying when you jump several times in a row\nTo skip circles while you jump quickly, use the row below",
      visible: on("visual.jumpFlash.enabled") },
    { kind:"slider", id:"jump-flash-delay", path:"visual.jumpFlash.quietMs", default:0,
      min:0, max:1000, step:50, unit:"ms",
      name:"Minimum time between jumps", desc:"Jumps closer together than this get no circle at all",
      searchTerms:["Do not flash on every jump","Quiet time"],
      tip:"Waits this long after a jump before the circle shows. A new jump in that time cancels it, so only the jump you stop on gets a circle\n- <b>0</b> — every jump gets a circle at once, even when you hold a key down\n- <b>300</b> — the circle shows 0.3 seconds after your last jump",
      visible: on("visual.jumpFlash.enabled") },
    { kind:"toggle", id:"jump-flash-inline", path:"visual.jumpFlash.inLine", default:false,
      name:"Use inside current line", desc:"Also mark the cursor when it hops between the parts of one line",
      searchTerms:["Flash on in-line jumps"],
      tip:"<code>Jump left</code> and <code>Jump right</code> move the cursor a short way along one line\n- <b>On</b> — those short hops show a circle too. Helps if you lose the cursor on long lines\n- <b>Off</b> — short hops show no circle, since the cursor usually stays where you are looking",
      visible: on("visual.jumpFlash.enabled") },
    { kind:"custom", id:"jump-flash-preview", render: jumpFlashPreview,
      visible: on("visual.jumpFlash.enabled") }
  ]
},
{
  id: "user-tag-colors", tab: "visual", order: 500, heading: "Color custom tags",
  intro: "Colors for tags you type yourself that are not a Value of any Field in <code>Tags & PKM → Fields</code>. These tags still get a bubble, and here you choose how it looks",
  tip: "Each row is one tag. You set the bubble color, the text color, and whether it shows the word, the word with its hash, or nothing. Values of a Field get their colors on <code>Tags & PKM</code>. Use these rows for every other tag, including tags added by other plugins. Leave a color unset and the tag follows your theme",
  items: [
    { kind:"custom", id:"user-tag-list", render: userTagColors }
  ]
}
];
