/**
 * ВНИМАНИЕ: файл сгенерирован из docs/prototype/settings_prototype.html.
 * Руками не правится. Правится прототип, затем `npm run gen:schema`.
 *
 * Тексты согласованы заказчиком и совпадают с Приложением B PRD.
 */

import type { SettingsGroup } from "../types.ts";
import { on } from "../types.ts";
import { callout } from "../custom/callouts.ts";
import { barsPreview, caretPreview, tagPreview, wheelPreview } from "../custom/previews.ts";
import { userTagColors } from "../custom/user_tags.ts";

export const VISUAL_GROUPS: readonly SettingsGroup[] = [
{ id: "visual-intro",    tab: "visual",     order: 50, heading: "Before you start",
  items: [
    { kind:"custom", id:"visual-callout", render: callout("visual") }
  ],
  visible: on("general.help.showCallouts") },
{
  id: "tag-appearance", tab: "visual", order: 100, heading: "Inline appearance",
  intro: "How a tagged line looks while you write. Tags are drawn as small colored bubbles; links and dates stay ordinary text. Nothing here changes a single character in your file",
  tip: "Everything in this block is drawing only: the file on disk is the same either way, and the line reads normally anywhere else. The two <b>opacity</b> rows fade the Blocks on each side of your text so the text itself stands out — they reach the tags, the dates and the links, and stop at the text between the Separators, because that part is yours. The size and shape rows below them apply to the same two Blocks. <b>Color Left\\Right blocks</b> puts a band behind each of them, from its first Value to its last, so the two are visible at a glance. Colors of individual Values live with the Field that offers them, on the <code>Tags & PKM</code> tab",
  items: [
    { kind:"custom", id:"tag-preview", render: tagPreview },
    { kind:"slider", id:"tags-opacity-left", path:"visual.tags.opacityLeft", default:100,
      min:0, max:100, step:1, unit:"%",
      name:"Opacity of the Left Block", desc:"Dims everything written before your text, tags and elements alike",
      tip:"Dimming is not hiding: at 0 the Left Block is still on the line, still searchable and still moved by the commands — it just steps out of the way while you read. Most people take it down a little so the sentence leads and the tags follow",
      searchTerms:["Opacity Left"],
      seeAlso:{ id:"field-editor", label:"Tag colors are set per Value under Fields" } },
    { kind:"slider", id:"tags-opacity-right", path:"visual.tags.opacityRight", default:100,
      min:0, max:100, step:1, unit:"%",
      name:"Opacity of the Right Block", desc:"Dims everything written after your text, tags and elements alike",
      tip:"The same dial for the other end of the line, and it is separate on purpose: dates and links after your text are usually worth less attention than the tags before it. At 0 everything after your text is still there and still works",
      searchTerms:["Opacity Right"] },
    { kind:"toggle", id:"tags-block-fill", path:"visual.tags.blockFill.enabled", default:false,
      /* Заказчик назвал строку `Color Left\\Right blocks`. В панели она стоит
         как `Color the Blocks`: правило имён держит `Left Block` и `Right Block`
         парой и не пускает имя длиннее пяти слов, а `Left\\Right` — ни то ни
         другое. Смысл тот же, и обе стороны названы в описании. */
      name:"Color the Blocks", desc:"A band behind the Left Block and the Right Block, so the two stand out from your text",
      searchTerms:["Block background", "Color the Blocks"],
      tip:"The band runs from the first Value of a Block to its last one, and stops there: your own text between the Separators keeps the page background. A Block with nothing in it gets no band. The band sits <b>behind</b> the writing, so everything on the line stays selectable and clickable. Tag bubbles carry their own color, so a Block of one tag would hide the band completely — the two rows at the bottom are how far it reaches past the writing, and that is what makes it show at all" },
    { kind:"color", id:"tags-block-fill-color", path:"visual.tags.blockFill.color", default:"",
      name:"Block color", desc:"Leave it unset and the band follows your theme",
      tip:"Unset means the accent color of whatever theme you are using, so the band keeps looking right when you change themes. Pick a color here only when you want a particular one",
      visible: on("visual.tags.blockFill.enabled") },
    { kind:"slider", id:"tags-block-fill-opacity", path:"visual.tags.blockFill.opacity", default:12,
      min:0, max:100, step:1, unit:"%",
      name:"Block color strength", desc:"How strongly the band shows through",
      tip:"Low numbers are the point: the band is there to catch the eye, not to be read. Around a tenth is enough to see where a Block begins and ends without fighting the writing on top of it",
      visible: on("visual.tags.blockFill.enabled") },
    { kind:"slider", id:"tags-block-fill-height", path:"visual.tags.blockFill.heightPct", default:60,
      min:0, max:100, step:20, unit:"%",
      name:"Band height", desc:"How far the band reaches above and below the writing",
      tip:"The scale has two landmarks. At <code>0</code> the band is exactly as tall as the writing — and a tag bubble has its own color, so a Block of one tag would hide it. At <code>100</code> it fills the line it belongs to, so the bands of two neighbouring lines meet and never overlap. In between it takes that much of the room the line has left, which is why every step moves the band on any theme, whatever its line spacing",
      visible: on("visual.tags.blockFill.enabled") },
    { kind:"slider", id:"tags-block-fill-width", path:"visual.tags.blockFill.widthPct", default:50,
      min:0, max:100, step:5, unit:"%",
      name:"Band width", desc:"How far the band reaches past the Block on both of its sides",
      tip:"The scale has three landmarks. At <code>0</code> the band starts on the first Value of the Block and ends on the last one. At <code>50</code> it touches the Separator on the inner side, and steps out by the same distance on the other. At <code>100</code> it takes the Separator in as well. The Left Block is the one exception: it never reaches onto the bullet or the checkbox, whatever the number says",
      visible: on("visual.tags.blockFill.enabled") },
    { kind:"slider", id:"tags-text-size", path:"visual.tags.textSizePct", default:100,
      min:50, max:140, step:5, unit:"%",
      name:"Text size", desc:"How big everything in the two Blocks is written, next to the rest of your note",
      tip:"This reaches the whole of both Blocks, not the tags alone: the writing in the bubbles, the dates and the links all change together. Your own text between the Separators keeps its size. Below 100 the Blocks step back and your sentence leads. Above 100 they compete with it. Most people end up a little under 100",
      searchTerms:["Tag text size"] },
    { kind:"slider", id:"tags-bubble-width", path:"visual.tags.bubbleWidthPct", default:100,
      min:20, max:140, step:5, unit:"%",
      name:"Tags bubble width", desc:"How much breathing room there is either side of the word",
      tip:"This is the padding either side of the word, not the word itself: the writing keeps its size, the bubble around it grows. At the bottom of the scale the word starts almost at the edge of the bubble; above 100 the bubbles read as separate chips even in a crowded Block",
      searchTerms:["Tag bubble size - width", "Bubble width"] },
    { kind:"slider", id:"tags-bubble-height", path:"visual.tags.bubbleHeightPct", default:100,
      min:20, max:140, step:5, unit:"%",
      name:"Tag bubble height", desc:"How tall the bubble is around the word",
      tip:"Keep this modest: a tall bubble pushes the lines of your note apart and the page starts to feel airy in a way that is hard to read. At the bottom of the scale the bubble closes in on the word from above and below",
      searchTerms:["Tag bubble size - height", "Bubble height"] },
    { kind:"slider", id:"tags-empty-bubble", path:"visual.tags.emptyBubblePct", default:100,
      min:10, max:180, step:5, unit:"%",
      name:"Empty tags bubble width", desc:"Width of a bubble whose <code>Show</code> is set to <code>empty</code>",
      searchTerms:["Empty bubble size", "Empty bubble width"],
      tip:"Under <code>Fields</code> a Value can be set to <code>empty</code>, which draws its color but no text — a marker instead of a word. This is how wide that marker gets",
      seeAlso:{ id:"field-editor", label:"Set a Value to empty under Fields" } },
    { kind:"slider", id:"tags-corners", path:"visual.tags.cornersPct", default:0,
      min:0, max:100, step:1,
      name:"Tags bubble corners", desc:"Slide from fully rounded to completely square",
      tip:"At 0 the bubble is a pill, at 100 a rectangle. Nothing else changes — the same colour, the same padding, the same size of writing. Square corners read as denser and pair well with narrow bubbles",
      searchTerms:["Tag shape", "Bubble corners"] }
  ]
},
{
  id: "user-tag-colors", tab: "visual", order: 150, heading: "Color your Tags",
  intro: "Colors for tags that are not a Value of any Field. A tag you type straight into a line still gets a bubble, and this is where you say what that bubble looks like",
  tip: "Every tag in a note is drawn as a bubble, whether the plugin put it there or you typed it. Each row below is one tag: the fill behind it, the color of the writing on it, and whether the bubble shows the word, the word with its hash, or nothing at all. Values of a Field take their colors from the Field, under <code>Tags & PKM</code>. Everything else \u2014 a tag you typed once, a tag another plugin put there \u2014 has no Field to belong to, and this is where it gets its look. Leave a color unset and the tag follows your theme, and keeps following it when the theme changes",
  items: [
    { kind:"custom", id:"user-tag-list", render: userTagColors }
  ]
},
{
  id: "tag-bars", tab: "visual", order: 200, heading: "Tag Bars",
  intro: "A colored Bar in the margin, so you can see at a glance what a whole block of lines is about without reading their tags. The Bar runs down the side of the line and everything nested under it",
  tip: "Bars are drawn from the colors of one Field, and you pick which one below. Only a tag Field can do it: the color of a Bar is the color of a Value, and links and dates have none. A Bar belongs to the line that carries the Value and runs the full height of that line and everything nested under it; a deeper line with a Value of its own gets its own Bar in the next lane along, so the number of lanes follows how deep your lists go. Bars sit in the margin, so the text column never moves, and you can hide the tag itself once its Bar says the same thing",
  items: [
    { kind:"custom", id:"bars-preview", render: barsPreview },
    { kind:"toggle", id:"bars-active", path:"visual.tagBars.active", default:false,
      name:"Tag Bars", desc:"Draw the Bars",
      tip:"The Bars are drawn to the left of the line and say, without a word of text, which Value it carries and how deep it sits in the list. They read the colours you gave the Values of one Field — the row below picks which — so nothing has to be coloured twice. Off, nothing is drawn and the settings under it are kept",
      searchTerms:["Activate strip","Strip","Hierarchy Bars","Level Bars"] },
    { kind:"dropdown", id:"bars-field", path:"visual.tagBars.fieldId", default:"",
      name:"Which Field draws Bars", desc:"Bars work with tag Fields only, and only for the one chosen here",
      searchTerms:["Strip Field"], visible: on("visual.tagBars.active"),
      /* Список — ваши Fields, а не эти два имени: они мокданные прототипа
         (Р8), и в панели их быть не должно. Первая строка отвечает за
         значение по умолчанию: без неё список показывал первый Field,
         когда не выбрано ничего (замечание заказчика 1.5.3.2). */
      options:[ {value:"",label:"No Field chosen"} ], optionsFrom:"tag-fields",
      tip:"Pick the one thing you scan a page for \u2014 usually how far along something is, or how urgent it is. The list is your own tag Fields: a Field of another type has no Value color, and a Bar is drawn in the color of the Value. Switch between Fields and the Bars in the preview above change shape, not just color, because different lines carry different Fields",
      seeAlso:{ id:"field-editor", label:"Bar colors are the Value colors under Fields" } },
    { kind:"slider", id:"bars-count", path:"visual.tagBars.stripesToShow", default:2,
      min:1, max:3, step:1,
      name:"Number of Bars", desc:"How far down the nesting to keep drawing them",
      searchTerms:["Stripes to show"], visible: on("visual.tagBars.active"),
      tip:"At 1 only the parent line gets a Bar, however deep the tree goes. At 2 a child with a Value of its own gets a second Bar beside the first. At 3 a grandchild gets a third. A line with no Value never gets one" },
    { kind:"toggle", id:"bars-show-tag", path:"visual.tagBars.tagVisibility", default:true,
      name:"Show the Field's tag", desc:"Keep the tag on the line, or let the Bar speak for it",
      searchTerms:["Strip tag visibility"], visible: on("visual.tagBars.active"),
      tip:"With the Bar already showing you the Value by color, the tag itself is often redundant. Hiding it buys back room on the line; the text stays in your note and stays searchable" },
    { kind:"toggle", id:"bars-hide-separator", path:"visual.tagBars.hideSeparatorWhenOnlyStripToken", default:false,
      name:"Hide the leftover marker", desc:"Tidy away a Separator that has nothing left beside it",
      searchTerms:["Hide Separator?"],
      visible:{ deps:["visual.tagBars.active","visual.tagBars.tagVisibility"],
                test: c => Boolean(c.get("visual.tagBars.active")) && !c.get("visual.tagBars.tagVisibility") },
      tip:"If the hidden tag was the only thing in front of your text, the line is left starting with a bare Separator and nothing before it. This clears that up" },
    { kind:"dropdown", id:"bars-mode", path:"visual.tagBars.mode", default:"default",
      name:"Bar arrangement", desc:"Which lane each level of the tree draws its Bar in",
      searchTerms:["Strip mode"], visible: on("visual.tagBars.active"),
      options:[ {value:"default",label:"Parent keeps the outer lane"}, {value:"crossing",label:"Lanes rotate"} ],
      tip:"Bars are drawn in lanes, one per level, left to right. With <b>parent keeps the outer lane</b> the top line of a tree always owns the leftmost lane, its child the next one in, and so on \u2014 so a lane always means the same depth, and you can read nesting by counting from the left. With <b>lanes rotate</b> each new level takes the next lane round in turn, which keeps deep trees narrower but means a lane no longer tells you the depth" },
    { kind:"slider", id:"bars-thickness", path:"visual.tagBars.thickness", default:2,
      min:1, max:12, step:1, unit:"px",
      name:"Bar thickness", desc:"How wide each Bar is",
      tip:"One number for every Bar: they are read as a group, and a group of different widths reads as a mistake. Thin lines suit a dense note; wide ones are easier to tell apart when your Values are close in colour",
      searchTerms:["Strip thickness"], visible: on("visual.tagBars.active") },
    { kind:"slider", id:"bars-gap", path:"visual.tagBars.childOffset", default:12,
      min:2, max:20, step:1, unit:"px",
      name:"Space between Bars", desc:"The gap between one level and the next",
      tip:"Each level of the list gets its own lane, and this is the empty space between two lanes. Tight spacing makes a deep list read as one ribbon; wide spacing keeps the levels apart but takes room from the text",
      searchTerms:["Parent/child strip distance"], visible: on("visual.tagBars.active") },
    { kind:"slider", id:"bars-distance", path:"visual.tagBars.spacing", default:20,
      min:8, max:48, step:1, unit:"px",
      name:"Distance from the text", desc:"How far the Bars sit from where your line begins",
      tip:"The whole group of Bars moves together, away from where your text begins. Give it room if your notes are indented and the Bars crowd the list markers",
      searchTerms:["Strip spacing"], visible: on("visual.tagBars.active") },
    { kind:"slider", id:"bars-line-gap", path:"visual.tagBars.lineGap", default:2,
      min:0, max:8, step:1, unit:"px",
      name:"Gap between Bars", desc:"Blank left above and below a Bar, so two lines in a row stay apart",
      searchTerms:["Bar height"], visible: on("visual.tagBars.active"),
      tip:"Two lines one under the other used to give one unbroken Bar, and there was no telling which line owned which part of it. A small gap draws that boundary. The number is the blank above and below, so a bigger number means a shorter Bar; at <code>0</code> the Bars meet again" },
    { kind:"toggle", id:"bars-whole-tree", path:"visual.tagBars.drawWholeTree", default:true,
      name:"Bars for the whole tree", desc:"A Bar runs down everything nested under its line, not just the line itself",
      searchTerms:["Draw bars for the whole tree","Bars for subtree"], visible: on("visual.tagBars.active"),
      tip:"On, a line with a Value draws its Bar down its own line and everything indented under it, and a deeper line with a Value of its own adds a Bar in the next lane along \u2014 so a nested line can carry several. Off, a Bar belongs to one line and nothing is inherited: a line without a Value of its own gets none at all, and <code>Join Bars in a tree</code> below has nothing left to join" },
    { kind:"toggle", id:"bars-join-tree", path:"visual.tagBars.joinTree", default:true,
      name:"Join Bars in a tree", desc:"A parent and its own children draw one unbroken Bar",
      searchTerms:["Tree gap"], visible: on("visual.tagBars.active"),
      tip:"The gap that keeps two neighboring lines apart also cuts the Bar of a tree, where it stands for one thing running down through the nesting. With this on, the gap is dropped wherever a Bar carries on from a parent into its own children, and kept between lines that have nothing to do with each other" }
  ]
},
{
  id: "tagwheel", tab: "visual", order: 300, heading: "TagWheel",
  intro: "TagWheel opens over the line and lays your Fields out across it, with the Values of the Field you are on running down",
  tip: "Every Field has its own pair of cycle commands, and one key each adds up to more keys than anyone remembers. TagWheel is the way round that: one command opens a picker over the line, with your Fields laid out across it and the Values of the Field you are on running down it, so you choose by looking instead of by memory. Steer it with the arrow keys: left and right move between Fields, up and down between that Field\u2019s Values. <code>Tab</code> jumps across to the Fields on the other side of your text, and <code>Escape</code> closes it without changing anything. The settings below decide how the picker looks, and whether the neighboring Values stay in sight as you move",
  commands: ["Open TagWheel on the left", "Open TagWheel on the right"],
  items: [
    { kind:"custom", id:"wheel-preview", render: wheelPreview },
    { kind:"toggle", id:"panel-markers", path:"visual.tagWheel.showMarkers", default:true,
      name:"Show tag markers", desc:"Show the hash and emoji in the picker, or just the words",
      searchTerms:["Show Prefix"],
      tip:"A column of words reads faster than a column of words with hashes in front. What actually goes into your note is the same either way" },
    { kind:"toggle", id:"panel-highlight", path:"visual.tagWheel.highlightLine", default:true,
      name:"Highlight the TagWheel line", desc:"Mark the line while the picker is open, so it stands out from the page",
      searchTerms:["Highlight the line"],
      tip:"TagWheel draws itself over the line you are on, and on a busy page it is not always clear where the picker ends and your note begins. On, the line is wrapped in <code>==</code> for as long as the picker is open, and that is what paints it: <code>Background color</code> below gives the color, and without one Obsidian uses its own highlight. The marks belong to the picker, not to your line — they leave with it, and nothing stays behind in the note" },
    { kind:"color", id:"panel-text-color", path:"visual.tagWheel.textColor", default:"",
      name:"Non-active Field text color", desc:"The color of the Field names you are not standing on, while the line is marked",
      searchTerms:["Text color"],
      tip:"This paints the picker drawn over your line, and only while <code>Highlight the TagWheel line</code> is on: without the marks there is nothing to paint. The scroller box below takes its colors from your theme and is not affected",
      allowReset:true },
    { kind:"color", id:"panel-active-color", path:"visual.tagWheel.activeTextColor", default:"",
      name:"Active Field text color", desc:"The color of the Field you are on, while the line is marked",
      searchTerms:["Current Field color"],
      tip:"The Field you are standing in is the one the up and down keys move through. Without its own color it differs from the rest only by weight, and on a line with many Fields that is easy to lose. Empty means it takes <code>Non-active Field text color</code> like the others",
      allowReset:true },
    { kind:"color", id:"panel-background", path:"visual.tagWheel.fillColor", default:"",
      name:"Background color", desc:"The color behind the picker, while the line is marked",
      searchTerms:["Background"],
      tip:"Pick something solid enough to read against your note, since the picker is drawn on top of your text. Like <code>Non-active Field text color</code>, it needs <code>Highlight the TagWheel line</code> on: the marks are what carries the color", allowReset:true },
    { kind:"toggle", id:"scroller-enabled", path:"visual.tagWheel.scroller.enabled", default:false,
      name:"Scroller", desc:"Show the next and previous Values around the current one",
      tip:"Off, you see only where you are and step blindly. On, you see what is coming, which makes a long list much quicker to work through",
      searchTerms:["TagWheel Scroller"] },
    { kind:"dropdown", id:"scroller-direction", path:"visual.tagWheel.scroller.direction", default:"full",
      name:"Scroller opening direction", desc:"Which way the Values unroll from the Field you are on",
      tip:"The scroller shows the Values around the one you are on. Upwards keeps your line at the bottom of it and your note visible below; downwards does the opposite. <code>Both ways</code> centres the current Value and is easiest to read when a Field has many Values",
      searchTerms:["Scroller direction","Opens"], visible: on("visual.tagWheel.scroller.enabled"),
      options:[ {value:"up",label:"Upwards"}, {value:"down",label:"Downwards"},
                {value:"full",label:"Both ways"} ] },
    { kind:"color", id:"scroller-fill", path:"visual.tagWheel.scroller.fillColor", default:"",
      name:"Scroller background color", desc:"The color behind the box of neighboring Values",
      searchTerms:["Scroller background"],
      tip:"Leave it empty and the box takes the color your theme gives a popover. Set it and the box stands out from the note even where the theme is pale",
      visible: on("visual.tagWheel.scroller.enabled"), allowReset:true },
    { kind:"color", id:"scroller-text", path:"visual.tagWheel.scroller.textColor", default:"",
      name:"Scroller text color", desc:"The color of the Values you are not on, inside the box",
      searchTerms:["Scroller text"],
      tip:"Empty means the color your theme gives ordinary text. The Value you are standing on is not in the box at all — it is drawn in the line itself, and <code>Active Field text color</code> above is what paints it",
      visible: on("visual.tagWheel.scroller.enabled"), allowReset:true },
    { kind:"slider", id:"scroller-size", path:"visual.tagWheel.scroller.size", default:3,
      min:1, max:20, step:1,
      name:"Scroller size", desc:"How many neighboring Values stay visible around the current one",
      tip:"How many neighbours are shown on each side, not in total. A small number keeps the scroller out of the way; a large one lets you see the whole set of a short Field at once. It never shows more than the Field has",
      searchTerms:["Values per side"], visible: on("visual.tagWheel.scroller.enabled") },
    { kind:"dropdown", id:"wheel-edge", path:"visual.tagWheel.edgeMode", default:"stay",
      name:"TagWheel navigation behavior", desc:"What the arrow keys do when there is no next Field on this side",
      searchTerms:["Edge of a Block","Wrap around","Move to the next Block","At the last Field"],
      options:[ {value:"stay",label:"Stay in the same Block"},
                {value:"next-block",label:"Move to the next Block"} ],
      tip:"The left and right Blocks each hold their own Fields, and the arrows walk along one of them. <code>Stay in the same Block</code> keeps you there: past the last Field you land back on the first. <code>Move to the next Block</code> makes the two into one ring — step right off the end of the left Block and you arrive at the first Field of the right one, step left off its start and you arrive at the last. <code>Tab</code> switches Blocks either way" }
  ]
},
{
  id: "text-cursor", tab: "visual", order: 400, heading: "Text cursor",
  intro: "The blinking line that shows where your typing will land. Give it a color of its own and it stops disappearing into the page",
  tip: "Obsidian draws the caret in the color of your text, which is the color everything else on the page already is. In a long note, or in a theme built on one shade, that makes it easy to lose and easy to leave behind. Pick a color that appears nowhere else in your writing and you can find the caret at a glance. This is the caret in your notes only: the boxes in this window and in the search box keep the one they had",
  items: [
    { kind:"toggle", id:"caret-enabled", path:"visual.caret.enabled", default:false,
      name:"Color the text cursor", desc:"Draw the blinking caret in a color you pick instead of the color of your text",
      searchTerms:["Caret color","Cursor color"],
      tip:"Off, the caret is whatever your theme makes it. On, the color below takes over, and only in the editor" },
    { kind:"color", id:"caret-color", path:"visual.caret.color", default:"",
      name:"Cursor color", desc:"The color of the blinking caret in your notes",
      searchTerms:["Caret"], visible: on("visual.caret.enabled"),
      tip:"Empty means the color your theme gives the caret. A color that stands well apart from your text is the whole point of this: something the page does not already use", allowReset:true },
    { kind:"toggle", id:"caret-shape", path:"visual.caret.shapeEnabled", default:false,
      name:"Shape the text cursor", desc:"Set how thick the caret is and how fast it blinks, instead of taking both from your theme",
      searchTerms:["Caret width","Cursor blink","Caret thickness"],
      tip:"Separate from the color above, and neither needs the other. Off, the caret keeps the thickness and the blinking your theme and Obsidian give it" },
    { kind:"slider", id:"caret-width", path:"visual.caret.width", default:2,
      min:1, max:8, step:1, unit:"px",
      name:"Cursor width", desc:"How thick the caret is drawn, in pixels",
      searchTerms:["Caret thickness"], visible: on("visual.caret.shapeEnabled"),
      tip:"Obsidian draws it a little over one pixel wide, which disappears on a bright background and on a large screen. Two or three is enough to find it without it reading as a selection" },
    { kind:"slider", id:"caret-blink", path:"visual.caret.blinkSpeed", default:5,
      min:0, max:10, step:1,
      name:"Blink speed", desc:"How fast the caret blinks, from not blinking at all to very fast",
      searchTerms:["Blink rate","Cursor blinking"], visible: on("visual.caret.shapeEnabled"),
      tip:"At <code>0</code> the caret stops blinking and simply stays where it is, which is the quietest a cursor gets. <code>5</code> is the speed Obsidian uses now, and every step up from there is quicker" },
    { kind:"custom", id:"caret-preview", render: caretPreview }
  ]
}
];
